//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "AFSyncChangeInfo-Protocol.h"

@class NSString, SADomainObject;

@interface ASSyncChangeInfo : NSObject <AFSyncChangeInfo>
{
    _Bool isDelete;	// 8 = 0x8
    SADomainObject *object;	// 16 = 0x10
    NSString *postAnchor;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000045f8
@property(nonatomic) _Bool isDelete; // @synthesize isDelete;
@property(copy, nonatomic) NSString *postAnchor; // @synthesize postAnchor;
@property(retain, nonatomic) SADomainObject *object; // @synthesize object;
- (id)description;	// IMP=0x00000001000044c0

@end

