//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MobileBackup/MBEngine.h>

#import "MBDeviceTransferProgressModelDelegate-Protocol.h"
#import "MBProgressDelegate-Protocol.h"

@class MBConnection, MBDeviceLockAssertion, MBDeviceTransferKeychain, MBDeviceTransferLocalDrive, MBDeviceTransferPreflight, MBDeviceTransferProgressModel, MBPeerInitResponse, MBPeerKeychainTransferResponse, MBPeerTransferDrive, MBPowerAssertion, NSDate, NSError, NSObject, NSString, RPFileTransferSession;
@protocol MBServiceManagerDeviceTransferDelegate, OS_dispatch_group, OS_dispatch_queue, OS_dispatch_semaphore, OS_dispatch_source, OS_os_transaction;

@interface MBTargetDeviceTransferEngine : MBEngine <MBProgressDelegate, MBDeviceTransferProgressModelDelegate>
{
    _Atomic _Bool _canceled;	// 56 = 0x38
    _Atomic _Bool _finished;	// 57 = 0x39
    _Atomic _Bool _peerConnectedOnce;	// 58 = 0x3a
    _Atomic _Bool _peerConnected;	// 59 = 0x3b
    _Atomic _Bool _trackPeerConnectionStatus;	// 60 = 0x3c
    _Atomic _Bool _sendingDoneMessage;	// 61 = 0x3d
    _Atomic _Bool _sentDoneMessage;	// 62 = 0x3e
    _Atomic _Bool _receivedDoneMessage;	// 63 = 0x3f
    _Atomic _Bool _sendingRestoreProgressMessage;	// 64 = 0x40
    MBConnection *_connection;	// 72 = 0x48
    id <MBServiceManagerDeviceTransferDelegate> _delegate;	// 80 = 0x50
    CDUnknownBlockType _completionHandler;	// 88 = 0x58
    double _startTime;	// 96 = 0x60
    NSObject<OS_dispatch_queue> *_queue;	// 104 = 0x68
    NSObject<OS_dispatch_queue> *_sessionQueue;	// 112 = 0x70
    NSObject<OS_os_transaction> *_transaction;	// 120 = 0x78
    NSObject<OS_dispatch_semaphore> *_requestInitSemaphore;	// 128 = 0x80
    NSObject<OS_dispatch_semaphore> *_requestPreflightSemaphore;	// 136 = 0x88
    NSObject<OS_dispatch_semaphore> *_requestKeychainSemaphore;	// 144 = 0x90
    NSObject<OS_dispatch_semaphore> *_requestBackupSemaphore;	// 152 = 0x98
    NSObject<OS_dispatch_semaphore> *_connectSemaphore;	// 160 = 0xa0
    NSObject<OS_dispatch_source> *_disconnectTimer;	// 168 = 0xa8
    MBPeerTransferDrive *_transferDrive;	// 176 = 0xb0
    MBDeviceTransferLocalDrive *_transferLocalDrive;	// 184 = 0xb8
    MBDeviceTransferProgressModel *_progressModel;	// 192 = 0xc0
    MBDeviceLockAssertion *_deviceLockAssertion;	// 200 = 0xc8
    MBPowerAssertion *_powerAssertion;	// 208 = 0xd0
    RPFileTransferSession *_fileTransferSession;	// 216 = 0xd8
    MBPeerInitResponse *_peerInitResponse;	// 224 = 0xe0
    MBDeviceTransferPreflight *_peerPreflightInfo;	// 232 = 0xe8
    MBPeerKeychainTransferResponse *_peerKeychainTransferResponse;	// 240 = 0xf0
    MBDeviceTransferKeychain *_peerKeychainInfo;	// 248 = 0xf8
    NSError *_completionError;	// 256 = 0x100
    NSDate *_preflightStartDate;	// 264 = 0x108
    unsigned long long _preflightDuration;	// 272 = 0x110
    NSDate *_fileTransferStartDate;	// 280 = 0x118
    NSDate *_fileTransferEndDate;	// 288 = 0x120
    NSDate *_restoreStartDate;	// 296 = 0x128
    NSObject<OS_dispatch_group> *_progressGroup;	// 304 = 0x130
    unsigned long long _lastRestoreProgressPercentage;	// 312 = 0x138
}

- (void).cxx_destruct;	// IMP=0x00000001000be3d8
@property(nonatomic) unsigned long long lastRestoreProgressPercentage; // @synthesize lastRestoreProgressPercentage=_lastRestoreProgressPercentage;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *progressGroup; // @synthesize progressGroup=_progressGroup;
@property(retain) NSDate *restoreStartDate; // @synthesize restoreStartDate=_restoreStartDate;
@property(retain) NSDate *fileTransferEndDate; // @synthesize fileTransferEndDate=_fileTransferEndDate;
@property(retain) NSDate *fileTransferStartDate; // @synthesize fileTransferStartDate=_fileTransferStartDate;
@property unsigned long long preflightDuration; // @synthesize preflightDuration=_preflightDuration;
@property(retain) NSDate *preflightStartDate; // @synthesize preflightStartDate=_preflightStartDate;
@property(retain, nonatomic) NSError *completionError; // @synthesize completionError=_completionError;
@property(retain) MBDeviceTransferKeychain *peerKeychainInfo; // @synthesize peerKeychainInfo=_peerKeychainInfo;
@property(retain) MBPeerKeychainTransferResponse *peerKeychainTransferResponse; // @synthesize peerKeychainTransferResponse=_peerKeychainTransferResponse;
@property(retain) MBDeviceTransferPreflight *peerPreflightInfo; // @synthesize peerPreflightInfo=_peerPreflightInfo;
@property(retain) MBPeerInitResponse *peerInitResponse; // @synthesize peerInitResponse=_peerInitResponse;
@property(retain, nonatomic) RPFileTransferSession *fileTransferSession; // @synthesize fileTransferSession=_fileTransferSession;
@property(retain, nonatomic) MBPowerAssertion *powerAssertion; // @synthesize powerAssertion=_powerAssertion;
@property(retain, nonatomic) MBDeviceLockAssertion *deviceLockAssertion; // @synthesize deviceLockAssertion=_deviceLockAssertion;
@property(readonly) MBDeviceTransferProgressModel *progressModel; // @synthesize progressModel=_progressModel;
@property(readonly) MBDeviceTransferLocalDrive *transferLocalDrive; // @synthesize transferLocalDrive=_transferLocalDrive;
@property(readonly) MBPeerTransferDrive *transferDrive; // @synthesize transferDrive=_transferDrive;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *disconnectTimer; // @synthesize disconnectTimer=_disconnectTimer;
@property(retain) NSObject<OS_dispatch_semaphore> *connectSemaphore; // @synthesize connectSemaphore=_connectSemaphore;
@property(retain) NSObject<OS_dispatch_semaphore> *requestBackupSemaphore; // @synthesize requestBackupSemaphore=_requestBackupSemaphore;
@property(retain) NSObject<OS_dispatch_semaphore> *requestKeychainSemaphore; // @synthesize requestKeychainSemaphore=_requestKeychainSemaphore;
@property(retain) NSObject<OS_dispatch_semaphore> *requestPreflightSemaphore; // @synthesize requestPreflightSemaphore=_requestPreflightSemaphore;
@property(retain) NSObject<OS_dispatch_semaphore> *requestInitSemaphore; // @synthesize requestInitSemaphore=_requestInitSemaphore;
@property(retain, nonatomic) NSObject<OS_os_transaction> *transaction; // @synthesize transaction=_transaction;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *sessionQueue; // @synthesize sessionQueue=_sessionQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) __weak id <MBServiceManagerDeviceTransferDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MBConnection *connection; // @synthesize connection=_connection;
- (void)progressUpdatedWithPercentage:(double)arg1 size:(unsigned long long)arg2;	// IMP=0x00000001000bdfac
- (void)updatedTotalProgress:(id)arg1;	// IMP=0x00000001000bde3c
- (void)_sendRestoreProgressMessageWithPercentage:(unsigned long long)arg1;	// IMP=0x00000001000bd7ac
- (void)_sendDoneMessageWithError:(id)arg1;	// IMP=0x00000001000bd2a8
- (id)_restoreEngineWithSourceInfo:(id)arg1;	// IMP=0x00000001000bd09c
- (_Bool)_restoreWithSourceInfo:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000bcd1c
- (void)_saveDeviceTransferInfo;	// IMP=0x00000001000bc820
- (_Bool)_requestBackupWithSourceInfo:(id)arg1 preflightInfo:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000bbfd0
- (_Bool)_restoreKeychainWithKeychainTransferResponse:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000bb918
- (id)_requestKeychainWithSourceInfo:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000bb340
- (id)_requestPreflightWithSourceInfo:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000bac58
- (id)_requestInitWithError:(id *)arg1;	// IMP=0x00000001000ba378
- (_Bool)_handleTimeout:(_Bool)arg1 error:(id *)arg2;	// IMP=0x00000001000ba2d8
- (void)resume;	// IMP=0x00000001000ba2d4
- (void)start;	// IMP=0x00000001000ba128
- (void)_start;	// IMP=0x00000001000b9940
- (void)startDataTransferWithPreflightInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b8eec
- (void)startKeychainDataImportWithKeychainInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b863c
- (void)startKeychainDataTransferWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b7e4c
- (void)startKeychainTransferWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b76d8
- (void)startPreflightWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b6a08
- (_Bool)_checkFreeDiskSpace:(unsigned long long)arg1 preflightInfo:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000b6870
- (void)_enableInfraWiFi;	// IMP=0x00000001000b6734
- (void)_disableInfraWiFi;	// IMP=0x00000001000b65f8
- (_Bool)_setUpFileTransferSessionWithError:(id *)arg1;	// IMP=0x00000001000b5d24
- (void)_handleFileTransferSessionProgress:(id)arg1;	// IMP=0x00000001000b5a70
- (void)_stopTrackingPeerConnectionStatus;	// IMP=0x00000001000b595c
- (void)_startTrackingPeerConnectionStatus;	// IMP=0x00000001000b5848
- (_Bool)_waitForControlConnectionWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b56e0
- (void)_signalControlConnectionStarted;	// IMP=0x00000001000b56a0
- (void)_cancelDisconnectTimer;	// IMP=0x00000001000b55a0
- (void)_startDisconnectTimer;	// IMP=0x00000001000b52b8
- (id)_perform:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b51f0
- (void)cancel;	// IMP=0x00000001000b4dcc
@property(readonly, nonatomic) _Bool isFinished;
@property(readonly, nonatomic) _Bool isCanceled;
- (_Bool)_handleCompletionWithError:(id *)arg1;	// IMP=0x00000001000b4c58
- (void)_finishWithError:(id)arg1;	// IMP=0x00000001000b4288
- (int)engineType;	// IMP=0x00000001000b4280
- (void)dealloc;	// IMP=0x00000001000b4214
- (id)initWithSessionInfo:(id)arg1;	// IMP=0x00000001000b3c24

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

