//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC16DaemoniOSLibrary16SDB332SetupAgent.h"

#import "SDB332AgentProtocol-Protocol.h"

@class NSString, NSXPCInterface;

@interface _TtC16DaemoniOSLibrary16SDB332SetupAgent (DaemoniOSLibrary1) <SDB332AgentProtocol>
- (void)connectionInvalidated:(id)arg1;	// IMP=0x00000001002b4800
- (void)connectionEstablished:(id)arg1;	// IMP=0x00000001002b43e4
- (_Bool)shouldAcceptNewConnection:(id)arg1;	// IMP=0x00000001002b3f6c
@property(nonatomic, readonly) NSXPCInterface *remoteObjectInterface;
@property(nonatomic, readonly) NSXPCInterface *exportedInterface;
@property(nonatomic, readonly) NSString *machServiceName;
- (void)pairTapped;	// IMP=0x00000001002b3ebc
- (void)enableBluetoothTapped;	// IMP=0x00000001002b3d88
@end

