//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@interface SDUnlockLockStateUpdated : PBCodable <NSCopying>
{
    unsigned int _version;	// 8 = 0x8
    _Bool _unlocked;	// 12 = 0xc
    struct {
        unsigned int version:1;
        unsigned int unlocked:1;
    } _has;	// 16 = 0x10
}

@property(nonatomic) _Bool unlocked; // @synthesize unlocked=_unlocked;
@property(nonatomic) unsigned int version; // @synthesize version=_version;
- (void)mergeFrom:(id)arg1;	// IMP=0x00000001000f6ec4
- (unsigned long long)hash;	// IMP=0x00000001000f6e70
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000f6d9c
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000f6d0c
- (void)copyTo:(id)arg1;	// IMP=0x00000001000f6c98
- (void)writeTo:(id)arg1;	// IMP=0x00000001000f6c1c
- (_Bool)readFrom:(id)arg1;	// IMP=0x00000001000f6c14
- (id)dictionaryRepresentation;	// IMP=0x00000001000f682c
- (id)description;	// IMP=0x00000001000f6778
@property(nonatomic) _Bool hasUnlocked;
@property(nonatomic) _Bool hasVersion;

@end

