//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CBWindow.h"

@interface CBSceneWindow : CBWindow
{
}

- (id)_topViewController;	// IMP=0x0000000100002764
- (void)viewControllerDidDismiss;	// IMP=0x00000001000026e0
- (void)dismissViewControllerAnimated:(_Bool)arg1;	// IMP=0x0000000100002534
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010000249c

@end

