//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface AssetExportController : NSObject
{
    _Bool _deleteFragmentsWhenFinished;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_completionQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010000664c
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *completionQueue; // @synthesize completionQueue=_completionQueue;
@property(nonatomic) _Bool deleteFragmentsWhenFinished; // @synthesize deleteFragmentsWhenFinished=_deleteFragmentsWhenFinished;
- (void)finalizeAssetWithComposition:(id)arg1 cacheWaveform:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x0000000100006238
- (id)init;	// IMP=0x00000001000061e0

@end

