//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CSEventMonitor.h"

@interface CSNetworkAvailabilityMonitor : CSEventMonitor
{
    int _notifyToken;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x0000000100110fec
- (void)_notifyObserver:(id)arg1 withNetworkAvailability:(_Bool)arg2;	// IMP=0x00000001001114c0
- (void)_didReceivedNetworkAvailabilityChangedNotification:(_Bool)arg1;	// IMP=0x0000000100111448
- (void)_availabilityChanged;	// IMP=0x0000000100111388
- (void)_stopMonitoring;	// IMP=0x00000001001112b4
- (void)_startMonitoringWithQueue:(id)arg1;	// IMP=0x0000000100111118
- (_Bool)isAvailable;	// IMP=0x00000001001110a0
- (id)init;	// IMP=0x0000000100111058

@end

