//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol CSVoiceTriggerXPCConnectionDelegate, OS_dispatch_queue, OS_xpc_object;

@interface CSVoiceTriggerXPCConnection : NSObject
{
    id <CSVoiceTriggerXPCConnectionDelegate> _delegate;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NSObject<OS_xpc_object> *_connection;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000fb31c
@property(retain, nonatomic) NSObject<OS_xpc_object> *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <CSVoiceTriggerXPCConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_handleServiceConnectionLostIfNeeded;	// IMP=0x00000001000fb2cc
- (void)_handleEnableVoiceTriggerWithSiriAssertionRequest:(id)arg1;	// IMP=0x00000001000fb1f0
- (void)_handleVoiceTriggeredSiriSessionCancelled;	// IMP=0x00000001000fb118
- (void)_handlePhraseSpotterBypassRequest:(id)arg1;	// IMP=0x00000001000fafe0
- (void)_handleVoiceTriggerXPCServiceMessage:(id)arg1 client:(id)arg2;	// IMP=0x00000001000faec0
- (void)_sendReply:(id)arg1 client:(id)arg2 result:(_Bool)arg3 error:(id)arg4;	// IMP=0x00000001000fae40
- (void)_handleClientError:(id)arg1 client:(id)arg2;	// IMP=0x00000001000fac48
- (void)_handleClientMessage:(id)arg1 client:(id)arg2;	// IMP=0x00000001000fab64
- (void)_handleClientEvent:(id)arg1;	// IMP=0x00000001000faa78
- (void)activateConnection;	// IMP=0x00000001000fa968
- (id)initWithConnection:(id)arg1;	// IMP=0x00000001000fa898

@end

