//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CSVoiceTriggerXPCClientDelegate-Protocol.h"

@class CSVoiceTriggerXPCClient, NSMutableSet, NSString;
@protocol CSVoiceTriggerXPCServiceDelegate, OS_dispatch_queue;

@interface CSVoiceTriggerXPCService : NSObject <CSVoiceTriggerXPCClientDelegate>
{
    _Bool _isPhraseSpotterBypassed;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    id <CSVoiceTriggerXPCServiceDelegate> _delegate;	// 24 = 0x18
    NSMutableSet *_activationAssertions;	// 32 = 0x20
    CSVoiceTriggerXPCClient *_xpcClient;	// 40 = 0x28
}

+ (id)sharedServiceForCoreSpeechDaemon;	// IMP=0x0000000100085108
+ (id)sharedService;	// IMP=0x000000010008509c
- (void).cxx_destruct;	// IMP=0x0000000100086714
@property(retain, nonatomic) CSVoiceTriggerXPCClient *xpcClient; // @synthesize xpcClient=_xpcClient;
@property(nonatomic) _Bool isPhraseSpotterBypassed; // @synthesize isPhraseSpotterBypassed=_isPhraseSpotterBypassed;
@property(retain, nonatomic) NSMutableSet *activationAssertions; // @synthesize activationAssertions=_activationAssertions;
@property(nonatomic) __weak id <CSVoiceTriggerXPCServiceDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void)_teardownXPCClientIfNeeded;	// IMP=0x0000000100086594
- (void)voiceTriggerXPCClient:(id)arg1 didDisconnect:(_Bool)arg2;	// IMP=0x0000000100086484
- (id)_createXPCClientConnectionIfNeeded;	// IMP=0x00000001000862ec
- (void)notifyServiceConnectionLostForCoreSpeechDaemon;	// IMP=0x00000001000860e4
- (void)notifyVoiceTriggeredSiriSessionCancelledForCoreSpeechDaemon;	// IMP=0x0000000100086040
- (void)notifyVoiceTriggeredSiriSessionCancelled;	// IMP=0x0000000100085fa4
- (void)setPhraseSpotterBypassingForCoreSpeechDaemon:(_Bool)arg1 timeout:(double)arg2;	// IMP=0x0000000100085a78
- (void)setPhraseSpotterBypassing:(_Bool)arg1 timeout:(double)arg2;	// IMP=0x00000001000859c8
- (void)enableVoiceTriggerForCoreSpeechDaemon:(_Bool)arg1 withAssertion:(id)arg2 timestamp:(double)arg3;	// IMP=0x0000000100085418
- (void)enableVoiceTrigger:(_Bool)arg1 withAssertion:(id)arg2;	// IMP=0x00000001000852ec
- (id)init;	// IMP=0x00000001000851c4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

