//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDSDRegistrationControl-Protocol.h"

@class NSString;

@interface IDSDRegistrationControl : NSObject <IDSDRegistrationControl>
{
}

+ (id)sharedInstance;	// IMP=0x000000010016083c
- (_Bool)_setKeychainData:(id)arg1 withServiceName:(id)arg2 withAccountKey:(id)arg3 withIDSRegistrationAccesssGroup:(id)arg4 error:(int)arg5;	// IMP=0x0000000100161808
- (long long)registrationStateForRegistrationType:(long long)arg1 error:(id *)arg2;	// IMP=0x0000000100161114
- (_Bool)updateRegistrationType:(long long)arg1 toState:(long long)arg2 error:(id *)arg3;	// IMP=0x0000000100160938

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

