//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IDSPipelineParameter-Protocol.h"

@class IDSPeerMessage, NSArray, NSDictionary, NSString;

@protocol IDSMessageFactoryParameter <IDSPipelineParameter>
- (_Bool)setUsedMMCS:(_Bool)arg1;
- (void)setAggregatableMessages:(NSArray *)arg1;
- (NSDictionary *)endpointsToEncryptedData;
- (IDSPeerMessage *)messageToSend;
- (unsigned long long)maxSize;
- (NSString *)service;
- (NSString *)fromID;
- (long long)encryptionType;
- (_Bool)wantsCertifiedDelivery;
- (_Bool)wantsDeliveryStatus;
- (_Bool)forceAttachmentMessage;
- (NSString *)guid;
@end

