//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDSNGMSwizzler : NSObject
{
}

+ (id)lastPrKey;	// IMP=0x0000000100110f78
+ (void)uninstallMethods;	// IMP=0x0000000100110ed4
+ (void)installMethods;	// IMP=0x0000000100110c58

@end

