//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "IDSProfileMessage.h"

#import "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface IDSProfileValidateInvitationContext : IDSProfileMessage <NSCopying>
{
    NSString *_basePhoneNumber;	// 232 = 0xe8
    NSString *_regionID;	// 240 = 0xf0
    NSString *_responseBasePhoneNumber;	// 248 = 0xf8
    NSString *_responseRegionID;	// 256 = 0x100
    NSDictionary *_responseExtraInfo;	// 264 = 0x108
}

- (void).cxx_destruct;	// IMP=0x00000001001bed14
@property(copy) NSDictionary *responseExtraInfo; // @synthesize responseExtraInfo=_responseExtraInfo;
@property(copy) NSString *responseRegionID; // @synthesize responseRegionID=_responseRegionID;
@property(copy) NSString *responseBasePhoneNumber; // @synthesize responseBasePhoneNumber=_responseBasePhoneNumber;
@property(copy) NSString *regionID; // @synthesize regionID=_regionID;
@property(copy) NSString *basePhoneNumber; // @synthesize basePhoneNumber=_basePhoneNumber;
- (void)handleResponseDictionary:(id)arg1;	// IMP=0x00000001001be8bc
- (double)anisetteHeadersTimeout;	// IMP=0x00000001001be8a4
- (id)messageBody;	// IMP=0x00000001001be72c
- (id)requiredKeys;	// IMP=0x00000001001be6a0
- (id)bagKey;	// IMP=0x00000001001be684
- (int)maxTimeoutRetries;	// IMP=0x00000001001be66c
- (_Bool)wantsExtraTimeoutRetry;	// IMP=0x00000001001be650
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001001be43c
- (id)init;	// IMP=0x00000001001be37c

@end

