//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class IDSUTunDeliveryController, NSString;

@protocol IDSUTunDeliveryControllerConnectivityDelegate <NSObject>

@optional
- (void)deliveryController:(IDSUTunDeliveryController *)arg1 foundNearbyIPsecCapableDeviceWithUniqueID:(NSString *)arg2;
- (void)deliveryController:(IDSUTunDeliveryController *)arg1 uniqueID:(NSString *)arg2 isCloudConnected:(_Bool)arg3;
- (void)deliveryController:(IDSUTunDeliveryController *)arg1 uniqueID:(NSString *)arg2 isConnected:(_Bool)arg3;
- (void)deliveryController:(IDSUTunDeliveryController *)arg1 uniqueID:(NSString *)arg2 isNearby:(_Bool)arg3;
@end

