//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, PKPass;

@interface PDGetPassResult : NSObject
{
    PKPass *_pass;	// 8 = 0x8
    NSString *_lastModified;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001001208dc
@property(retain, nonatomic) NSString *lastModified; // @synthesize lastModified=_lastModified;
@property(retain, nonatomic) PKPass *pass; // @synthesize pass=_pass;

@end

