//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "PDNetworkConnectionTask.h"

@class NSString, PDWebService;

@interface PDWebServiceConnectionTask : PDNetworkConnectionTask
{
    PDWebService *_webService;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010011c66c
- (void).cxx_destruct;	// IMP=0x000000010011d35c
@property(readonly, nonatomic) PDWebService *webService; // @synthesize webService=_webService;
- (id)teamIdentifier;	// IMP=0x000000010011d2f8
@property(readonly, nonatomic) NSString *passTypeIdentifier;
- (id)bodyDictionary;	// IMP=0x000000010011d29c
- (id)headerFields;	// IMP=0x000000010011d294
- (id)queryFields;	// IMP=0x000000010011d28c
- (id)endpointComponents;	// IMP=0x000000010011d284
- (id)method;	// IMP=0x000000010011d27c
- (void)reportMalformedResponseError:(id)arg1;	// IMP=0x000000010011d228
- (void)reportNSURLConnectionError:(id)arg1;	// IMP=0x000000010011d1d4
- (void)reportUnexpectedResponseCode:(long long)arg1;	// IMP=0x000000010011d170
- (void)reportAuthenticationFailure;	// IMP=0x000000010011d118
- (id)request;	// IMP=0x000000010011c7a8
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010011c720
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010011c674
- (id)initWithWebService:(id)arg1;	// IMP=0x000000010011c5ec

@end

