//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SQLiteEntity.h"

@interface Rule : SQLiteEntity
{
}

+ (id)databaseTable;	// IMP=0x000000010006c448
+ (id)_propertySettersForAccount;	// IMP=0x000000010006c364
+ (id)_predicateForRuleIdentifier:(id)arg1;	// IMP=0x000000010006c344
+ (void)deleteAllRulesInDatabase:(id)arg1;	// IMP=0x000000010006c070
+ (void)deleteRulesNotIncludingIdentifiers:(id)arg1 inDatabase:(id)arg2;	// IMP=0x000000010006bfa4
+ (void)deleteRuleWithIdentifier:(id)arg1 inDatabase:(id)arg2;	// IMP=0x000000010006bef0
+ (id)insertOrUpdateRule:(id)arg1 inDatabase:(id)arg2;	// IMP=0x000000010006bce8
+ (id)ruleWithIdentifier:(id)arg1 inDatabase:(id)arg2;	// IMP=0x000000010006bc44
+ (id)rulesInDatabase:(id)arg1;	// IMP=0x000000010006ba30
- (void)updateWithRule:(id)arg1;	// IMP=0x000000010006c258
- (id)rule;	// IMP=0x000000010006c110
- (id)initWithRule:(id)arg1 inDatabase:(id)arg2;	// IMP=0x000000010006bdc8

@end

