//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface ADAuthenticationManager : NSObject
{
    NSObject<OS_dispatch_queue> *_pendingChallengesQueue;	// 8 = 0x8
}

+ (id)sharedInstance;	// IMP=0x000000010001a11c
- (void).cxx_destruct;	// IMP=0x000000010001a4c0
- (void)promptForPasswordWithChallenge:(id)arg1 username:(id)arg2;	// IMP=0x000000010001a2cc
- (void)handleAuthenticationWithChallenge:(id)arg1 username:(id)arg2;	// IMP=0x000000010001a1b8
- (id)init;	// IMP=0x000000010001a090

@end

