//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_NFContactlessSession.h"

#import "NFContactlessUICCSessionInterface-Protocol.h"

@interface _NFContactlessUICCSession : _NFContactlessSession <NFContactlessUICCSessionInterface>
{
}

+ (id)validateEntitlements:(id)arg1;	// IMP=0x00000001000a65c8
- (id)preloadApplets;	// IMP=0x00000001000a67b4
- (unsigned long long)initialRoutingMode;	// IMP=0x00000001000a67ac

@end

