//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSHashTable;

@interface APSSystemMonitor : NSObject
{
    NSHashTable *_listeners;	// 8 = 0x8
    NSDate *_dateSystemLockLastChanged;	// 16 = 0x10
    NSDate *_dateScreenLightLastChanged;	// 24 = 0x18
    _Bool _active;	// 32 = 0x20
    _Bool _willSleep;	// 33 = 0x21
    _Bool _usesPowerNotifications;	// 34 = 0x22
    _Bool _watchesScreenLightState;	// 35 = 0x23
    _Bool _watchesSystemLockState;	// 36 = 0x24
    _Bool _systemLocked;	// 37 = 0x25
    _Bool _screenLit;	// 38 = 0x26
}

+ (id)sharedInstance;	// IMP=0x000000010008105c
- (void).cxx_destruct;	// IMP=0x0000000100081b44
@property(nonatomic) _Bool usesPowerNotifications; // @synthesize usesPowerNotifications=_usesPowerNotifications;
@property(readonly, nonatomic) _Bool isSystemLocked; // @synthesize isSystemLocked=_systemLocked;
@property(readonly, retain, nonatomic) NSDate *dateSystemLockLastChanged; // @synthesize dateSystemLockLastChanged=_dateSystemLockLastChanged;
@property(readonly, retain, nonatomic) NSDate *dateScreenLightLastChanged; // @synthesize dateScreenLightLastChanged=_dateScreenLightLastChanged;
@property(readonly, nonatomic) _Bool isScreenLit; // @synthesize isScreenLit=_screenLit;
@property(nonatomic, setter=setActive:) _Bool isActive; // @synthesize isActive=_active;
@property(nonatomic) _Bool watchesSystemLockState; // @synthesize watchesSystemLockState=_watchesSystemLockState;
@property(readonly, nonatomic) _Bool systemIsSleeping; // @synthesize systemIsSleeping=_willSleep;
@property(nonatomic) _Bool watchesScreenLightState; // @synthesize watchesScreenLightState=_watchesScreenLightState;
- (void)removeListener:(id)arg1;	// IMP=0x0000000100081a7c
- (void)addListener:(id)arg1;	// IMP=0x00000001000819ec
- (void)_setSystemLockState:(_Bool)arg1;	// IMP=0x0000000100081868
- (void)_setSystemScreenState:(_Bool)arg1;	// IMP=0x00000001000816e4
- (void)_systemWillSleep;	// IMP=0x0000000100081480
- (void)_systemDidWake;	// IMP=0x0000000100081468
- (void)_deliverNotificationSelector:(SEL)arg1;	// IMP=0x00000001000813a8
- (void)dealloc;	// IMP=0x000000010008113c
- (id)init;	// IMP=0x00000001000810c8

@end

