//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AKUserInformation, NSArray, NSDictionary;

@interface AKAppleIDUserInformationResponse : NSObject
{
    NSArray *_allAccountNames;	// 8 = 0x8
    AKUserInformation *_userInformationRepresentation;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100003df0
@property(copy, nonatomic) AKUserInformation *userInformationRepresentation; // @synthesize userInformationRepresentation=_userInformationRepresentation;
@property(readonly, copy) NSDictionary *dictionaryRepresentation;
@property(readonly, copy) NSArray *allAccountNames; // @synthesize allAccountNames=_allAccountNames;
- (id)initWithResponseBody:(id)arg1;	// IMP=0x00000001000036b0

@end

