//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_AKMessage.h"

@class NSObject;

@interface AKCommandMessage : _AKMessage
{
}

- (id)description;	// IMP=0x000000010001a788
@property(copy, nonatomic) NSObject *argument;
@property(nonatomic) unsigned long long command;
- (id)init;	// IMP=0x000000010001a614

@end

