//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class NSString;
@protocol NDAnalyticsService;

@interface NDAnalyticsServiceListenerDelegate : NSObject <NSXPCListenerDelegate>
{
    id <NDAnalyticsService> _service;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100006d74
@property(retain, nonatomic) id <NDAnalyticsService> service; // @synthesize service=_service;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000100006b14
- (id)initWithService:(id)arg1;	// IMP=0x0000000100006a7c
- (id)init;	// IMP=0x00000001000069c4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

