//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ADService.h"

@class HMClientConnection, NSObject;
@protocol OS_dispatch_queue;

@interface ADHomeKitService : ADService
{
    HMClientConnection *_hmConnection;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_targetQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001001d0554
- (id)_hmConnection;	// IMP=0x00000001001d04e0
- (void)handleCommand:(id)arg1 forDomain:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00000001001d01c8
- (void)resetExternalResources;	// IMP=0x00000001001d0150
- (void)preheatDomain:(id)arg1;	// IMP=0x00000001001d00cc
- (_Bool)implementsCommand:(id)arg1 forDomain:(id)arg2;	// IMP=0x00000001001d00c4
- (id)commandsForDomain:(id)arg1;	// IMP=0x00000001001d0024
- (id)domains;	// IMP=0x00000001001cffb4
- (id)handle;	// IMP=0x00000001001cffb0
- (id)init;	// IMP=0x00000001001cff0c

@end

