//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CSOpportuneSpeakListenerDelegate-Protocol.h"

@class ADOpportuneSpeakingMovingAverageBuffer, ADOpportuneSpeakingStateManager, AFWatchdogTimer, CSOpportuneSpeakListener, NSString, NSUUID;
@protocol OS_dispatch_queue;

@interface ADOpportuneSpeakingModuleEdgeDetector : NSObject <CSOpportuneSpeakListenerDelegate>
{
    NSUUID *_uuid;	// 8 = 0x8
    _Bool _currentHasAccel;	// 16 = 0x10
    _Bool _currentHasVAD;	// 17 = 0x11
    ADOpportuneSpeakingMovingAverageBuffer *_avbuffer;	// 24 = 0x18
    ADOpportuneSpeakingStateManager *_stateManager;	// 32 = 0x20
    CSOpportuneSpeakListener *_listener;	// 40 = 0x28
    _Bool _inVoice;	// 48 = 0x30
    int _currentFrameCount;	// 52 = 0x34
    int _currentPausedFrameCount;	// 56 = 0x38
    int _currentVoiceFrameCount;	// 60 = 0x3c
    int _thresholdFrameCount;	// 64 = 0x40
    CDUnknownBlockType _successCompletionBlock;	// 72 = 0x48
    CDUnknownBlockType _failCompletionBlock;	// 80 = 0x50
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 88 = 0x58
    unsigned long long _mode;	// 96 = 0x60
    _Bool _isStopping;	// 104 = 0x68
    AFWatchdogTimer *_timer;	// 112 = 0x70
    NSString *_deviceID;	// 120 = 0x78
    float _maxDelay;	// 128 = 0x80
    _Bool _shouldStopListeningOnDetection;	// 132 = 0x84
    _Bool _isListening;	// 133 = 0x85
}

- (void).cxx_destruct;	// IMP=0x00000001001e69ec
@property(readonly, nonatomic) _Bool isListening; // @synthesize isListening=_isListening;
- (void)opportuneSpeakListener:(id)arg1 didStopUnexpectly:(_Bool)arg2;	// IMP=0x00000001001e6844
- (void)opportuneSpeakListener:(id)arg1 hasVADAvailable:(_Bool)arg2;	// IMP=0x00000001001e6724
- (void)opportuneSpeakListener:(id)arg1 hasRemoteVADAvailable:(_Bool)arg2;	// IMP=0x00000001001e65d0
- (id)modeDescriptionFor:(unsigned long long)arg1;	// IMP=0x00000001001e65b4
- (void)_didStopListening;	// IMP=0x00000001001e659c
- (void)_didStartListening;	// IMP=0x00000001001e6584
- (void)_restartAndExtendListening;	// IMP=0x00000001001e60b4
- (void)stopListeningWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001001e5fdc
- (void)_stopListeningWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001001e5d3c
- (void)_thresholdDetected;	// IMP=0x00000001001e5ba0
- (void)_handleFrame:(unsigned long long)arg1;	// IMP=0x00000001001e5858
- (void)waitOnDeviceID:(id)arg1 forVoice:(float)arg2 maxDelay:(float)arg3 stopOnDetection:(_Bool)arg4 executeOnSuccess:(CDUnknownBlockType)arg5 onFail:(CDUnknownBlockType)arg6;	// IMP=0x00000001001e543c
- (void)waitOnDeviceID:(id)arg1 forPause:(float)arg2 maxDelay:(float)arg3 stopOnDetection:(_Bool)arg4 executeOnSuccess:(CDUnknownBlockType)arg5 onFail:(CDUnknownBlockType)arg6;	// IMP=0x00000001001e5020
- (void)_scheduleTimerForMaxDelay:(float)arg1;	// IMP=0x00000001001e4e94
- (void)_resetStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001001e4e20
- (void)dealloc;	// IMP=0x00000001001e4dd0
- (id)initWithQueue:(id)arg1 stateManager:(id)arg2;	// IMP=0x00000001001e4c98

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

