//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SAObjects/SASettingGetBool.h>

@interface SASettingGetBool (ADSettingsTransformer)
- (id)_ad_aceSettingsResponseCommandRepresentationForSiriResponse:(id)arg1;	// IMP=0x0000000100202000
- (void)_ad_getSettingsRequestForHandler:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100201ed4
- (long long)_ad_settingType;	// IMP=0x0000000100201ecc
@end

