//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSInputStream.h>

#import "NSStreamDelegate-Protocol.h"

@class NSString;

@interface W5SpeedTestUploadStream : NSInputStream <NSStreamDelegate>
{
    unsigned long long _payloadSize;	// 8 = 0x8
    unsigned long long _bufferSize;	// 16 = 0x10
    unsigned long long _bytesSent;	// 24 = 0x18
    unsigned long long _status;	// 32 = 0x20
}

+ (id)__randomDataOfSize:(unsigned long long)arg1;	// IMP=0x0000000100006160
@property(readonly, nonatomic) unsigned long long bytesSent; // @synthesize bytesSent=_bytesSent;
@property(readonly, nonatomic) unsigned long long bufferSize; // @synthesize bufferSize=_bufferSize;
@property(readonly, nonatomic) unsigned long long payloadSize; // @synthesize payloadSize=_payloadSize;
- (_Bool)_setCFClientFlags:(unsigned long long)arg1 callback:(CDUnknownFunctionPointerType)arg2 context:(CDStruct_e097db04 *)arg3;	// IMP=0x00000001000062ec
- (void)_unscheduleFromCFRunLoop:(struct __CFRunLoop *)arg1 forMode:(struct __CFString *)arg2;	// IMP=0x00000001000062e8
- (void)_scheduleInCFRunLoop:(struct __CFRunLoop *)arg1 forMode:(struct __CFString *)arg2;	// IMP=0x00000001000062e4
- (void)removeFromRunLoop:(id)arg1 forMode:(id)arg2;	// IMP=0x00000001000062e0
- (void)scheduleInRunLoop:(id)arg1 forMode:(id)arg2;	// IMP=0x00000001000062dc
- (void)close;	// IMP=0x00000001000062c8
- (void)open;	// IMP=0x00000001000062b4
- (_Bool)hasBytesAvailable;	// IMP=0x00000001000062ac
- (_Bool)getBuffer:(char **)arg1 length:(unsigned long long *)arg2;	// IMP=0x00000001000062a4
- (long long)read:(char *)arg1 maxLength:(unsigned long long)arg2;	// IMP=0x00000001000061ec
- (void)setDelegate:(id)arg1;	// IMP=0x000000010000615c
- (unsigned long long)streamStatus;	// IMP=0x000000010000614c
- (id)initWithPayloadSize:(unsigned long long)arg1 bufferSize:(unsigned long long)arg2;	// IMP=0x00000001000060c0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

