//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSNumber, NSString;

@interface _StoreStatus : NSObject
{
    NSString *_persistencePath;	// 8 = 0x8
    NSMutableDictionary *_status;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100054ce4
@property(retain, nonatomic) NSNumber *seqId;
@property(nonatomic) _Bool needsResetSync;
- (id)initWithPersistencePath:(id)arg1;	// IMP=0x00000001000548fc

@end

