//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NTKComplicationStoreServer-Protocol.h"
#import "NTKDComplicationStoreObserver-Protocol.h"

@class NSMutableArray, NSString, NSXPCConnection, NTKDComplicationStore;
@protocol OS_dispatch_queue;

@interface NTKDComplicationCollectionClient : NSObject <NTKComplicationStoreServer, NTKDComplicationStoreObserver>
{
    NSXPCConnection *_connection;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    NTKDComplicationStore *_complicationStore;	// 24 = 0x18
    NSMutableArray *_actionsEnqueuedWhileWaitingForStore;	// 32 = 0x20
    CDUnknownBlockType _invalidationHandler;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x000000010004b920
@property(copy, nonatomic) CDUnknownBlockType invalidationHandler; // @synthesize invalidationHandler=_invalidationHandler;
- (void)complicationStore:(id)arg1 didRemoveComplicationForClientIdentifier:(id)arg2 seqId:(id)arg3;	// IMP=0x000000010004b7f0
- (void)complicationStore:(id)arg1 didUpdateLocalizableSampleTemplate:(id)arg2 forClientIdentifier:(id)arg3 family:(long long)arg4 seqId:(id)arg5;	// IMP=0x000000010004b690
- (void)complicationStore:(id)arg1 loadFullCollectionWithLocalizableSampleTemplates:(id)arg2 seqId:(id)arg3;	// IMP=0x000000010004b574
- (void)removeComplicationForClientIdentifier:(id)arg1;	// IMP=0x000000010004b4cc
- (void)updateLocalizableSampleDataTemplate:(id)arg1 forClientIdentifier:(id)arg2 family:(long long)arg3;	// IMP=0x000000010004b3e0
- (void)registerForCollectionIdentifier:(id)arg1 deviceUUID:(id)arg2 withSeqId:(id)arg3;	// IMP=0x000000010004b028
- (void)_onQueue:(CDUnknownBlockType)arg1;	// IMP=0x000000010004af6c
- (void)_performOrEnqueueAction:(CDUnknownBlockType)arg1;	// IMP=0x000000010004adf8
- (void)_handleInvalidation;	// IMP=0x000000010004acd0
- (id)initWithConnection:(id)arg1;	// IMP=0x000000010004aa9c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

