//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (xpcdictConv)
+ (id)dictionaryFromXPCDictionary:(id)arg1 withDataFromKey:(const char *)arg2;	// IMP=0x000000010006514c
+ (id)dictionaryFromJsonData:(id)arg1;	// IMP=0x0000000100064fd4
+ (id)dictionaryWithXPCDictionary:(id)arg1;	// IMP=0x0000000100064b18
- (id)convertToNSData;	// IMP=0x0000000100065360
- (_Bool)saveAsDataInXPCDictionary:(id)arg1 forKey:(const char *)arg2;	// IMP=0x00000001000652a4
- (id)createXPCDictionary;	// IMP=0x0000000100064fcc
- (id)initWithXPCDictionary:(id)arg1;	// IMP=0x0000000100064b6c
@end

