//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_source;

@interface SESTimer : NSObject
{
    NSObject<OS_dispatch_source> *_src;	// 8 = 0x8
    _Bool _started;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010002e980
@property(readonly, nonatomic) _Bool started; // @synthesize started=_started;
- (void)stopTimer;	// IMP=0x000000010002e938
- (void)startTimer:(double)arg1 leeway:(double)arg2;	// IMP=0x000000010002e8a0
- (void)startTimer:(double)arg1;	// IMP=0x000000010002e870
- (void)dealloc;	// IMP=0x000000010002e828
- (id)initOnQueue:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x000000010002e6e4

@end

