//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NESMVPNSessionState.h"

@interface NESMVPNSessionStateReasserting : NESMVPNSessionState
{
    _Bool _setConfigurationInProgress;	// 40 = 0x28
}

@property _Bool setConfigurationInProgress; // @synthesize setConfigurationInProgress=_setConfigurationInProgress;
- (void)handleSetConfigurationResult:(_Bool)arg1;	// IMP=0x000000010005bab4
- (_Bool)handleSetConfiguration;	// IMP=0x000000010005ba54
- (void)handleUserLogout;	// IMP=0x000000010005ba20
- (void)handleUserSwitch;	// IMP=0x000000010005b9ec
- (void)handleWakeup;	// IMP=0x000000010005b8fc
- (_Bool)handleSleep;	// IMP=0x000000010005b6ec
- (void)handlePluginStatusDidChangeToConnected:(id)arg1;	// IMP=0x000000010005b664
- (void)handleTimeout;	// IMP=0x000000010005b5b4
- (void)handleInterfaceAvailable:(id)arg1 changed:(_Bool)arg2;	// IMP=0x000000010005b308
- (void)handleInterfaceUnavailable:(id)arg1;	// IMP=0x000000010005b1f4
- (void)enterWithSession:(id)arg1;	// IMP=0x000000010005b15c
- (id)init;	// IMP=0x000000010005b120

@end

