//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <TelephonyUI/TPAlert.h>

@interface PHAirplaneEmergencyCallAlert : TPAlert
{
    CDUnknownBlockType _dialAction;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000777cc
@property(copy, nonatomic) CDUnknownBlockType dialAction; // @synthesize dialAction=_dialAction;
- (void)otherResponse;	// IMP=0x0000000100077730
- (void)defaultResponse;	// IMP=0x00000001000776b0
- (void)alternateResponse;	// IMP=0x0000000100077614
- (id)defaultButtonTitle;	// IMP=0x00000001000775a0
- (id)otherButtonTitle;	// IMP=0x0000000100077504
- (id)alternateButtonTitle;	// IMP=0x0000000100077490
- (id)message;	// IMP=0x00000001000773f4
- (id)title;	// IMP=0x0000000100077358
- (id)initWithDialAction:(CDUnknownBlockType)arg1;	// IMP=0x00000001000772e4

@end

