//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

#import "PHSlidingButtonDelegateProtocol-Protocol.h"

@class NSArray, NSMutableArray, NSString, PHSlidingButton, TUCallCenter, UIButton;
@protocol PHBottomBarDelegateProtocol;

@interface PHBottomBar : UIView <PHSlidingButtonDelegateProtocol>
{
    _Bool _declineAndRemindIsAvailable;	// 8 = 0x8
    _Bool _declineAndMessageIsAvailable;	// 9 = 0x9
    _Bool _enabled;	// 10 = 0xa
    _Bool _blursBackground;	// 11 = 0xb
    _Bool _usesLowerButtons;	// 12 = 0xc
    _Bool _animating;	// 13 = 0xd
    id <PHBottomBarDelegateProtocol> _delegate;	// 16 = 0x10
    long long _currentState;	// 24 = 0x18
    long long _orientation;	// 32 = 0x20
    double _bottomMargin;	// 40 = 0x28
    double _yOffsetForLoweredButtons;	// 48 = 0x30
    NSArray *_buttonLayoutConstraints;	// 56 = 0x38
    UIView *_topLayoutGuide;	// 64 = 0x40
    UIView *_mainButtonLayoutGuide;	// 72 = 0x48
    NSArray *_horizontalConstraintsForSupplementalButtons;	// 80 = 0x50
    UIButton *_supplementalTopLeftButton;	// 88 = 0x58
    UIButton *_supplementalTopRightButton;	// 96 = 0x60
    UIButton *_mainLeftButton;	// 104 = 0x68
    UIButton *_mainRightButton;	// 112 = 0x70
    UIButton *_sideButtonLeft;	// 120 = 0x78
    UIButton *_sideButtonRight;	// 128 = 0x80
    UIButton *_supplementalBottomRightButton;	// 136 = 0x88
    UIButton *_supplementalBottomLeftButton;	// 144 = 0x90
    PHSlidingButton *_slidingButton;	// 152 = 0x98
    NSMutableArray *_pendingStateBlocks;	// 160 = 0xa0
    TUCallCenter *_callCenter;	// 168 = 0xa8
}

+ (double)defaultYOffsetForBottomButtons;	// IMP=0x00000001000dd460
+ (double)defaultBottomSupplementalButtonSpacing;	// IMP=0x00000001000dd3f8
+ (double)defaultBottomMargin;	// IMP=0x00000001000dd3ec
+ (double)defaultWidth;	// IMP=0x00000001000dd380
+ (double)defaultInterButtonSpacing;	// IMP=0x00000001000dd324
+ (double)defaultSideMarginForDoubleButton;	// IMP=0x00000001000dd2b0
+ (double)defaultSideMarginForSingleButton;	// IMP=0x00000001000dd2a8
- (void).cxx_destruct;	// IMP=0x00000001000e9f94
@property(retain, nonatomic) TUCallCenter *callCenter; // @synthesize callCenter=_callCenter;
@property(readonly, copy, nonatomic) NSMutableArray *pendingStateBlocks; // @synthesize pendingStateBlocks=_pendingStateBlocks;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(retain, nonatomic) PHSlidingButton *slidingButton; // @synthesize slidingButton=_slidingButton;
@property(retain, nonatomic) UIButton *supplementalBottomLeftButton; // @synthesize supplementalBottomLeftButton=_supplementalBottomLeftButton;
@property(retain, nonatomic) UIButton *supplementalBottomRightButton; // @synthesize supplementalBottomRightButton=_supplementalBottomRightButton;
@property(retain, nonatomic) UIButton *sideButtonRight; // @synthesize sideButtonRight=_sideButtonRight;
@property(retain, nonatomic) UIButton *sideButtonLeft; // @synthesize sideButtonLeft=_sideButtonLeft;
@property(retain, nonatomic) UIButton *mainRightButton; // @synthesize mainRightButton=_mainRightButton;
@property(retain, nonatomic) UIButton *mainLeftButton; // @synthesize mainLeftButton=_mainLeftButton;
@property(retain, nonatomic) UIButton *supplementalTopRightButton; // @synthesize supplementalTopRightButton=_supplementalTopRightButton;
@property(retain, nonatomic) UIButton *supplementalTopLeftButton; // @synthesize supplementalTopLeftButton=_supplementalTopLeftButton;
@property(retain) NSArray *horizontalConstraintsForSupplementalButtons; // @synthesize horizontalConstraintsForSupplementalButtons=_horizontalConstraintsForSupplementalButtons;
@property(retain, nonatomic) UIView *mainButtonLayoutGuide; // @synthesize mainButtonLayoutGuide=_mainButtonLayoutGuide;
@property(retain, nonatomic) UIView *topLayoutGuide; // @synthesize topLayoutGuide=_topLayoutGuide;
@property(retain) NSArray *buttonLayoutConstraints; // @synthesize buttonLayoutConstraints=_buttonLayoutConstraints;
@property(nonatomic) double yOffsetForLoweredButtons; // @synthesize yOffsetForLoweredButtons=_yOffsetForLoweredButtons;
@property(nonatomic) double bottomMargin; // @synthesize bottomMargin=_bottomMargin;
@property(nonatomic) long long orientation; // @synthesize orientation=_orientation;
@property(nonatomic) long long currentState; // @synthesize currentState=_currentState;
@property(nonatomic) _Bool usesLowerButtons; // @synthesize usesLowerButtons=_usesLowerButtons;
@property(nonatomic) _Bool blursBackground; // @synthesize blursBackground=_blursBackground;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(nonatomic) _Bool declineAndMessageIsAvailable; // @synthesize declineAndMessageIsAvailable=_declineAndMessageIsAvailable;
@property(nonatomic) _Bool declineAndRemindIsAvailable; // @synthesize declineAndRemindIsAvailable=_declineAndRemindIsAvailable;
@property __weak id <PHBottomBarDelegateProtocol> delegate; // @synthesize delegate=_delegate;
- (id)nameForActionType:(long long)arg1;	// IMP=0x00000001000e9b38
- (void)_startShopDemoMode;	// IMP=0x00000001000e9ae0
- (void)animateFromIncomingCallStateToFaceTimeInCallState:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e83b0
- (void)animateFromIncomingCallStateToInCallState:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e7328
- (void)animateFromOutgoingStateToCallbackAndMessageUIToState:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e6b80
- (void)animateFromFaceTimeOutgoingStateToFaceTimeInCallState:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e67ec
- (void)animateOutSupplementalBottomLeftButtonToState:(long long)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e602c
- (void)animateInSupplementalBottomRightButton:(id)arg1 WithCompletion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000e55ec
- (void)animateFromOutgoingStateToInCallStateWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000e5080
- (void)layoutSubviews;	// IMP=0x00000001000e5020
- (_Bool)animateFromState:(long long)arg1 toState:(long long)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000e4cb4
- (void)prepareButtonsForAnimationEnd;	// IMP=0x00000001000e4b4c
- (void)prepareButtonsForAnimationBegin;	// IMP=0x00000001000e49e4
- (_Bool)shouldShowUseRTTButton;	// IMP=0x00000001000e4950
- (_Bool)shouldShowAnswerRTTButton;	// IMP=0x00000001000e48bc
- (void)refreshUseRTTButton;	// IMP=0x00000001000e477c
@property(readonly, nonatomic) UIButton *useRTTButton;
- (void)refreshEndCallButton;	// IMP=0x00000001000e45e4
- (void)refreshCustomizedActionTypeTitleForButton:(id)arg1;	// IMP=0x00000001000e43d8
- (void)refreshCustomizedActionTypeTitles;	// IMP=0x00000001000e427c
- (long long)updatedActionTypeForActionType:(long long)arg1;	// IMP=0x00000001000e4244
- (_Bool)updatedSelectedStateForActionType:(long long)arg1;	// IMP=0x00000001000e41b4
- (id)audioRouteImageWithColor:(id)arg1;	// IMP=0x00000001000e40f8
- (id)updatedSelectedImageForActionType:(long long)arg1 givenDefaultSelectedImage:(id)arg2;	// IMP=0x00000001000e405c
- (id)updatedImageForActionType:(long long)arg1 givenDefaultImage:(id)arg2;	// IMP=0x00000001000e3fc0
- (id)customTitleStringForActionType:(long long)arg1 givenDefaultTitle:(id)arg2;	// IMP=0x00000001000e3ed0
- (id)controlForActionType:(long long)arg1;	// IMP=0x00000001000e3d60
- (struct CGRect)frameForControlWithActionType:(long long)arg1;	// IMP=0x00000001000e3cd0
- (id)viewLabels;	// IMP=0x00000001000e3b40
- (void)slidingButton:(id)arg1 didSlideToProportion:(double)arg2;	// IMP=0x00000001000e3a88
- (void)didFinishSlideForSlidingButton:(id)arg1;	// IMP=0x00000001000e3a78
- (void)willFinishSlideForSlidingButton:(id)arg1;	// IMP=0x00000001000e38e4
- (void)buttonLongPressed:(id)arg1;	// IMP=0x00000001000e37f8
- (void)buttonPressed:(id)arg1;	// IMP=0x00000001000e366c
- (void)removeAllButtons;	// IMP=0x00000001000e3304
- (void)addSubview:(id)arg1;	// IMP=0x00000001000e327c
- (id)makeSlidingButtonWithType:(int)arg1;	// IMP=0x00000001000e31cc
- (id)makeCaptureButtonWithDiameter:(double)arg1;	// IMP=0x00000001000e3134
- (id)makeButtonWithType:(long long)arg1 title:(id)arg2 image:(id)arg3 color:(id)arg4 font:(id)arg5 fontColor:(id)arg6 diameter:(double)arg7;	// IMP=0x00000001000e2d24
- (id)makeButtonWithType:(long long)arg1 title:(id)arg2 image:(id)arg3 color:(id)arg4 font:(id)arg5 fontColor:(id)arg6;	// IMP=0x00000001000e2c1c
- (long long)currentBottomBarCallState;	// IMP=0x00000001000e2bc8
- (_Bool)currentCallIsMuted;	// IMP=0x00000001000e2b50
- (_Bool)shouldShowActionTypeEffects;	// IMP=0x00000001000e2ab0
- (_Bool)shouldShowActionTypePhotoCapture;	// IMP=0x00000001000e2a10
- (_Bool)shouldShowActionTypePunchOut;	// IMP=0x00000001000e2970
- (_Bool)shouldShowActionTypeSendToVoicemail;	// IMP=0x00000001000e28d0
- (_Bool)shouldShowActionTypeAudioRoute;	// IMP=0x00000001000e2830
- (_Bool)shouldShowActionTypeCameraFlip;	// IMP=0x00000001000e2790
- (id)constraintsForState:(long long)arg1;	// IMP=0x00000001000e0834
- (id)_supplementalBottomRightButtonLayoutConstraints;	// IMP=0x00000001000e0604
- (id)_supplementalBottomLeftButtonLayoutConstraints;	// IMP=0x00000001000e03d4
- (void)setCurrentState:(long long)arg1 animated:(_Bool)arg2 animationCompletionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000de5f8
- (long long)_gestureStateToCompletionState:(long long)arg1;	// IMP=0x00000001000de5e0
- (void)setAction:(long long)arg1 enabled:(_Bool)arg2;	// IMP=0x00000001000de310
- (void)setAction:(long long)arg1 selected:(_Bool)arg2;	// IMP=0x00000001000de2c8
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;	// IMP=0x00000001000de10c
- (void)updateMainButtonLayoutGuide;	// IMP=0x00000001000de004
- (void)updateTopLayoutGuide;	// IMP=0x00000001000dddfc
- (double)sideMarginForDoubleButton;	// IMP=0x00000001000ddc10
- (double)sideMarginForFaceTimeInCallButtons;	// IMP=0x00000001000ddb88
- (double)sideMarginForFaceTimeButtons;	// IMP=0x00000001000ddaf8
@property(readonly, nonatomic) struct CGSize effectiveSize;
- (struct CGSize)intrinsicContentSize;	// IMP=0x00000001000dd7b0
- (void)dealloc;	// IMP=0x00000001000dd754
- (id)init;	// IMP=0x00000001000dd738
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000dd4ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

