//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface PHNumberPadKeyCommandHandler : NSObject
{
}

- (unsigned int)numberPadCharacterForString:(id)arg1;	// IMP=0x0000000100035884
- (BOOL)characterForNumberPadCharacter:(unsigned int)arg1;	// IMP=0x00000001000357fc
- (void)handleKeyCommand:(id)arg1 receivedCharacterBlock:(CDUnknownBlockType)arg2 receivedSpecialCharacterBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000354f8
- (id)initWithViewController:(id)arg1 selector:(SEL)arg2;	// IMP=0x00000001000351f4
- (id)init;	// IMP=0x00000001000351dc

@end

