//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/_UIRemoteViewController.h>

@protocol PHInCallBackgroundStyleProtocol, PHPhoneRemoteViewControllerDelegate;

@interface PHPhoneRemoteViewController : _UIRemoteViewController
{
    id <PHPhoneRemoteViewControllerDelegate> _delegate;	// 8 = 0x8
    id <PHInCallBackgroundStyleProtocol> _backgroundStyleDelegate;	// 16 = 0x10
}

+ (id)serviceBundleIdentifier;	// IMP=0x0000000100089394
+ (id)viewControllerClassName;	// IMP=0x000000010008938c
+ (_Bool)shouldPropagateAppearanceCustomizations;	// IMP=0x00000001000891f4
+ (id)requestViewControllerWithConnectionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000890a4
+ (_Bool)isSupported;	// IMP=0x000000010008909c
- (void).cxx_destruct;	// IMP=0x000000010008940c
@property(nonatomic) __weak id <PHInCallBackgroundStyleProtocol> backgroundStyleDelegate; // @synthesize backgroundStyleDelegate=_backgroundStyleDelegate;
@property(nonatomic) __weak id <PHPhoneRemoteViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long backgroundStyle;
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100089314
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100089288
- (void)viewServiceDidTerminateWithError:(id)arg1;	// IMP=0x00000001000891fc

@end

