//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC13callservicesd29VoicemailNotificationProvider.h"

#import "CoreTelephonyClientVoicemailDelegate-Protocol.h"

@interface _TtC13callservicesd29VoicemailNotificationProvider (callservicesd) <CoreTelephonyClientVoicemailDelegate>
- (void)voicemailInfoAvailableNotification:(id)arg1 voicemailInfo:(id)arg2;	// IMP=0x00000001001c780c
@end

