//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NSMutableArray, NSString;

@interface AWDCSDCallStatus : PBCodable <NSCopying>
{
    CDStruct_9f2792e4 _features;	// 8 = 0x8
    unsigned long long _connectionTimeMs;	// 32 = 0x20
    unsigned long long _durationMs;	// 40 = 0x28
    unsigned long long _endReason;	// 48 = 0x30
    long long _providerEndedReason;	// 56 = 0x38
    long long _providerErrorCode;	// 64 = 0x40
    unsigned long long _setupTimeMs;	// 72 = 0x48
    NSString *_callUuid;	// 80 = 0x50
    unsigned int _faceTimeTransportType;	// 88 = 0x58
    int _idsLinkType;	// 92 = 0x5c
    NSString *_providerId;	// 96 = 0x60
    NSMutableArray *_relayDeviceRouteChanges;	// 104 = 0x68
    unsigned int _telephonyTransportType;	// 112 = 0x70
    _Bool _hasConnected;	// 116 = 0x74
    _Bool _hasEnded;	// 117 = 0x75
    _Bool _hasStartedConnecting;	// 118 = 0x76
    _Bool _isCurrentlyGrouped;	// 119 = 0x77
    _Bool _isHeld;	// 120 = 0x78
    _Bool _isIncoming;	// 121 = 0x79
    _Bool _isRelay;	// 122 = 0x7a
    struct {
        unsigned int connectionTimeMs:1;
        unsigned int durationMs:1;
        unsigned int endReason:1;
        unsigned int providerEndedReason:1;
        unsigned int providerErrorCode:1;
        unsigned int setupTimeMs:1;
        unsigned int faceTimeTransportType:1;
        unsigned int idsLinkType:1;
        unsigned int telephonyTransportType:1;
        unsigned int hasConnected:1;
        unsigned int hasEnded:1;
        unsigned int hasStartedConnecting:1;
        unsigned int isCurrentlyGrouped:1;
        unsigned int isHeld:1;
        unsigned int isIncoming:1;
        unsigned int isRelay:1;
    } _has;	// 124 = 0x7c
}

+ (Class)relayDeviceRouteChangeType;	// IMP=0x00000001000144f8
- (void).cxx_destruct;	// IMP=0x00000001000175c4
@property(retain, nonatomic) NSMutableArray *relayDeviceRouteChanges; // @synthesize relayDeviceRouteChanges=_relayDeviceRouteChanges;
@property(nonatomic) _Bool hasStartedConnecting; // @synthesize hasStartedConnecting=_hasStartedConnecting;
@property(nonatomic) long long providerEndedReason; // @synthesize providerEndedReason=_providerEndedReason;
@property(nonatomic) _Bool isRelay; // @synthesize isRelay=_isRelay;
@property(nonatomic) long long providerErrorCode; // @synthesize providerErrorCode=_providerErrorCode;
@property(nonatomic) unsigned int telephonyTransportType; // @synthesize telephonyTransportType=_telephonyTransportType;
@property(nonatomic) unsigned int faceTimeTransportType; // @synthesize faceTimeTransportType=_faceTimeTransportType;
@property(nonatomic) unsigned long long endReason; // @synthesize endReason=_endReason;
@property(nonatomic) unsigned long long connectionTimeMs; // @synthesize connectionTimeMs=_connectionTimeMs;
@property(nonatomic) unsigned long long setupTimeMs; // @synthesize setupTimeMs=_setupTimeMs;
@property(nonatomic) unsigned long long durationMs; // @synthesize durationMs=_durationMs;
@property(nonatomic) _Bool isCurrentlyGrouped; // @synthesize isCurrentlyGrouped=_isCurrentlyGrouped;
@property(nonatomic) _Bool hasEnded; // @synthesize hasEnded=_hasEnded;
@property(nonatomic) _Bool hasConnected; // @synthesize hasConnected=_hasConnected;
@property(nonatomic) _Bool isHeld; // @synthesize isHeld=_isHeld;
@property(nonatomic) _Bool isIncoming; // @synthesize isIncoming=_isIncoming;
@property(retain, nonatomic) NSString *providerId; // @synthesize providerId=_providerId;
@property(retain, nonatomic) NSString *callUuid; // @synthesize callUuid=_callUuid;
- (void)mergeFrom:(id)arg1;	// IMP=0x0000000100017008
- (unsigned long long)hash;	// IMP=0x0000000100016d60
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100016968
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100016500
- (void)copyTo:(id)arg1;	// IMP=0x00000001000160e4
- (void)writeTo:(id)arg1;	// IMP=0x0000000100015cf8
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100015cf0
- (id)dictionaryRepresentation;	// IMP=0x00000001000145b8
- (id)description;	// IMP=0x0000000100014504
- (id)relayDeviceRouteChangeAtIndex:(unsigned long long)arg1;	// IMP=0x00000001000144e0
- (unsigned long long)relayDeviceRouteChangesCount;	// IMP=0x00000001000144c8
- (void)addRelayDeviceRouteChange:(id)arg1;	// IMP=0x0000000100014454
- (void)clearRelayDeviceRouteChanges;	// IMP=0x000000010001443c
- (int)StringAsIdsLinkType:(id)arg1;	// IMP=0x00000001000142fc
- (id)idsLinkTypeAsString:(int)arg1;	// IMP=0x000000010001423c
@property(nonatomic) _Bool hasIdsLinkType;
@property(nonatomic) int idsLinkType; // @synthesize idsLinkType=_idsLinkType;
@property(nonatomic) _Bool hasHasStartedConnecting;
@property(nonatomic) _Bool hasProviderEndedReason;
@property(nonatomic) _Bool hasIsRelay;
@property(nonatomic) _Bool hasProviderErrorCode;
@property(nonatomic) _Bool hasTelephonyTransportType;
@property(nonatomic) _Bool hasFaceTimeTransportType;
@property(nonatomic) _Bool hasEndReason;
- (void)setFeatures:(unsigned int *)arg1 count:(unsigned long long)arg2;	// IMP=0x0000000100013f50
- (unsigned int)featuresAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100013e78
- (void)addFeatures:(unsigned int)arg1;	// IMP=0x0000000100013e64
- (void)clearFeatures;	// IMP=0x0000000100013e54
@property(readonly, nonatomic) unsigned int *features;
@property(readonly, nonatomic) unsigned long long featuresCount;
@property(nonatomic) _Bool hasConnectionTimeMs;
@property(nonatomic) _Bool hasSetupTimeMs;
@property(nonatomic) _Bool hasDurationMs;
@property(nonatomic) _Bool hasIsCurrentlyGrouped;
@property(nonatomic) _Bool hasHasEnded;
@property(nonatomic) _Bool hasHasConnected;
@property(nonatomic) _Bool hasIsHeld;
@property(nonatomic) _Bool hasIsIncoming;
@property(readonly, nonatomic) _Bool hasProviderId;
@property(readonly, nonatomic) _Bool hasCallUuid;
- (void)dealloc;	// IMP=0x0000000100013afc

@end

