//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface SPUsageTrack : NSObject
{
    NSMutableDictionary *_appUsageTrack;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_usageTrackQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000097d4
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *usageTrackQueue; // @synthesize usageTrackQueue=_usageTrackQueue;
@property(retain, nonatomic) NSMutableDictionary *appUsageTrack; // @synthesize appUsageTrack=_appUsageTrack;
- (id)_aggdKeyForApplication:(id)arg1 toGizmo:(_Bool)arg2;	// IMP=0x00000001000096f4
- (id)_aggdDistKeyForApplication:(id)arg1 toGizmo:(_Bool)arg2;	// IMP=0x0000000100009684
- (id)_aggdScalarKeyForIndex:(int)arg1 application:(id)arg2 toGizmo:(_Bool)arg3;	// IMP=0x00000001000095fc
- (unsigned int *)_arrayForApplication:(id)arg1 toGizmo:(_Bool)arg2;	// IMP=0x00000001000094f8
- (int)_indexForSize:(unsigned long long)arg1;	// IMP=0x00000001000094cc
- (void)_updateDataCount:(unsigned long long)arg1 application:(id)arg2 toGizmo:(_Bool)arg3;	// IMP=0x0000000100009328
- (void)dataReceiedFromGizmo:(unsigned long long)arg1 application:(id)arg2;	// IMP=0x0000000100009278
- (void)dataSentToGizmo:(unsigned long long)arg1 application:(id)arg2;	// IMP=0x00000001000091c8
- (void)_logUsageData;	// IMP=0x0000000100008d40
- (void)_printSeparator;	// IMP=0x0000000100008c34
- (void)_printString:(char *)arg1 fromArray:(unsigned int *)arg2;	// IMP=0x0000000100008b30
- (void)_prepareString:(char *)arg1 fromArray:(unsigned int *)arg2;	// IMP=0x0000000100008a44
- (id)init;	// IMP=0x00000001000089ac

@end

