//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SiriUI/SiriUISnippetCollectionViewController.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSCache, NSDate, NSMutableArray, NSMutableSet, NSOperationQueue, NSSet, NSString, SAGuidanceGuideSnippet, SRBigButtonController, UIImage;

@interface SRGuideViewController : SiriUISnippetCollectionViewController <UICollectionViewDataSource, UICollectionViewDelegate>
{
    NSCache *_domainIconCache;	// 8 = 0x8
    NSDate *_startViewingTime;	// 16 = 0x10
    _Bool _showingDetails;	// 24 = 0x18
    NSSet *_siriEnabledAppList;	// 32 = 0x20
    SRBigButtonController *_bigButtonController;	// 40 = 0x28
    NSOperationQueue *_guideImageOperationQueue;	// 48 = 0x30
    NSMutableSet *_spawnedGuideImageFetches;	// 56 = 0x38
    UIImage *_fallbackImage;	// 64 = 0x40
    NSMutableArray *_enabledIntentSupportedAppSnippets;	// 72 = 0x48
    SAGuidanceGuideSnippet *_guideSnippet;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x0000000100027ee8
@property(retain, nonatomic, getter=_guideSnippet) SAGuidanceGuideSnippet *guideSnippet; // @synthesize guideSnippet=_guideSnippet;
- (_Bool)_canShowWhileLocked;	// IMP=0x0000000100027ed0
- (void)_prepareSiriEnabledAppList;	// IMP=0x0000000100027c8c
- (_Bool)_hasTitle;	// IMP=0x0000000100027c14
- (id)_fallbackImage;	// IMP=0x0000000100027b6c
- (id)_iconImageForGuideDomainSnippet:(id)arg1;	// IMP=0x00000001000277f8
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;	// IMP=0x00000001000277e8
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;	// IMP=0x00000001000276b0
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000274b4
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001000274ac
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;	// IMP=0x00000001000274a4
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x00000001000273e8
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x0000000100026d30
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x0000000100026c40
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x0000000100026c38
- (double)_heightOfRowForDomainSnippet:(id)arg1;	// IMP=0x0000000100026b4c
- (id)_domainSnippetForIndexPath:(id)arg1;	// IMP=0x0000000100026abc
- (id)_domainSnippetForEnabledIntentSupportedAppAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100026aa4
- (id)_domainSnippetForHelpDomainAtIndex:(unsigned long long)arg1;	// IMP=0x0000000100026a20
- (long long)_numberOfIntentEnabledApps;	// IMP=0x0000000100026a08
- (long long)_numberOfIntentSupportedApps;	// IMP=0x0000000100026994
- (long long)_numberOfHelpDomains;	// IMP=0x0000000100026920
- (long long)_pinAnimationType;	// IMP=0x0000000100026904
- (_Bool)usePlatterStyle;	// IMP=0x00000001000268fc
- (_Bool)wantsToManageBackgroundColor;	// IMP=0x00000001000268f4
- (double)desiredHeightForTransparentHeaderView;	// IMP=0x0000000100026820
- (void)configureReusableTransparentHeaderView:(id)arg1;	// IMP=0x0000000100026790
- (Class)transparentHeaderViewClass;	// IMP=0x000000010002675c
- (void)_endTrackingGuideShowTimeIfNecessary;	// IMP=0x00000001000265d4
- (double)desiredTopPaddingBelowController:(id)arg1;	// IMP=0x00000001000264ac
- (double)desiredHeightForWidth:(double)arg1;	// IMP=0x00000001000262d4
- (void)siriDidDeactivate;	// IMP=0x00000001000262c8
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100026190
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x0000000100026028
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100025e8c
- (void)loadView;	// IMP=0x0000000100025cc0
- (id)_bigButtonViewController;	// IMP=0x0000000100025bcc
- (void)setDelegate:(id)arg1;	// IMP=0x0000000100025b7c
- (void)didReceiveMemoryWarning;	// IMP=0x0000000100025b24
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0000000100025a10

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

