//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBABackgroundDataClient-Protocol.h"
#import "FBAForegroundDataClient-Protocol.h"
#import "FBALoginManagerDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC18Feedback_Assistant17FBADataClientStub : NSObject <FBAForegroundDataClient, FBABackgroundDataClient, FBALoginManagerDelegate>
{
    MISSING_TYPE *bundle;	// 8 = 0x8
    MISSING_TYPE *testFixtureDir;	// 16 = 0x10
    MISSING_TYPE *Log;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000f0d7c
- (id)init;	// IMP=0x00000001000f0dc8
- (void)getOngoingTasks:(CDUnknownBlockType)arg1;	// IMP=0x00000001000efa6c
- (id)beginUploadWithRequest:(id)arg1 fromFileURL:(id)arg2;	// IMP=0x00000001000ef880
- (void)deleteAtURL:(id)arg1 parameters:(id)arg2 encoding:(unsigned long long)arg3 success:(CDUnknownBlockType)arg4 error:(CDUnknownBlockType)arg5;	// IMP=0x00000001000ef6d8
- (void)deleteResourceAtURL:(id)arg1 success:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;	// IMP=0x00000001000ef54c
- (void)putToURL:(id)arg1 parameters:(id)arg2 encoding:(unsigned long long)arg3 success:(CDUnknownBlockType)arg4 error:(CDUnknownBlockType)arg5;	// IMP=0x00000001000ef508
- (void)postToURL:(id)arg1 parameters:(id)arg2 encoding:(unsigned long long)arg3 success:(CDUnknownBlockType)arg4 error:(CDUnknownBlockType)arg5;	// IMP=0x00000001000ef4c4
- (void)jsonForURL:(id)arg1 success:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;	// IMP=0x00000001000ef384
- (void)dataForURL:(id)arg1 successWithResponse:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;	// IMP=0x00000001000eed9c
- (void)dataForURL:(id)arg1 success:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;	// IMP=0x00000001000eed5c
- (void)jsonForURLRequest:(id)arg1 success:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;	// IMP=0x00000001000eead4
- (void)dataForURLRequest:(id)arg1 successWithResponse:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;	// IMP=0x00000001000ee954
- (void)dataForURLRequest:(id)arg1 success:(CDUnknownBlockType)arg2 error:(CDUnknownBlockType)arg3;	// IMP=0x00000001000ee92c
- (void)didLogInWithUsername:(id)arg1 participantID:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000ee7f0
- (void)didLogOutWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000ee79c
- (id)initForBundle:(id)arg1;	// IMP=0x00000001000ee760

@end

