//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FBADiffableObject-Protocol.h"
#import "NSObject-Protocol.h"

@class DEDDevice, FBAGroupedDevice, NSDictionary, NSSet, NSString;

@protocol DEDDeviceLike <NSObject, FBADiffableObject>
- (_Bool)isLikeDEDDevice:(DEDDevice *)arg1;
- (void)addDevice:(DEDDevice *)arg1;
- (NSString *)hashingKey;
- (NSString *)shortDescription;
- (_Bool)isEqualToDevice:(FBAGroupedDevice *)arg1;
- (_Bool)hasCapabilities:(NSSet *)arg1;
- (NSDictionary *)serialize;
- (NSString *)productType;
- (NSString *)name;
- (NSString *)deviceClass;
- (NSString *)color;
- (NSString *)build;
- (NSString *)publicLogDescription;
- (_Bool)isCurrentDevice;
- (NSString *)platform;
- (NSString *)identifier;
@end

