//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURLRequest;

@interface FBABoxedRequest : NSObject
{
    NSURLRequest *_request;	// 8 = 0x8
    CDUnknownBlockType _successBlock;	// 16 = 0x10
    CDUnknownBlockType _errorBlock;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010000ed44
@property(copy, nonatomic) CDUnknownBlockType errorBlock; // @synthesize errorBlock=_errorBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (id)initWithRequest:(id)arg1 successBlock:(CDUnknownBlockType)arg2 errorBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010000ec28

@end

