//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FBAInboxItemCell.h"

@class FBAFormResponse, FBANetworkMonitor, FBARadialProgressView, UIActivityIndicatorView;

@interface FBAOutboxItemCell : FBAInboxItemCell
{
    FBARadialProgressView *_progressView;	// 64 = 0x40
    FBAFormResponse *_observedResponse;	// 72 = 0x48
    UIActivityIndicatorView *_indeterminateSpinner;	// 80 = 0x50
    FBANetworkMonitor *_netMonitor;	// 88 = 0x58
    unsigned long long _lastStage;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x0000000100052cc8
@property(nonatomic) unsigned long long lastStage; // @synthesize lastStage=_lastStage;
@property(nonatomic) __weak FBANetworkMonitor *netMonitor; // @synthesize netMonitor=_netMonitor;
@property(nonatomic) __weak UIActivityIndicatorView *indeterminateSpinner; // @synthesize indeterminateSpinner=_indeterminateSpinner;
@property(retain, nonatomic) FBAFormResponse *observedResponse; // @synthesize observedResponse=_observedResponse;
@property(nonatomic) __weak FBARadialProgressView *progressView; // @synthesize progressView=_progressView;
- (void)updateUploadStage:(unsigned long long)arg1;	// IMP=0x0000000100052710
- (void)updateProgressWithFormResponse:(id)arg1;	// IMP=0x000000010005259c
- (void)updateForNetworkStateChange:(_Bool)arg1;	// IMP=0x0000000100052440
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000001000522ac
- (void)stopObservingResponse:(id)arg1;	// IMP=0x0000000100052230
- (void)beginObservingResponse:(id)arg1;	// IMP=0x00000001000521ac
- (void)dealloc;	// IMP=0x0000000100052110
- (void)awakeFromNib;	// IMP=0x0000000100051e98

@end

