//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

@interface INRegistrationDigest : NSObject
{
    NSData *_hashData;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100003420
- (unsigned long long)hash;	// IMP=0x0000000100003410
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100003360
- (id)data;	// IMP=0x0000000100003358
- (id)initWithData:(id)arg1;	// IMP=0x00000001000032e0
- (id)initWithRegistrationRequest:(id)arg1;	// IMP=0x000000010000311c

@end

