//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class AWDServerConnection, NSThread;
@protocol OS_dispatch_queue;

@interface WRM_AWDService : NSObject
{
    NSThread *mThread;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *mQueue;	// 16 = 0x10
    AWDServerConnection *mConnection;	// 24 = 0x18
}

- (void)submitMetricPrefInit;	// IMP=0x00000001000e8c38
- (void)submitMetricCellularToWifi;	// IMP=0x00000001000e8650
- (void)submitMericStreaming;	// IMP=0x00000001000e7c24
- (void)submitMericULCACoexStats;	// IMP=0x00000001000e78a4
- (void)submitMericAntSelPolicyStats;	// IMP=0x00000001000e75c0
- (void)submitMericWiFiCallingEnd;	// IMP=0x00000001000e705c
- (void)submitDataLinkPreferenceaMetrics;	// IMP=0x00000001000e68d8
- (void)submitProximityMetrics;	// IMP=0x00000001000e64b0
- (void)submitMetricsFaceTimeHandover;	// IMP=0x00000001000e5ed4
- (void)submitMetricWifiToCellular;	// IMP=0x00000001000e586c
- (void)processMetricQuery:(unsigned int)arg1;	// IMP=0x00000001000e5668
- (void)dealloc;	// IMP=0x00000001000e560c
- (id)init;	// IMP=0x00000001000e47c8

@end

