//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "iOSSetupBaseViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIView;

@interface iOSSetupStartViewController : iOSSetupBaseViewController <UIGestureRecognizerDelegate>
{
    UIButton *_dismissButton;	// 32 = 0x20
    UILabel *_titleLabel;	// 40 = 0x28
    UILabel *_infoLabel;	// 48 = 0x30
    UIImageView *_imageView;	// 56 = 0x38
    UIView *_progressView;	// 64 = 0x40
    UIActivityIndicatorView *_progressSpinner;	// 72 = 0x48
    UILabel *_progressLabel;	// 80 = 0x50
    UIButton *_startButton;	// 88 = 0x58
    _Bool _started;	// 96 = 0x60
    _Bool _autoStart;	// 97 = 0x61
}

- (void).cxx_destruct;	// IMP=0x00000001000413d4
@property(nonatomic) _Bool autoStart; // @synthesize autoStart=_autoStart;
- (void)handleTapOutsideView:(id)arg1;	// IMP=0x000000010004131c
- (void)handleStartButton:(id)arg1;	// IMP=0x0000000100040efc
- (void)handleDeviceSetupNotification:(id)arg1;	// IMP=0x0000000100040c94
- (void)handleDismissButton:(id)arg1;	// IMP=0x0000000100040bfc
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;	// IMP=0x0000000100040b5c
- (_Bool)_canShowWhileLocked;	// IMP=0x0000000100040b54
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x0000000100040a78
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010004043c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

