//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "ComponentControl.h"

#import "tGraphDataSource-Protocol.h"

@interface PackagePowerCC : ComponentControl <tGraphDataSource>
{
    int _packageCCListId;	// 120 = 0x78
}

- (void)refreshCPMSTGraphTelemetry;	// IMP=0x000000010001f7cc
- (void)updatePowerTarget;	// IMP=0x000000010001f6a0
- (void)defaultCPMSAction;	// IMP=0x000000010001f694
- (void)defaultAction;	// IMP=0x000000010001f688
- (id)initWithParams:(struct __CFDictionary *)arg1;	// IMP=0x000000010001f490

@end

