//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CommonProduct.h"

@interface tm0148f449e0ff00c77f11492610c521ce : CommonProduct
{
    float _filteredBacklightCurrentLI2;	// 356 = 0x164
    int _filteredTempMaxCameraDie;	// 360 = 0x168
    int _filteredTempRearCameraDie;	// 364 = 0x16c
    int _filteredTempMic1;	// 368 = 0x170
    int _filteredTempMic2;	// 372 = 0x174
}

- (void)updateCoreAnalyticsInfo;	// IMP=0x000000010003c3c0
- (void)postDeviceTempMetric;	// IMP=0x000000010003c2a0
- (void)updateAggdInfo;	// IMP=0x000000010003c0b4
- (void)updateAllThermalLoad:(_Bool)arg1;	// IMP=0x000000010003b95c
- (int)arcVirtualTemperature;	// IMP=0x000000010003b954
- (int)arcModuleTemperature;	// IMP=0x000000010003b944
- (int)gasGaugeBatteryTemperature;	// IMP=0x000000010003b934
- (void)resetVTFilterState;	// IMP=0x000000010003b8ec
- (id)initProduct:(id)arg1;	// IMP=0x000000010003b894

@end

