//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "USUsageTrackingAgent-Protocol.h"

@interface USUsageTrackingAgent : NSObject <USUsageTrackingAgent>
{
}

- (void)fetchBudgetsWithIdentifier:(id)arg1 clientIdentifier:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100011a64
- (void)checkStatusOfBudgets:(id)arg1 clientIdentifiers:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000119f8
- (void)checkStatusOfAllBudgetsWithReplyHandler:(CDUnknownBlockType)arg1;	// IMP=0x00000001000119e4
- (void)checkStatusOfBudgets:(id)arg1 clientIdentifier:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100011978
- (void)stopMonitoringAllBudgetsWithReplyHandler:(CDUnknownBlockType)arg1;	// IMP=0x0000000100011908
- (void)stopMonitoringBudgets:(id)arg1 clientIdentifier:(id)arg2 replyHandler:(CDUnknownBlockType)arg3;	// IMP=0x0000000100011858
- (void)startMonitoringBudgets:(id)arg1 darwinNotificationName:(id)arg2 notificationTimes:(id)arg3 clientIdentifier:(id)arg4 replyHandler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100011768
- (void)fetchReportsDuringInterval:(id)arg1 partitionInterval:(double)arg2 replyHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000116e0

@end

