//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MRDOutputDeviceRoute.h"

@class AVOutputDevice;

@interface MRDAVOutputDeviceRoute : MRDOutputDeviceRoute
{
    AVOutputDevice *_avOutputDevice;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000a055c
@property(readonly, nonatomic) AVOutputDevice *avOutputDevice; // @synthesize avOutputDevice=_avOutputDevice;
- (id)initWithAVOutputDevice:(id)arg1;	// IMP=0x00000001000a0468

@end

