//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SBSLockScreenContentAssertion;
@protocol OS_os_transaction;

@interface MRDLockScreenAssertion : NSObject
{
    SBSLockScreenContentAssertion *_assertion;	// 8 = 0x8
    NSObject<OS_os_transaction> *_transaction;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00000001000479ec
@property(retain, nonatomic) NSObject<OS_os_transaction> *transaction; // @synthesize transaction=_transaction;
@property(retain, nonatomic) SBSLockScreenContentAssertion *assertion; // @synthesize assertion=_assertion;
- (void)dealloc;	// IMP=0x0000000100047980
- (void)delayCreateAssertion;	// IMP=0x00000001000478a0
- (void)createAssertion;	// IMP=0x0000000100047658
- (id)init;	// IMP=0x0000000100047500

@end

