//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <MediaRemote/MRVirtualVoiceInputDevice.h>

@class MRDMediaRemoteClient;

@interface MRDVirtualAudioInputServerDevice : MRVirtualVoiceInputDevice
{
    MRDMediaRemoteClient *_owningClient;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100032060
@property(readonly, nonatomic) MRDMediaRemoteClient *owningClient; // @synthesize owningClient=_owningClient;
- (id)initWithOwningClient:(id)arg1;	// IMP=0x0000000100031fb8

@end

