//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "WAClientConfigChangedDelegate-Protocol.h"

@class NSString, NSThread, WAClient;
@protocol OS_dispatch_queue;

@interface WiFiManagerAnalytics : NSObject <WAClientConfigChangedDelegate>
{
    _Bool _hasRegisteredWithDaemon;	// 8 = 0x8
    NSThread *_wifiManagerMainThread;	// 16 = 0x10
    WAClient *_waClient;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_serialQ;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x000000010010100c
- (void).cxx_destruct;	// IMP=0x0000000100119948
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQ; // @synthesize serialQ=_serialQ;
@property(nonatomic) _Bool hasRegisteredWithDaemon; // @synthesize hasRegisteredWithDaemon=_hasRegisteredWithDaemon;
@property(retain, nonatomic) WAClient *waClient; // @synthesize waClient=_waClient;
@property(retain, nonatomic) NSThread *wifiManagerMainThread; // @synthesize wifiManagerMainThread=_wifiManagerMainThread;
- (void)_populateDPSLinkStateChangeMessage:(CDStruct_de0e5961 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100119600
- (void)_populateDPSProbeResultMessage:(CDStruct_7fa06ce9 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100119294
- (void)_populateDPSNotificationMessage:(const struct __CFDictionary *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100118fa8
- (void)_populateAirplayStatisticsMessage:(struct WiFiMetricsManagerAirplayStatistics *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100117ce4
- (void)_populateOtaSystemInfoMessage:(CDStruct_d361f42f *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100117538
- (void)_populateSidecarUsageMessage:(struct WiFiMetricsManagerSidecarStatistics *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100116614
- (void)_loadSidecarHistogramBin:(id)arg1 blankAWDSHBInstance:(id)arg2 histogram:(CDStruct_39925896 *)arg3 histogramCount:(unsigned int)arg4 fieldForKey:(id)arg5;	// IMP=0x0000000100116410
- (void)configDidChangeWithConfiguredMetricIDs:(id)arg1 andInterestedMetricIDs:(id)arg2 forGroupType:(long long)arg3;	// IMP=0x000000010011623c
- (void)trigger11axPerfStudy;	// IMP=0x0000000100116134
- (void)collectInterfaceStatsForEventType:(int)arg1 andEvent:(_Bool)arg2 wifiDevice:(struct __WiFiDevice *)arg3 andCellularInterfaceName:(struct __CFString *)arg4;	// IMP=0x0000000100115fb8
- (int)_getAssociationEventIDForEventTypeString:(id)arg1;	// IMP=0x0000000100115eb8
- (void)_populateActionFrameMessage:(CDStruct_a9c4f86c *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100115764
- (void)_populateWiFiConnectionQualityMessageWithScorecard:(id)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100112e60
- (void)_populateAlwaysOnWiFiReportMessage:(id)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001001120ec
- (void)_populateBlacklistingEventMessage:(CDStruct_853d9d76 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100111d70
- (void)_populateAssocHistoryMessageWithString:(id)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100110f34
- (void)_populateSoftErrorCountersMessage:(struct softErrorCounters *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100110d28
- (void)_getPrepopulatedMessageWithID:(unsigned int)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100110a5c
- (void)_populateScanStatsMessageAndReply:(CDUnknownBlockType)arg1;	// IMP=0x00000001001108b0
- (void)_populateAssocInfoMessageAndReply:(CDUnknownBlockType)arg1;	// IMP=0x0000000100110704
- (void)_populatePHClientMessage:(CDStruct_dff281c0 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010011040c
- (void)_populateSoftAPMessage:(CDStruct_42e25c54 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010ff44
- (void)_populateWoWBlacklistHistoryMessage:(CDStruct_46441b56 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010f37c
- (void)_populateNetworkTransitionCumulativeMessage:(struct __WiFiMetricsManagerNetworkTransitionCumulative *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010f12c
- (void)_populateNetworkTransitionSessionRecordsMessage:(CDStruct_32e92d78 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010ead4
- (void)_populateAutoJoinCumulativeMessage:(CDStruct_43080ab9 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010e6a0
- (void)_populateAutoJoinSessionRecordsMessage:(CDStruct_0b3a2485 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010da48
- (void)_populateTXInhibitEventMessage:(CDStruct_b31ca263 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010d858
- (void)_populateUserBlacklistingMessage:(CDStruct_f6842fbd *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010d4d8
- (void)_populateRoamStatusMessage:(CDStruct_9342e987 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010cb14
- (void)_populateLastSSIDInfoStatsMessage:(CDStruct_5bae0375 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010c874
- (void)_populateActiveProbeStatsMessage:(CDStruct_0307c87d *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010c414
- (void)_populateLeakyAPStatsMessage:(CDStruct_1490e47e *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010c0fc
- (void)_populateLinkQualityStatsMessage:(CDStruct_a810ad24 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010b480
- (void)_populateKnownNetworksEventMessage:(CDStruct_474defab *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010b1b0
- (void)_populatePowerStatsUpdateMessage:(CDStruct_cc4e5495 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010aed8
- (void)_populateWifidAvailabilityMessage:(CDStruct_20c13360 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010aca8
- (void)_populateWatchdogEvent:(CDStruct_4ec26687 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001001096a0
- (void)_populateDeviceCountMessage:(CDStruct_eb5aa7f0 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001001093fc
- (void)_populateCustomNetworkSettingMessage:(CDStruct_a561fd19 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001001090b4
- (void)_populateIPV4DHCPLatencyMessage:(CDStruct_32a7f38a *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100108e50
- (void)_populateTetheredDeviceOUIMessage:(CDStruct_8356e4f6 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100108c34
- (void)_populateHotspotTransportMessage:(CDStruct_f4b747e6 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001001089cc
- (void)_populateNetworkPrefsMessage:(CDStruct_e0daccdd *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100107e44
- (void)_populateAssocErrorMessage:(CDStruct_f07423db *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100107a44
- (void)_populateAWDLUsageMessage:(CDStruct_ab83e539 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010010617c
- (void)_populateWoWStateMessage:(CDStruct_b31ca263 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100105f8c
- (void)_populateInterfaceStatsMessage:(CDStruct_aaf269f3 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100105a84
- (void)_populateHardwareVersionMessage:(CDStruct_1d7abdeb *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100105858
- (void)_populateLQMHistoryMessage:(CDStruct_c203e5c3 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100105480
- (void)_populatePowerMessage:(CDStruct_6b48f683 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100105288
- (void)_populate11axLinkChangedMessage:(CDStruct_a4a261f1 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001001044d8
- (void)_populateLinkChangedMessage:(CDStruct_35ff53e1 *)arg1 andReply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100103624
- (id)__copyHashOfSSID:(id)arg1;	// IMP=0x0000000100103414
- (id)_initPrivate;	// IMP=0x0000000100103358
- (id)init;	// IMP=0x0000000100103314
- (void)_registerForQueryableMessages;	// IMP=0x0000000100103118
- (void)prepareMessageForSubmission:(unsigned int)arg1 withData:(void *)arg2 andReply:(CDUnknownBlockType)arg3;	// IMP=0x00000001001025c4
- (void)_runReplyBlock:(CDUnknownBlockType)arg1 withMessage:(id)arg2 andError:(id)arg3;	// IMP=0x0000000100102564
- (void *)_gatherDataForMessageWithIdentifier:(unsigned int)arg1 andArguments:(id)arg2;	// IMP=0x0000000100102318
- (void)_triggerQueryableMessageSubmissionOnMasterThread:(unsigned int)arg1 andArguments:(id)arg2;	// IMP=0x00000001001020ec
- (void)triggerDatapathDiagnosticsNoReply:(id)arg1;	// IMP=0x0000000100101ec4
- (void)submitGeoServicesMessage:(id)arg1;	// IMP=0x0000000100101c70
- (void)submitMessage:(id)arg1;	// IMP=0x0000000100101958
- (void)setWiFiManagerMainThread:(id)arg1;	// IMP=0x00000001001018d4
- (void)_registerQueryableMessageWithIdentifier:(unsigned int)arg1;	// IMP=0x00000001001015cc
- (void)_register;	// IMP=0x0000000100101188

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

