//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface REDActionRefreshSchedule : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    NSMutableDictionary *_hourlyApplicationLaunches;	// 16 = 0x10
    NSMutableDictionary *_dailyApplicationLaunches;	// 24 = 0x18
    NSArray *_upcomingHourlyLaunches;	// 32 = 0x20
    NSArray *_upcomingDailyLaunches;	// 40 = 0x28
    NSString *_scheduleDirectory;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000100006f78
- (_Bool)_shouldLaunchApp:(id)arg1;	// IMP=0x0000000100006e6c
- (void)_queue_markDailyLaunch:(id)arg1;	// IMP=0x0000000100006d94
- (void)_queue_markHourlyLaunch:(id)arg1;	// IMP=0x0000000100006cbc
- (void)_queue_fetchAllDailyApplications:(CDUnknownBlockType)arg1;	// IMP=0x00000001000068ec
- (void)_queue_fetchTopHourlyApplication:(CDUnknownBlockType)arg1;	// IMP=0x0000000100005fe4
- (void)_removePrecedingApplicationLaunches:(id)arg1;	// IMP=0x0000000100005e58
- (void)_saveApplicationList:(id)arg1 toPath:(id)arg2;	// IMP=0x0000000100005d5c
- (id)_loadApplicationListFromPath:(id)arg1;	// IMP=0x0000000100005be4
- (void)recordDailyApplicationLaunch:(id)arg1;	// IMP=0x0000000100005b4c
- (void)recordHourlyApplicationLaunch:(id)arg1;	// IMP=0x0000000100005ab4
- (void)fetchDailyApplications:(CDUnknownBlockType)arg1;	// IMP=0x0000000100005a08
- (void)fetchNextHourlyApplication:(CDUnknownBlockType)arg1;	// IMP=0x0000000100005928
- (id)init;	// IMP=0x00000001000056cc

@end

