//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol REPredictionElementDonatedActionProvider <NSObject>
- (void)predictionElementForAction:(NSString *)arg1 interaction:(NSString *)arg2 completion:(void (^)(REPredictionElement *))arg3;
@end

