//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SafariSharedUI/WBSCloudHistoryConfiguration.h>

@class NSArray, NSDictionary;

@interface CloudHistoryConfiguration : WBSCloudHistoryConfiguration
{
    NSArray *_assetsSortedByVersionNumber;	// 8 = 0x8
    NSDictionary *_remoteConfigurationDictionary;	// 16 = 0x10
    _Bool _fetchedAssetData;	// 24 = 0x18
}

+ (id)sharedConfiguration;	// IMP=0x0000000100068474
- (void).cxx_destruct;	// IMP=0x0000000100068fb8
- (_Bool)shouldUseLongLivedOperationsToSaveRecords;	// IMP=0x0000000100068f8c
- (void)_reloadConfigurationDataIfNecessary;	// IMP=0x0000000100068cb0
- (id)_cloudConfigurationAssetsSortedByVersionNumber;	// IMP=0x0000000100068a1c
- (id)remoteConfiguration;	// IMP=0x0000000100068630
- (id)platformBuiltInConfiguration;	// IMP=0x0000000100068568
- (id)init;	// IMP=0x00000001000684e0

@end

