//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface ScrollToTopView : UIView
{
    CDUnknownBlockType _targetBlock;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000cf220
@property(copy, nonatomic) CDUnknownBlockType targetBlock; // @synthesize targetBlock=_targetBlock;
@property(readonly, nonatomic) double defaultHeight;
- (id)_targetScrollView;	// IMP=0x00000001000cf134
- (void)_tappedScrollToTopView:(id)arg1;	// IMP=0x00000001000cf0f0
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000cf054
- (id)initWithTargetBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000cefc4

@end

