//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "TabThumbnailView.h"

@class GradientView, TabSnapshotImageView, TiltedTabItemLayoutInfo, TiltedTabView;

@interface TiltedTabThumbnailView : TabThumbnailView
{
    GradientView *_contentShadowView;	// 8 = 0x8
    TabSnapshotImageView *_snapshotView;	// 16 = 0x10
    TiltedTabView *_tiltedTabView;	// 24 = 0x18
    TiltedTabItemLayoutInfo *_layoutInfo;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000ad2f4
@property(nonatomic) __weak TiltedTabItemLayoutInfo *layoutInfo; // @synthesize layoutInfo=_layoutInfo;
@property(nonatomic) __weak TiltedTabView *tiltedTabView; // @synthesize tiltedTabView=_tiltedTabView;
@property(readonly, nonatomic) TabSnapshotImageView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(readonly, nonatomic) GradientView *contentShadowView; // @synthesize contentShadowView=_contentShadowView;
- (struct CGRect)headerBackgroundViewFrame;	// IMP=0x00000001000ad12c
- (_Bool)titleIsHorizontallyCentered;	// IMP=0x00000001000ad124
- (_Bool)headerHasFinishedAnimating;	// IMP=0x00000001000ad0b4
- (void)showBlankSnapshotAnimated:(_Bool)arg1;	// IMP=0x00000001000acf00
- (void)setSnapshot:(id)arg1 animated:(_Bool)arg2;	// IMP=0x00000001000aca1c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000ac99c
- (void)prepareForUseAsDragLiftPreview;	// IMP=0x00000001000ac950
- (void)reset;	// IMP=0x00000001000ac934
- (struct CGSize)_snapshotBorderSize;	// IMP=0x00000001000ac884
- (void)setTitleFont:(id)arg1;	// IMP=0x00000001000ac7dc
- (void)layoutSubviews;	// IMP=0x00000001000ac774
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000abc54

@end

