/*
                       * This header is generated by classdump-dyld 1.5
                       * on Wednesday, October 27, 2021 at 3:23:19 PM Mountain Standard Time
                       * Operating System: Version 13.5.1 (Build 17F80)
                       * Image Source: /usr/lib/libtzupdate.dylib
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@class TZFileSystemInterface, NSXPCConnection;

@interface TZUpdate : NSObject {

	TZFileSystemInterface* _fileSystemInterface;
	NSXPCConnection* _connectionToService;

}

@property (retain) TZFileSystemInterface * fileSystemInterface;              //@synthesize fileSystemInterface=_fileSystemInterface - In the implementation block
@property (retain) NSXPCConnection * connectionToService;                    //@synthesize connectionToService=_connectionToService - In the implementation block
+(id)sharedInstance;
-(id)init;
-(void)isUpdateWaitingWithCompletion:(/*^block*/id)arg1 ;
-(id)createNewXPCConnection;
-(BOOL)isUpdateWaiting;
-(TZFileSystemInterface *)fileSystemInterface;
-(void)purgeAllAssetsWithCompletion:(/*^block*/id)arg1 ;
-(id)affectedZones;
-(id)currentTZDataVersion;
-(BOOL)alertForAllZones;
-(id)updateTZDataVersion;
-(void)setFileSystemInterface:(TZFileSystemInterface *)arg1 ;
-(NSXPCConnection *)connectionToService;
-(void)setConnectionToService:(NSXPCConnection *)arg1 ;
@end

