//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSLock, NSString, SCRCTargetSelectorTimer, SCRCThread, VOSCommandManager, VOTKeyInfo;

@interface VOTKeyboardManager : NSObject
{
    NSDictionary *_singleLetterCommandsTable;	// 8 = 0x8
    NSString *_lastLayout;	// 16 = 0x10
    NSDictionary *_layoutToKeyboardMap;	// 24 = 0x18
    NSDictionary *_keyboardMap;	// 32 = 0x20
    unsigned int _currentModifiers;	// 40 = 0x28
    _Bool _modifierToggleSpeakingKeyDown;	// 44 = 0x2c
    NSString *_lastCommand;	// 48 = 0x30
    SCRCTargetSelectorTimer *_keyRepeatTimer;	// 56 = 0x38
    unsigned int _keyboardHelpMask;	// 64 = 0x40
    _Bool _isQuickNavOn;	// 68 = 0x44
    SCRCTargetSelectorTimer *_quickNavRepostTimer;	// 72 = 0x48
    SCRCTargetSelectorTimer *_quickNavKeyTimer;	// 80 = 0x50
    unsigned long long _quickNavStateMask;	// 88 = 0x58
    unsigned long long _quickNavLastDownState;	// 96 = 0x60
    double _quickNavDownStateTime[2];	// 104 = 0x68
    double _quickNavLastRecordedActivation;	// 120 = 0x78
    _Bool _quickNavDidSendDown;	// 128 = 0x80
    _Bool _realCapsLockOn;	// 129 = 0x81
    _Bool _fakeCapsLockOn;	// 130 = 0x82
    _Bool _captureModeEnabled;	// 131 = 0x83
    _Bool _explictlyEnabledQuickNav;	// 132 = 0x84
    VOTKeyInfo *_keyDownInfo;	// 136 = 0x88
    NSLock *_keyDownLock;	// 144 = 0x90
    SCRCThread *_keyboardThread;	// 152 = 0x98
    _Bool _capsLockDown;	// 160 = 0xa0
    _Bool _modifierKeyLockEnabled;	// 161 = 0xa1
    double _capsLockTap1;	// 168 = 0xa8
    long long _consecutiveKeyPressCount;	// 176 = 0xb0
    VOTKeyInfo *_lastKeyForTapCount;	// 184 = 0xb8
    VOSCommandManager *_commandManager;	// 192 = 0xc0
    _Bool _controlKeyToggleSpeakingAllowed;	// 200 = 0xc8
    CDUnknownBlockType _testingEventDispatchTap;	// 208 = 0xd0
    double _quickNavDownDurationAllowedAcceptance;	// 216 = 0xd8
}

+ (id)keyboardManager;	// IMP=0x00000001000def18
+ (void)initialize;	// IMP=0x00000001000deec4
- (void).cxx_destruct;	// IMP=0x00000001000e2e60
@property(nonatomic) _Bool controlKeyToggleSpeakingAllowed; // @synthesize controlKeyToggleSpeakingAllowed=_controlKeyToggleSpeakingAllowed;
@property(nonatomic) double quickNavDownDurationAllowedAcceptance; // @synthesize quickNavDownDurationAllowedAcceptance=_quickNavDownDurationAllowedAcceptance;
@property(copy, nonatomic) CDUnknownBlockType testingEventDispatchTap; // @synthesize testingEventDispatchTap=_testingEventDispatchTap;
@property(nonatomic) _Bool explictlyEnabledQuickNav; // @synthesize explictlyEnabledQuickNav=_explictlyEnabledQuickNav;
@property(readonly, nonatomic) _Bool isQuickNavOn; // @synthesize isQuickNavOn=_isQuickNavOn;
@property(nonatomic) _Bool captureModeEnabled; // @synthesize captureModeEnabled=_captureModeEnabled;
- (void)clearConsecutiveKeyPressCount;	// IMP=0x00000001000e2dec
- (void)_postEvent:(id)arg1;	// IMP=0x00000001000e2d54
- (void)_handleQuickNavPressTimer:(id)arg1;	// IMP=0x00000001000e2d00
- (void)_handleQuickNavPress:(id)arg1;	// IMP=0x00000001000e29a4
- (void)_handleQuickNavDownArrowRepostPress:(id)arg1;	// IMP=0x00000001000e2888
- (void)_postKeyboardKey:(id)arg1 keyCode:(unsigned short)arg2 eventFlags:(unsigned int)arg3 keyFlags:(unsigned short)arg4 keyDown:(_Bool)arg5 source:(unsigned short)arg6;	// IMP=0x00000001000e2668
- (void)_sendEventForCommand:(id)arg1 withKeyInfo:(id)arg2 arrowMask:(long long)arg3;	// IMP=0x00000001000e2510
- (void)_keyRepeat:(id)arg1;	// IMP=0x00000001000e24b8
- (void)_dispatchKeyEventIntoSystem:(id)arg1;	// IMP=0x00000001000e21a8
- (_Bool)_keyInfoIsModifierOnly:(id)arg1;	// IMP=0x00000001000e20b8
- (void)_handleKeyboardKeyEvent:(id)arg1 isRepeatedEvent:(_Bool)arg2;	// IMP=0x00000001000e1e24
- (void)_handleModifierCapsLockBehavior:(id)arg1;	// IMP=0x00000001000e1d64
- (void)_handleCapsLockToggle:(id)arg1;	// IMP=0x00000001000e19e4
- (void)_dispatchEventRepresentationIntoSystem:(id)arg1;	// IMP=0x00000001000e1970
- (_Bool)_keyEventShouldGoToFocusedContext:(id)arg1;	// IMP=0x00000001000e1968
- (void)_handleKeyboardKeyEvent:(id)arg1;	// IMP=0x00000001000e1958
- (void)_updateEventFlags:(id)arg1;	// IMP=0x00000001000e186c
- (void)_handleAnnouncementsForKeyInfo:(id)arg1;	// IMP=0x00000001000e172c
- (void)_speakCapsLockKey;	// IMP=0x00000001000e1680
- (_Bool)_handleArrowKeyEvent:(id)arg1;	// IMP=0x00000001000e1200
- (void)_initializeQuickNav;	// IMP=0x00000001000e1068
- (_Bool)_dispatchCommandForKeyInfo:(id)arg1 isRepeatedEvent:(_Bool)arg2;	// IMP=0x00000001000e06c4
- (id)_localizeKeyboardString:(id)arg1;	// IMP=0x00000001000e0650
- (void)setKeyDownInfo:(id)arg1;	// IMP=0x00000001000e05cc
- (void)_updateConsecutiveKeyCount:(id)arg1;	// IMP=0x00000001000e04d4
- (void)updateQuickNavState:(_Bool)arg1;	// IMP=0x00000001000e04c8
- (id)keyDownInfo;	// IMP=0x00000001000e049c
- (id)threadSafe_keyDownInfo;	// IMP=0x00000001000e0448
- (void)postEvent:(id)arg1;	// IMP=0x00000001000e03c4
- (id)singleLetterCommandForKeyInfo:(id)arg1;	// IMP=0x00000001000e02dc
- (id)keyboardCommandForKeyInfo:(id)arg1;	// IMP=0x00000001000dfbc0
- (id)_characterStringRepresentationForKey:(id)arg1;	// IMP=0x00000001000df750
- (void)loadKeyboardMap;	// IMP=0x00000001000df3f0
- (void)handleKeyboardKeyEvent:(id)arg1 eventOrigin:(long long)arg2;	// IMP=0x00000001000df354
- (void)_initializeThread;	// IMP=0x00000001000df2c0
- (_Bool)modifierKeyLockEnabled;	// IMP=0x00000001000df2b8
- (void)toggleVoiceOverModifierKeyLock;	// IMP=0x00000001000df2a8
- (void)_verifyCorrectThread;	// IMP=0x00000001000df1d8
- (id)init;	// IMP=0x00000001000defb0
- (void)dealloc;	// IMP=0x00000001000def30
- (void)setCommandManager:(id)arg1;	// IMP=0x00000001000def24

@end

