//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSError, NSMutableArray;

@interface NRAccountsManager : NSObject
{
    NSMutableArray *_completions;	// 8 = 0x8
    NSError *_error;	// 16 = 0x10
    struct os_unfair_lock_s _lock;	// 24 = 0x18
    _Bool _alreadySignedOut;	// 28 = 0x1c
}

+ (id)sharedInstance;	// IMP=0x0000000100003230
- (void).cxx_destruct;	// IMP=0x0000000100003980
- (void)reset;	// IMP=0x00000001000036f8
- (void)signOutAccountsWithKill:(_Bool)arg1 queue:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000036e0
- (void)fireCompletionBlocks;	// IMP=0x00000001000033c0
- (_Bool)_addCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x0000000100003310
- (id)init;	// IMP=0x00000001000032d4

@end

