//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ProtocolBuffer/PBCodable.h>

#import "NSCopying-Protocol.h"

@class NRPBNSError;

@interface NRPBCheckTermsEventResponse : PBCodable <NSCopying>
{
    NRPBNSError *_error;	// 8 = 0x8
    _Bool _acknowledged;	// 16 = 0x10
    struct {
        unsigned int acknowledged:1;
    } _has;	// 20 = 0x14
}

- (void).cxx_destruct;	// IMP=0x00000001000845e0
@property(retain, nonatomic) NRPBNSError *error; // @synthesize error=_error;
@property(nonatomic) _Bool acknowledged; // @synthesize acknowledged=_acknowledged;
- (void)mergeFrom:(id)arg1;	// IMP=0x000000010008451c
- (unsigned long long)hash;	// IMP=0x00000001000844b8
- (_Bool)isEqual:(id)arg1;	// IMP=0x00000001000843d8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100084330
- (void)copyTo:(id)arg1;	// IMP=0x00000001000842b8
- (void)writeTo:(id)arg1;	// IMP=0x0000000100084248
- (_Bool)readFrom:(id)arg1;	// IMP=0x0000000100084240
- (id)dictionaryRepresentation;	// IMP=0x0000000100083ea4
- (id)description;	// IMP=0x0000000100083df0
@property(readonly, nonatomic) _Bool hasError;
@property(nonatomic) _Bool hasAcknowledged;

@end

