//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface HNDEvent : NSObject
{
    int _type;	// 8 = 0x8
    struct CGPoint _location;	// 16 = 0x10
    double _deltaX;	// 32 = 0x20
    double _deltaY;	// 40 = 0x28
    long long _buttonNumber;	// 48 = 0x30
    NSString *_actionOverride;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x000000010002dadc
@property(retain, nonatomic) NSString *actionOverride; // @synthesize actionOverride=_actionOverride;
@property(nonatomic) long long buttonNumber; // @synthesize buttonNumber=_buttonNumber;
@property(nonatomic) double deltaY; // @synthesize deltaY=_deltaY;
@property(nonatomic) double deltaX; // @synthesize deltaX=_deltaX;
@property(nonatomic) struct CGPoint location; // @synthesize location=_location;
@property(nonatomic) int type; // @synthesize type=_type;
- (id)description;	// IMP=0x000000010002d93c

@end

