//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCATAuxiliaryElementManager.h"

#import "SCATVisualScrollerContainerViewScrollingDelegate-Protocol.h"
#import "SCATVisualScrollersAuxiliaryElementViewControllerDelegate-Protocol.h"

@class NSArray, NSString;

@interface SCATVisualScrollersAuxiliaryElementManager : SCATAuxiliaryElementManager <SCATVisualScrollersAuxiliaryElementViewControllerDelegate, SCATVisualScrollerContainerViewScrollingDelegate>
{
    _Bool _hasActivatedScrollSinceContextUpdate;	// 8 = 0x8
    NSArray *_scrollerElements;	// 16 = 0x10
    NSArray *_scrollerGroups;	// 24 = 0x18
    long long _mode;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0000000100087a00
@property(nonatomic) _Bool hasActivatedScrollSinceContextUpdate; // @synthesize hasActivatedScrollSinceContextUpdate=_hasActivatedScrollSinceContextUpdate;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
@property(retain, nonatomic) NSArray *scrollerGroups; // @synthesize scrollerGroups=_scrollerGroups;
@property(retain, nonatomic) NSArray *scrollerElements; // @synthesize scrollerElements=_scrollerElements;
- (_Bool)scrollViewController:(id)arg1 showVerticalScrollerForContextElement:(id)arg2;	// IMP=0x0000000100087988
- (_Bool)scrollViewController:(id)arg1 showHorizontalScrollerForContextElement:(id)arg2;	// IMP=0x0000000100087978
- (void)scrollContainer:(id)arg1 scrollInDirection:(long long)arg2;	// IMP=0x000000010008767c
- (_Bool)containsElement:(id)arg1;	// IMP=0x00000001000874cc
- (void)didFinishProvidingElements;	// IMP=0x00000001000874c8
- (void)willBeginProvidingElements;	// IMP=0x00000001000874c4
- (id)elementAfter:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x00000001000873b4
- (id)elementBefore:(id)arg1 didWrap:(_Bool *)arg2 options:(int *)arg3;	// IMP=0x00000001000872a4
- (id)lastElementWithOptions:(int *)arg1;	// IMP=0x0000000100087224
- (id)firstElementWithOptions:(int *)arg1;	// IMP=0x00000001000871a4
- (_Bool)providesElements;	// IMP=0x000000010008719c
- (void)setContextElement:(id)arg1;	// IMP=0x0000000100086ff4
- (id)_groupForElement:(id)arg1;	// IMP=0x0000000100086e34
- (id)scrollerGroupsForContextElement;	// IMP=0x0000000100086b38
- (id)scrollerElementsForContextElement;	// IMP=0x00000001000867a8
- (_Bool)_showScroller:(long long)arg1 withElement:(id)arg2;	// IMP=0x000000010008664c
- (_Bool)_isGroupingEnabled;	// IMP=0x00000001000865f8
- (_Bool)isTopLevel;	// IMP=0x0000000100085e44
- (void)dealloc;	// IMP=0x0000000100085d50
- (id)init;	// IMP=0x0000000100085d40
- (id)initWithMode:(long long)arg1;	// IMP=0x0000000100085c20

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

