//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SCATDriver.h"

@interface SCATDwellDriver : SCATDriver
{
    _Bool _isReadyForSelect;	// 8 = 0x8
}

@property(nonatomic) _Bool isReadyForSelect; // @synthesize isReadyForSelect=_isReadyForSelect;
- (double)dwellDelay;	// IMP=0x000000010006ea48
- (void)_cancelDwellRelatedTimers;	// IMP=0x000000010006e99c
- (void)_scanAbortTimerFired;	// IMP=0x000000010006e948
- (void)_dwellTimerFired;	// IMP=0x000000010006e8f0
- (void)_startScanAbortTimer;	// IMP=0x000000010006e824
- (void)_startDwellTimer;	// IMP=0x000000010006e7d0
- (void)_resetDwellTimer;	// IMP=0x000000010006e774
- (void)_didTransitionToPhase:(int)arg1;	// IMP=0x000000010006e724
- (void)_idleTimerDidFire;	// IMP=0x000000010006e6cc
- (_Bool)_shouldUseScanAbortTimer;	// IMP=0x000000010006e558
- (_Bool)_shouldUseDwellSelection;	// IMP=0x000000010006e50c
- (_Bool)_handleStepPreviousAction;	// IMP=0x000000010006e4b8
- (_Bool)_handleStepNextAction;	// IMP=0x000000010006e464
- (_Bool)_handleStepAction:(long long)arg1;	// IMP=0x000000010006e408
- (_Bool)_handleSelectAction;	// IMP=0x000000010006e3fc
- (_Bool)_actuallyHandleSelectAction;	// IMP=0x000000010006e3c8
- (_Bool)handleInputAction:(long long)arg1;	// IMP=0x000000010006e370
- (int)driverType;	// IMP=0x000000010006e368

@end

