//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDSServiceDelegate-Protocol.h"

@class IDSService, NSString;

@interface IDSNearbyDelegate : NSObject <IDSServiceDelegate>
{
    queue_9c98cea5 fQueue;	// 8 = 0x8
    struct block<void (^)(unsigned int)> fCallback;	// 16 = 0x10
    IDSService *fIDSService;	// 24 = 0x18
    unsigned int _fDeviceCnt;	// 32 = 0x20
}

- (id).cxx_construct;	// IMP=0x0000000100a45078
- (void).cxx_destruct;	// IMP=0x0000000100a45038
@property unsigned int fDeviceCnt; // @synthesize fDeviceCnt=_fDeviceCnt;
- (unsigned int)devicesCount;	// IMP=0x0000000100a4501c
- (_Bool)isNearby;	// IMP=0x0000000100a44ff8
- (void)service:(id)arg1 connectedDevicesChanged:(id)arg2;	// IMP=0x0000000100a44de0
- (void)dealloc;	// IMP=0x0000000100a44d80
- (id)initWithCallback:(CDUnknownBlockType)arg1 queue:(struct dispatch_queue_s *)arg2;	// IMP=0x0000000100a448bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

