//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NWPathEvaluator;

@interface NetworkReachability : NSObject
{
    struct property_source_t<internet_reachability_interface> fInternetReachabilityInterface;	// 8 = 0x8
    struct property_source_t<internet_status> fInternetStatus;	// 48 = 0x30
    struct property_source_t<wifi_status> fWifiStatus;	// 88 = 0x58
    struct RestModule fRestModule;	// 128 = 0x80
    queue_9c98cea5 fQueue;	// 144 = 0x90
    NWPathEvaluator *fNWPathEvaluator;	// 152 = 0x98
    shared_ptr_0fd4464b fRegistry;	// 160 = 0xa0
    struct OsLogLogger *fLogger;	// 176 = 0xb0
}

- (id).cxx_construct;	// IMP=0x0000000100513f94
- (void).cxx_destruct;	// IMP=0x0000000100513ec4
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x0000000100513a5c
- (void)dealloc;	// IMP=0x00000001005139cc
- (void)setup;	// IMP=0x0000000100513678
- (id)initWithRegistry:(shared_ptr_0fd4464b)arg1 andQueue:(struct queue)arg2 andLogger:(struct OsLogLogger *)arg3;	// IMP=0x00000001005133f4

@end

