//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "LakituResponse.h"

@class NSString;

@interface EscrowGenericResponse : LakituResponse
{
}

@property(readonly, nonatomic) long long errorCode;
- (id)errorMessage;	// IMP=0x000000010000ddfc
@property(readonly, nonatomic) NSString *message;
@property(readonly, nonatomic) long long status;
@property(readonly, nonatomic) long long version;
- (id)initWithURLResponse:(id)arg1 data:(id)arg2;	// IMP=0x000000010000d768

@end

