//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "EscrowGenericResponse.h"

@class NSData, NSString;

@interface EscrowCertificateResponse : EscrowGenericResponse
{
    long long _clubID;	// 8 = 0x8
}

@property(readonly, nonatomic) long long clubID; // @synthesize clubID=_clubID;
- (id)description;	// IMP=0x000000010000dfc4
@property(readonly, nonatomic) NSString *dsid;
@property(readonly, nonatomic) NSData *cert;

@end

