//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ManagedConfiguration/MCPasscodeManager.h>

@interface MCPasscodeManagerWriter : MCPasscodeManager
{
}

+ (void)setCurrentEphemeralUserPasscodeTypeFromUnlockScreenType:(int)arg1 simplePasscodeType:(int)arg2;	// IMP=0x000000010008b3f8
+ (_Bool)sendPasscodeRestrictionChangeNotificationIfNeededWithOldRestrictions:(id)arg1 newRestrictions:(id)arg2;	// IMP=0x000000010008b1b8
+ (id)sharedManager;	// IMP=0x000000010008a0dc
- (void)resetPasscodeMetadata;	// IMP=0x000000010008b554
- (_Bool)clearPasscodeWithEscrowKeybagData:(id)arg1 secret:(id)arg2 outError:(id *)arg3;	// IMP=0x000000010008aecc
- (_Bool)changePasscodeFrom:(id)arg1 to:(id)arg2 outError:(id *)arg3;	// IMP=0x000000010008a224
- (void)_sendPasscodeChangedNotification;	// IMP=0x000000010008a1fc
- (void)_setPrivatePasscodeDict:(id)arg1;	// IMP=0x000000010008a110

@end

