//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface MCMSQLiteDB : NSObject
{
    struct sqlite3 *_db;	// 8 = 0x8
    NSURL *_url;	// 16 = 0x10
}

+ (struct sqlite3 *)openDBWithURL:(id)arg1;	// IMP=0x000000010004db08
- (void).cxx_destruct;	// IMP=0x000000010004dafc
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) struct sqlite3 *db; // @synthesize db=_db;
- (_Bool)deleteAllAdvanceCopiesOfCodeSigningEntriesWithError:(id *)arg1;	// IMP=0x000000010004d7e4
- (id)parentIdentifierForChildIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004d3d4
- (id)childIdentifiersForParentIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004cf30
- (id)identifiersWithError:(id *)arg1;	// IMP=0x000000010004cba4
- (id)enumerateIdentifiersAndCodeSigningInfoUsingBlock:(CDUnknownBlockType)arg1;	// IMP=0x000000010004c688
- (_Bool)invalidateCodeSigningForIdentifierAndAllChildren:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004bffc
- (_Bool)invalidateCodeSigningWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004bf04
- (id)codeSigningEntryWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004bcb4
- (_Bool)deleteCodeSigningEntryWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004bbec
- (_Bool)addCodeSigningEntry:(id)arg1 withIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x000000010004b6cc
- (id)_selectCodeSigningEntryWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004b3ac
- (id)_codeSigningEntryFromStatementRow:(struct sqlite3_stmt *)arg1 error:(id *)arg2;	// IMP=0x000000010004b0a0
- (_Bool)_deleteCodeSigningWithIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x000000010004afcc
- (_Bool)_insertCodeSigningData:(id)arg1 forIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x000000010004ab30
- (_Bool)_insertCodeSigningInfo:(id)arg1 forIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x000000010004a94c
- (_Bool)_performInsertOrUpdateQuery:(const char *)arg1 withCodeSigningEntry:(id)arg2 forIdentifier:(id)arg3 isUpdate:(_Bool)arg4 error:(id *)arg5;	// IMP=0x000000010004a298
- (_Bool)_insertChildIdentifier:(id)arg1 forParentIdentifier:(id)arg2 error:(id *)arg3;	// IMP=0x000000010004a194
- (_Bool)_performSingleParameterQuery:(const char *)arg1 withTextInput:(id)arg2 error:(id *)arg3;	// IMP=0x000000010004a180
- (_Bool)_performSingleParameterQuery:(const char *)arg1 withTextInput:(id)arg2 expectedChanges:(int)arg3 error:(id *)arg4;	// IMP=0x000000010004a168
- (_Bool)_performTwoParameterQuery:(const char *)arg1 withTextInputOne:(id)arg2 andTextInputTwo:(id)arg3 expectedChanges:(int)arg4 error:(id *)arg5;	// IMP=0x0000000100049cf0
- (void)closeDB;	// IMP=0x0000000100049b9c
- (_Bool)_sqliteExec:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100049a6c
- (void)dealloc;	// IMP=0x0000000100049a20
- (id)initWithParentDirectoryURL:(id)arg1;	// IMP=0x000000010004990c

@end

