//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class QLCacheVersionedFileIdentifier;

@interface QLCacheFileInfo : NSObject
{
    float _minSize;	// 8 = 0x8
    float _maxSize;	// 12 = 0xc
    unsigned long long _cacheId;	// 16 = 0x10
    QLCacheVersionedFileIdentifier *_fileIdentifier;	// 24 = 0x18
    unsigned long long _thumbnailCount;	// 32 = 0x20
    unsigned long long _totalDataLength;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0000000100007a84
@property(readonly, nonatomic) unsigned long long totalDataLength; // @synthesize totalDataLength=_totalDataLength;
@property(readonly, nonatomic) float maxSize; // @synthesize maxSize=_maxSize;
@property(readonly, nonatomic) float minSize; // @synthesize minSize=_minSize;
@property(readonly, nonatomic) unsigned long long thumbnailCount; // @synthesize thumbnailCount=_thumbnailCount;
@property(readonly, nonatomic) QLCacheVersionedFileIdentifier *fileIdentifier; // @synthesize fileIdentifier=_fileIdentifier;
@property(readonly, nonatomic) unsigned long long cacheId; // @synthesize cacheId=_cacheId;
- (id)initWithCacheId:(unsigned long long)arg1 versionedFileIdentifier:(id)arg2;	// IMP=0x0000000100007a38
- (id)initWithCacheId:(unsigned long long)arg1 versionedFileIdentifier:(id)arg2 thumbnailCount:(unsigned long long)arg3 minSize:(float)arg4 maxSize:(float)arg5 totalDataLength:(unsigned long long)arg6;	// IMP=0x0000000100007990

@end

