//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface CARDNDWatchSyncManager : NSObject
{
}

+ (id)sharedInstance;	// IMP=0x00000001000260dc
- (void)setAutoReplyAudience:(unsigned long long)arg1;	// IMP=0x00000001000262bc
- (void)setAutomaticDNDStatus:(_Bool)arg1;	// IMP=0x000000010002625c
- (void)_syncDomain;	// IMP=0x0000000100026148

@end

