//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SFSpeechRecognitionTaskDelegate-Protocol.h"

@class AVAudioEngine, NSError, NSString, SFSpeechAudioBufferRecognitionRequest, SFSpeechRecognitionTask, SFSpeechRecognizer;

@interface CRDictationService : NSObject <SFSpeechRecognitionTaskDelegate>
{
    _Bool _currentlyRecording;	// 8 = 0x8
    _Bool _currentlyTranscribing;	// 9 = 0x9
    _Bool _finishedTranscribing;	// 10 = 0xa
    NSString *_transcription;	// 16 = 0x10
    NSError *_error;	// 24 = 0x18
    SFSpeechRecognitionTask *_recognitionTask;	// 32 = 0x20
    SFSpeechAudioBufferRecognitionRequest *_recognitionRequest;	// 40 = 0x28
    SFSpeechRecognizer *_speechRecognizer;	// 48 = 0x30
    AVAudioEngine *_audioEngine;	// 56 = 0x38
    CDUnknownBlockType _recordingBlock;	// 64 = 0x40
}

+ (id)sharedInstance;	// IMP=0x000000010000a20c
- (void).cxx_destruct;	// IMP=0x000000010000b2c8
@property(copy, nonatomic) CDUnknownBlockType recordingBlock; // @synthesize recordingBlock=_recordingBlock;
@property(retain, nonatomic) AVAudioEngine *audioEngine; // @synthesize audioEngine=_audioEngine;
@property(retain, nonatomic) SFSpeechRecognizer *speechRecognizer; // @synthesize speechRecognizer=_speechRecognizer;
@property(retain, nonatomic) SFSpeechAudioBufferRecognitionRequest *recognitionRequest; // @synthesize recognitionRequest=_recognitionRequest;
@property(retain, nonatomic) SFSpeechRecognitionTask *recognitionTask; // @synthesize recognitionTask=_recognitionTask;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSString *transcription; // @synthesize transcription=_transcription;
@property(nonatomic) _Bool finishedTranscribing; // @synthesize finishedTranscribing=_finishedTranscribing;
@property(nonatomic) _Bool currentlyTranscribing; // @synthesize currentlyTranscribing=_currentlyTranscribing;
@property(nonatomic) _Bool currentlyRecording; // @synthesize currentlyRecording=_currentlyRecording;
- (void)_playEndDictationChime;	// IMP=0x000000010000b060
- (void)_playStartDictationChimeWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000af98
- (void)speechRecognitionTask:(id)arg1 didFinishSuccessfully:(_Bool)arg2;	// IMP=0x000000010000aed8
- (void)speechRecognitionTask:(id)arg1 didFinishRecognition:(id)arg2;	// IMP=0x000000010000ad90
- (void)speechRecognitionTaskFinishedReadingAudio:(id)arg1;	// IMP=0x000000010000ad80
- (void)speechRecognitionDidDetectSpeech:(id)arg1;	// IMP=0x000000010000ad70
- (void)_endAudioSessionWithError:(id)arg1;	// IMP=0x000000010000ac98
@property(readonly, nonatomic) _Bool dictationAvailable;
@property(readonly, nonatomic) _Bool dictationEnabled;
- (void)_stopRecording;	// IMP=0x000000010000aa8c
- (void)stopRecordingWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000aa58
- (void)beginRecordingWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x000000010000a3a4
- (id)init;	// IMP=0x000000010000a278

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

