//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CRAlert.h"

@class CRVehicleAccessory;

@interface CRVehicleAccessoryAlert : CRAlert
{
    CRVehicleAccessory *_vehicleAccessory;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001000227e0
@property(retain, nonatomic) CRVehicleAccessory *vehicleAccessory; // @synthesize vehicleAccessory=_vehicleAccessory;
- (_Bool)presentAlertWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100022728
- (id)lockscreenMessage;	// IMP=0x000000010002271c
- (id)initWithVehicleAccessory:(id)arg1;	// IMP=0x00000001000226a8

@end

