//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableString, NSString, NSUUID;

@interface PTPObjectInfoDataset : NSObject
{
    unsigned int _storageID;	// 8 = 0x8
    unsigned short _objectFormat;	// 12 = 0xc
    unsigned short _protectionStatus;	// 14 = 0xe
    unsigned long long _objectCompressedSize;	// 16 = 0x10
    unsigned short _thumbFormat;	// 24 = 0x18
    unsigned int _thumbCompressedSize;	// 28 = 0x1c
    unsigned int _thumbOffset;	// 32 = 0x20
    unsigned int _thumbPixWidth;	// 36 = 0x24
    unsigned int _thumbPixHeight;	// 40 = 0x28
    unsigned int _imagePixWidth;	// 44 = 0x2c
    unsigned int _imagePixHeight;	// 48 = 0x30
    unsigned int _imageBitDepth;	// 52 = 0x34
    unsigned int _parentObject;	// 56 = 0x38
    unsigned short _associationType;	// 60 = 0x3c
    unsigned int _associationDesc;	// 64 = 0x40
    unsigned int _sequenceNumber;	// 68 = 0x44
    NSString *_filename;	// 72 = 0x48
    NSString *_captureDate;	// 80 = 0x50
    NSString *_modificationDate;	// 88 = 0x58
    NSMutableString *_keywords;	// 96 = 0x60
    unsigned int _thmFileSize;	// 104 = 0x68
    unsigned int _objectHandle;	// 108 = 0x6c
    NSUUID *_relatedUUID;	// 112 = 0x70
    long long _intervalSince1970;	// 120 = 0x78
}

- (long long)intervalSince1970;	// IMP=0x000000010001ddf8
- (id)relatedUUID;	// IMP=0x000000010001dcf0
- (unsigned int)objectBufferSizeForContentType:(int)arg1;	// IMP=0x000000010001dcb4
- (unsigned int)objectContentSizeForContentType:(int)arg1;	// IMP=0x000000010001dc78
- (void)setObjectHandle:(unsigned int)arg1;	// IMP=0x000000010001dc70
- (unsigned int)objectHandle;	// IMP=0x000000010001dc68
- (void)addCustomKeyword:(id)arg1 withIdentifier:(id)arg2;	// IMP=0x000000010001dbd0
- (void)setKeywords:(id)arg1;	// IMP=0x000000010001db7c
- (id)keywords;	// IMP=0x000000010001db5c
- (void)setModificationDate:(id)arg1;	// IMP=0x000000010001db20
- (id)modificationDate;	// IMP=0x000000010001db18
- (void)setCaptureDate:(id)arg1;	// IMP=0x000000010001dac0
- (id)captureDate;	// IMP=0x000000010001dab8
- (void)setFilename:(id)arg1;	// IMP=0x000000010001da7c
- (id)filename;	// IMP=0x000000010001da74
- (void)setSequenceNumber:(unsigned int)arg1;	// IMP=0x000000010001da6c
- (unsigned int)sequenceNumber;	// IMP=0x000000010001da64
- (void)setAssociationDesc:(unsigned int)arg1;	// IMP=0x000000010001da5c
- (unsigned int)associationDesc;	// IMP=0x000000010001da54
- (void)setAssociationType:(unsigned short)arg1;	// IMP=0x000000010001da4c
- (unsigned short)associationType;	// IMP=0x000000010001da44
- (void)setParentObject:(unsigned int)arg1;	// IMP=0x000000010001da3c
- (unsigned int)parentObject;	// IMP=0x000000010001da34
- (void)setImageBitDepth:(unsigned int)arg1;	// IMP=0x000000010001da2c
- (unsigned int)imageBitDepth;	// IMP=0x000000010001da24
- (void)setImagePixHeight:(unsigned int)arg1;	// IMP=0x000000010001da1c
- (unsigned int)imagePixHeight;	// IMP=0x000000010001da14
- (void)setImagePixWidth:(unsigned int)arg1;	// IMP=0x000000010001da0c
- (unsigned int)imagePixWidth;	// IMP=0x000000010001da04
- (void)setThumbPixHeight:(unsigned int)arg1;	// IMP=0x000000010001d9fc
- (unsigned int)thumbPixHeight;	// IMP=0x000000010001d9f4
- (void)setThumbPixWidth:(unsigned int)arg1;	// IMP=0x000000010001d9ec
- (unsigned int)thumbPixWidth;	// IMP=0x000000010001d9e4
- (void)setThumbOffset:(unsigned int)arg1;	// IMP=0x000000010001d9dc
- (unsigned int)thumbOffset;	// IMP=0x000000010001d9d4
- (void)setThmFileSize:(unsigned int)arg1;	// IMP=0x000000010001d9cc
- (unsigned int)thmFileSize;	// IMP=0x000000010001d9c4
- (void)setThumbCompressedSize:(unsigned int)arg1;	// IMP=0x000000010001d9bc
- (unsigned int)thumbCompressedSize;	// IMP=0x000000010001d9b4
- (void)setThumbFormat:(unsigned short)arg1;	// IMP=0x000000010001d9ac
- (unsigned short)thumbFormat;	// IMP=0x000000010001d9a4
- (void)setObjectCompressedSize:(unsigned long long)arg1;	// IMP=0x000000010001d99c
- (unsigned int)objectCompressedSize;	// IMP=0x000000010001d988
- (unsigned long long)objectCompressedSize64;	// IMP=0x000000010001d980
- (void)setProtectionStatus:(unsigned short)arg1;	// IMP=0x000000010001d978
- (unsigned short)protectionStatus;	// IMP=0x000000010001d970
- (void)setObjectFormat:(unsigned short)arg1;	// IMP=0x000000010001d968
- (unsigned short)objectFormat;	// IMP=0x000000010001d960
- (void)setStorageID:(unsigned int)arg1;	// IMP=0x000000010001d958
- (unsigned int)storageID;	// IMP=0x000000010001d950
- (id)description;	// IMP=0x000000010001d840
- (id)content:(int)arg1;	// IMP=0x000000010001d664
- (_Bool)contentLengthValid:(unsigned int)arg1 forContentType:(int)arg2;	// IMP=0x000000010001d618
- (void)contentLength:(unsigned int *)arg1 bufferLength:(unsigned int *)arg2 contentType:(int)arg3;	// IMP=0x000000010001d4f0
- (id)content;	// IMP=0x000000010001d4e0
- (void)dealloc;	// IMP=0x000000010001d478
- (id)initWithBytes:(char *)arg1 length:(unsigned int)arg2 contentType:(int)arg3;	// IMP=0x000000010001d0ac
- (id)initWithData:(id)arg1 contentType:(int)arg2;	// IMP=0x000000010001d044
- (id)initWithBytes:(char *)arg1 length:(unsigned int)arg2;	// IMP=0x000000010001d034
- (id)initWithData:(id)arg1;	// IMP=0x000000010001d024
- (id)init;	// IMP=0x000000010001cff0

@end

