//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@class MISSING_TYPE;

@interface _TtC8AppStore24InfiniteScrollFooterView : UICollectionReusableView
{
    MISSING_TYPE *activityIndicator;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100014c30
- (void)willMoveToSuperview:(id)arg1;	// IMP=0x0000000100014b44
- (void)willMoveToWindow:(id)arg1;	// IMP=0x0000000100014b30
- (void)prepareForReuse;	// IMP=0x0000000100014ac4
- (void)layoutSubviews;	// IMP=0x00000001000149a4
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x000000010001473c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000146e4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000146c4

@end

