//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8AppStore15TitleHeaderView.h"

@class MISSING_TYPE;

@interface _TtC8AppStore16ArcadeHeaderView : _TtC8AppStore15TitleHeaderView
{
    MISSING_TYPE *effect;	// 368 = 0x170
    MISSING_TYPE *gradientLayer;	// 416 = 0x1a0
}

- (void).cxx_destruct;	// IMP=0x00000001000e1dac
- (void)layoutSubviews;	// IMP=0x00000001000e141c
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000e0d80

@end

