//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_TtC8AppStore29StoreCollectionViewController.h"

@class MISSING_TYPE;

@interface _TtC8AppStore27SearchResultsViewController : _TtC8AppStore29StoreCollectionViewController
{
    MISSING_TYPE *presenter;	// 136 = 0x88
    MISSING_TYPE *objectGraph;	// 144 = 0x90
    MISSING_TYPE *artworkLoader;	// 152 = 0x98
    MISSING_TYPE *storeDataProvider;	// 160 = 0xa0
    MISSING_TYPE *artworkIconFetcher;	// 176 = 0xb0
    MISSING_TYPE *tableFlowLayout;	// 184 = 0xb8
    MISSING_TYPE *gridFlowLayout;	// 192 = 0xc0
    MISSING_TYPE *searchResultsCollectionViewDataSource;	// 200 = 0xc8
    MISSING_TYPE *searchResultsCollectionViewDelegate;	// 208 = 0xd0
    MISSING_TYPE *flowPreviewing;	// 216 = 0xd8
    MISSING_TYPE *noResultsView;	// 224 = 0xe0
    MISSING_TYPE *delegate;	// 232 = 0xe8
    MISSING_TYPE *advertRotationController;	// 248 = 0xf8
    MISSING_TYPE *isAutoPlayEnabled;	// 256 = 0x100
    MISSING_TYPE *allowsResultFiltering;	// 257 = 0x101
}

- (void).cxx_destruct;	// IMP=0x00000001001e5e48
- (id)initWithCollectionViewLayout:(id)arg1;	// IMP=0x00000001001e5f30
- (void)dealloc;	// IMP=0x00000001001e5e24
- (void)collectionView:(id)arg1 prefetchItemsAtIndexPaths:(id)arg2;	// IMP=0x00000001001e5c08
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x00000001001e5b1c
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x00000001001e5ab0
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x00000001001e5aa8
- (void)viewWillLayoutSubviews;	// IMP=0x00000001001e4d6c
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x00000001001e4ad4
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001001e44f4
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x00000001001e414c
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001001e4110
- (void)as_viewDidBecomePartiallyVisible;	// IMP=0x00000001001e3fd4
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001001e3ed8
- (void)as_viewWillBecomePartiallyVisible;	// IMP=0x00000001001e3d60
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001001e3c60
- (void)as_viewDidBecomeFullyVisible;	// IMP=0x00000001001e3a10
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001001e395c
- (void)as_viewWillBecomeFullyVisible;	// IMP=0x00000001001e3930
- (void)viewDidLoad;	// IMP=0x00000001001e35e4
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001001e29cc

@end

