//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class MISSING_TYPE, NSString;

@interface _TtC10healthappd22DaemonListenerDelegate : NSObject <NSXPCListenerDelegate>
{
    MISSING_TYPE *healthExperienceStoreOracle;	// 8 = 0x8
    MISSING_TYPE *$__lazy_storage_$_availablePlugins;	// 16 = 0x10
    MISSING_TYPE *feedPopulationManagerOracle;	// 24 = 0x18
    MISSING_TYPE *longRunningProcessOracle;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010001eed0
- (id)init;	// IMP=0x000000010001ef28
- (void)dealloc;	// IMP=0x000000010001ee74
@property(nonatomic, readonly) NSString *description;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010001eaf4

@end

