//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "DDRManagerDelegate-Protocol.h"
#import "DDRObserverServerDelegate-Protocol.h"
#import "DDRServerProtocol-Protocol.h"
#import "NSXPCListenerDelegate-Protocol.h"

@class DDRManager, DDRObserverServer, NSMutableArray, NSString, NSXPCConnection, NSXPCListener;
@protocol OS_dispatch_queue;

@interface DDRServer : NSObject <NSXPCListenerDelegate, DDRServerProtocol, DDRManagerDelegate, DDRObserverServerDelegate>
{
    NSXPCListener *_listener;	// 8 = 0x8
    DDRObserverServer *_observerServer;	// 16 = 0x10
    NSMutableArray *_clients;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_serverQueue;	// 32 = 0x20
    DDRManager *_manager;	// 40 = 0x28
    long long _currentResetState;	// 48 = 0x30
    CDUnknownBlockType _completion;	// 56 = 0x38
    NSXPCConnection *_completionClient;	// 64 = 0x40
    long long _currentResetMode;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0000000100003cb8
@property(nonatomic) long long currentResetMode; // @synthesize currentResetMode=_currentResetMode;
@property(retain, nonatomic) NSXPCConnection *completionClient; // @synthesize completionClient=_completionClient;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) long long currentResetState; // @synthesize currentResetState=_currentResetState;
@property(retain, nonatomic) DDRManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serverQueue; // @synthesize serverQueue=_serverQueue;
@property(retain, nonatomic) NSMutableArray *clients; // @synthesize clients=_clients;
@property(retain, nonatomic) DDRObserverServer *observerServer; // @synthesize observerServer=_observerServer;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
- (void)resetWithModeDidFinish:(long long)arg1 error:(id)arg2;	// IMP=0x0000000100003454
- (void)resetWithModeDidBegin:(long long)arg1;	// IMP=0x000000010000326c
- (void)resetWithMode:(long long)arg1 didUpdateWithProgress:(double)arg2;	// IMP=0x0000000100003268
- (void)resetWithModeWillBegin:(long long)arg1;	// IMP=0x0000000100003080
- (void)resetDataWithRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0000000100002dd8
- (void)didAddObserverClientWithXPCConnection:(id)arg1;	// IMP=0x0000000100002b48
- (_Bool)connectionHasRequiredEntitlements:(id)arg1;	// IMP=0x0000000100002b3c
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000100002604
- (_Bool)hasRequiredEntitlements:(id)arg1;	// IMP=0x000000010000247c
- (void)start;	// IMP=0x00000001000021c4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

