//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSXPCListener.h>

#import "NSXPCListenerDelegate-Protocol.h"
#import "_CDInteractionXPCProtocol-Protocol.h"

@class NSObject, NSString, _CDInteractionAdviceEngine, _CDInteractionPolicies, _CDInteractionStore, _DKDataProtectionStateMonitor, _PSEnsembleModel, _PSSuggester;
@protocol OS_dispatch_queue, _DKKnowledgeQuerying><_DKKnowledgeSaving, _DKLocationHistorian;

@interface CDPeopleDaemon : NSXPCListener <NSXPCListenerDelegate, _CDInteractionXPCProtocol>
{
    _CDInteractionAdviceEngine *_advisor;	// 72 = 0x48
    _DKDataProtectionStateMonitor *_dataProtection;	// 80 = 0x50
    _CDInteractionPolicies *_policies;	// 88 = 0x58
    id <_DKLocationHistorian> _locationHistorian;	// 96 = 0x60
    NSObject<OS_dispatch_queue> *_workQueue;	// 104 = 0x68
    _CDInteractionStore *_store;	// 112 = 0x70
    id <_DKKnowledgeQuerying><_DKKnowledgeSaving> _knowledgeStore;	// 120 = 0x78
    _PSSuggester *_suggester;	// 128 = 0x80
    _PSEnsembleModel *_ensembleModel;	// 136 = 0x88
}

+ (id)readRepopulationCheckpoint;	// IMP=0x0000000100007234
+ (_Bool)writeRepopulationCheckpoint:(id)arg1;	// IMP=0x0000000100007144
- (void).cxx_destruct;	// IMP=0x000000010000aa8c
@property(readonly, nonatomic) _PSEnsembleModel *ensembleModel; // @synthesize ensembleModel=_ensembleModel;
@property(readonly, nonatomic) _PSSuggester *suggester; // @synthesize suggester=_suggester;
@property(readonly, nonatomic) id <_DKKnowledgeQuerying><_DKKnowledgeSaving> knowledgeStore; // @synthesize knowledgeStore=_knowledgeStore;
@property(readonly, nonatomic) _CDInteractionStore *store; // @synthesize store=_store;
- (void)reportPeopleStatistics;	// IMP=0x000000010000a7d4
- (void)logSizeOfStorage:(id)arg1;	// IMP=0x000000010000a46c
- (void)populateSharingAppUsageCache;	// IMP=0x000000010000a41c
- (void)_maintainPrivacy;	// IMP=0x0000000100009f50
- (void)maintainPrivacy;	// IMP=0x0000000100009e74
- (void)tuneSocialAdvisorUsingSettings:(id)arg1 heartBeatHandler:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100009d6c
- (void)adviseSocialInteractionsForDate:(id)arg1 andSeedContacts:(id)arg2 usingSettings:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0000000100009c08
- (void)adviseInteractionsForLocation:(id)arg1 usingSettings:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100009a70
- (void)adviseInteractionsForKeywordsInString:(id)arg1 usingSettings:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100009928
- (void)adviseInteractionsForDate:(id)arg1 usingSettings:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x00000001000097e0
- (void)adviseInteractionsUsingSettings:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00000001000096a8
- (void)fillInCurrentLocationIfNeeded:(id)arg1;	// IMP=0x0000000100009594
- (void)rankCandidateContacts:(id)arg1 usingSettings:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010000944c
- (void)rankedAutocompleteSuggestionsFromContext:(id)arg1 candidates:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100009354
- (void)rankedContactSuggestionsFromContext:(id)arg1 contactsOnly:(_Bool)arg2 maxSuggestions:(id)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0000000100009240
- (void)rankedNameSuggestionsFromContext:(id)arg1 name:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100009148
- (void)messagesZKWSuggestionsFromContext:(id)arg1 maxSuggestions:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x000000010000903c
- (void)mapsSuggestionsFromContext:(id)arg1 maxSuggestions:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008f30
- (void)shareExtensionSuggestionsFromContext:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100008e5c
- (void)suggestInteractionsFromContext:(id)arg1 maxSuggestions:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008d48
- (void)deleteInteractionsWithBundleId:(id)arg1 domainIdentifier:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008b3c
- (void)deleteInteractionsWithBundleId:(id)arg1 account:(id)arg2 reply:(CDUnknownBlockType)arg3;	// IMP=0x0000000100008930
- (void)deleteInteractionsWithBundleId:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100008748
- (void)deleteInteractionsMatchingPredicate:(id)arg1 sortDescriptors:(id)arg2 limit:(unsigned long long)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0000000100008524
- (void)countContactsUsingPredicate:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x000000010000833c
- (void)countInteractionsUsingPredicate:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x0000000100008154
- (void)queryContactsUsingPredicate:(id)arg1 sortDescriptors:(id)arg2 limit:(unsigned long long)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0000000100007f2c
- (void)queryInteractionsUsingPredicate:(id)arg1 sortDescriptors:(id)arg2 limit:(unsigned long long)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0000000100007ccc
- (void)recordInteractions:(id)arg1 enforceDataLimits:(_Bool)arg2 enforcePrivacy:(_Bool)arg3 reply:(CDUnknownBlockType)arg4;	// IMP=0x0000000100007b60
- (void)setLocationHistorian:(id)arg1;	// IMP=0x0000000100007af4
- (_Bool)isClassCLocked;	// IMP=0x0000000100007abc
- (_Bool)requestInteractionRepopulation;	// IMP=0x000000010000730c
- (_Bool)versionCheckAndUpgradeIfNecessaryAndPossible;	// IMP=0x0000000100006e68
- (void)writeVersionNumberToDefaults:(unsigned long long)arg1;	// IMP=0x0000000100006e00
- (long long)readVersionNumberFromDefaults;	// IMP=0x0000000100006da4
- (void)handleError:(id)arg1;	// IMP=0x0000000100006b30
- (void)populatePeopleSuggesterCaches;	// IMP=0x0000000100006a40
- (void)setupDataProtectionChangeHandler;	// IMP=0x0000000100006710
- (id)workQueue;	// IMP=0x0000000100006700
- (id)initWithKnowledgeStore:(id)arg1;	// IMP=0x0000000100006274
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x0000000100005fec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

