//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UISystemShellApplication.h>

#import "CRSAppHistoryDataProviding-Protocol.h"
#import "CRSAppHistoryServiceDelegate-Protocol.h"
#import "CRSIconLayoutServiceDelegate-Protocol.h"
#import "FBSystemServiceDelegate-Protocol.h"

@class CARAppHistory, CARDisplayManager, CRSAppHistoryService, CRSIconLayoutService, CRSSessionService, FBSApplicationLibrary, NSMutableDictionary, NSString;

@interface CARApplication : UISystemShellApplication <CRSIconLayoutServiceDelegate, FBSystemServiceDelegate, CRSAppHistoryServiceDelegate, CRSAppHistoryDataProviding>
{
    FBSApplicationLibrary *_sharedApplicationLibrary;	// 8 = 0x8
    CARDisplayManager *_displayManager;	// 16 = 0x10
    CRSSessionService *_sessionService;	// 24 = 0x18
    CRSIconLayoutService *_iconLayoutService;	// 32 = 0x20
    NSMutableDictionary *_iconLayoutDataProviders;	// 40 = 0x28
    CARAppHistory *_appHistory;	// 48 = 0x30
    CRSAppHistoryService *_appHistoryService;	// 56 = 0x38
}

+ (id)_newApplicationInitializationContext;	// IMP=0x0000000100094e3c
+ (id)_newApplicationLibrary;	// IMP=0x00000001000946a4
+ (_Bool)registerAsSystemApp;	// IMP=0x0000000100094520
- (void).cxx_destruct;	// IMP=0x0000000100096030
@property(retain, nonatomic) CRSAppHistoryService *appHistoryService; // @synthesize appHistoryService=_appHistoryService;
@property(retain, nonatomic) CARAppHistory *appHistory; // @synthesize appHistory=_appHistory;
@property(retain, nonatomic) NSMutableDictionary *iconLayoutDataProviders; // @synthesize iconLayoutDataProviders=_iconLayoutDataProviders;
@property(retain, nonatomic) CRSIconLayoutService *iconLayoutService; // @synthesize iconLayoutService=_iconLayoutService;
@property(retain, nonatomic) CRSSessionService *sessionService; // @synthesize sessionService=_sessionService;
@property(retain, nonatomic) CARDisplayManager *displayManager; // @synthesize displayManager=_displayManager;
- (_Bool)runTest:(id)arg1 options:(id)arg2;	// IMP=0x0000000100095c70
- (void)getSessionEchoContextStatesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100095bdc
- (void)getSessionUIContextStatesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100095b48
- (void)getUIContextStatesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100095ad0
- (id)_currentAppHistory;	// IMP=0x000000010009590c
- (id)_currentDashboard;	// IMP=0x000000010009575c
- (id)appHistoryDataProviderForService:(id)arg1;	// IMP=0x0000000100095758
- (void)systemService:(id)arg1 handleOpenApplicationRequest:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x00000001000952d0
- (void)systemService:(id)arg1 canActivateApplication:(id)arg2 withResult:(CDUnknownBlockType)arg3;	// IMP=0x0000000100095224
- (id)systemServiceApplicationInfoProvider:(id)arg1;	// IMP=0x0000000100095218
- (id)iconLayoutService:(id)arg1 dataProviderForVehicleID:(id)arg2;	// IMP=0x0000000100094e44
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0000000100094ca4
- (_Bool)handleDoubleHeightStatusBarTapWithStyleOverride:(int)arg1;	// IMP=0x000000010009469c
- (id)_windowForSystemAppButtonEventsForScreen:(id)arg1;	// IMP=0x00000001000945f0
- (id)_keyWindowForScreen:(id)arg1;	// IMP=0x0000000100094528
- (_Bool)_hostsSystemStatusBar;	// IMP=0x0000000100094518
- (_Bool)disablesFrontBoardImplicitWindowScenes;	// IMP=0x0000000100094510
- (id)sharedApplicationLibrary;	// IMP=0x0000000100094500
- (void)dealloc;	// IMP=0x0000000100094490
- (id)init;	// IMP=0x000000010009438c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

