//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CARSmartWidgetEngine, NSArray;

@protocol CARSmartWidgetEngineObserver <NSObject>
- (void)smartWidgetEngineDidStop:(CARSmartWidgetEngine *)arg1;
- (void)smartWidgetEngineDidStart:(CARSmartWidgetEngine *)arg1;
- (void)smartWidgetEngineDidUpdatePredictionsFresh:(CARSmartWidgetEngine *)arg1;
- (void)smartWidgetEngine:(CARSmartWidgetEngine *)arg1 didUpdateCurrentPredictions:(NSArray *)arg2;
@end

