//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CARSmartWidgetPrediction.h"

#import "WFLActionUserInterface-Protocol.h"
#import "WFLWorkflowControllerDelegate-Protocol.h"

@class ATXScoredPrediction, INIntent, NSString, WFLWorkflowController;

@interface CARSmartWidgetAppPrediction : CARSmartWidgetPrediction <WFLWorkflowControllerDelegate, WFLActionUserInterface>
{
    ATXScoredPrediction *_scoredAction;	// 8 = 0x8
    WFLWorkflowController *_workflowController;	// 16 = 0x10
}

+ (double)minValue;	// IMP=0x0000000100058a2c
+ (double)maxValue;	// IMP=0x0000000100058a10
+ (long long)baseScore;	// IMP=0x00000001000589b4
+ (double)minActionScore;	// IMP=0x000000010005812c
+ (void)setMinActionScore:(double)arg1;	// IMP=0x0000000100058120
+ (double)maxActionScore;	// IMP=0x0000000100058114
+ (void)setMaxActionScore:(double)arg1;	// IMP=0x0000000100058108
- (void).cxx_destruct;	// IMP=0x0000000100058f0c
@property(retain, nonatomic) WFLWorkflowController *workflowController; // @synthesize workflowController=_workflowController;
@property(readonly, nonatomic) ATXScoredPrediction *scoredAction; // @synthesize scoredAction=_scoredAction;
- (void)action:(id)arg1 requiresContinuingInAppWithProceedHandler:(CDUnknownBlockType)arg2;	// IMP=0x0000000100058e64
- (void)handleIntentAction:(id)arg1 requiresUserConfirmation:(_Bool)arg2 requiresUserAuthentication:(_Bool)arg3 withIntentResponse:(id)arg4 proceedHandler:(CDUnknownBlockType)arg5;	// IMP=0x0000000100058df4
- (void)action:(id)arg1 requiresUserConfirmation:(_Bool)arg2 requiresUserAuthentication:(_Bool)arg3 proceedHandler:(CDUnknownBlockType)arg4;	// IMP=0x0000000100058d84
- (void)logDebugInformation:(id)arg1;	// IMP=0x0000000100058d20
- (id)workflowController:(id)arg1 userInterfaceForRunningAction:(id)arg2;	// IMP=0x0000000100058cac
- (void)workflowController:(id)arg1 didRunAction:(id)arg2;	// IMP=0x0000000100058c48
- (void)workflowController:(id)arg1 willRunAction:(id)arg2 withInput:(id)arg3 proceedHandler:(CDUnknownBlockType)arg4;	// IMP=0x0000000100058bb4
- (void)workflowControllerDidStop:(id)arg1 withError:(id)arg2;	// IMP=0x0000000100058b30
- (void)workflowControllerDidFinishRunning:(id)arg1 withOutput:(id)arg2;	// IMP=0x0000000100058aac
- (void)workflowControllerWillRun:(id)arg1;	// IMP=0x0000000100058a48
- (double)value;	// IMP=0x00000001000589bc
- (id)image;	// IMP=0x00000001000588dc
- (CDUnknownBlockType)actionBlock;	// IMP=0x000000010005881c
- (id)subtitle;	// IMP=0x0000000100058740
- (id)title;	// IMP=0x00000001000584f8
- (id)predictedObject;	// IMP=0x00000001000584ec
- (id)uniqueIdentifier;	// IMP=0x0000000100058470
- (void)_runAction;	// IMP=0x00000001000581b4
@property(readonly, nonatomic) INIntent *intent;
- (id)initWithScoredAction:(id)arg1;	// IMP=0x0000000100058088

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

