//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Intents/INIntent.h>

@class NSArray, NSString;

@interface INIntent (CARSmartWidget)
@property(readonly, nonatomic) _Bool car_valid;
@property(readonly, nonatomic) NSString *car_action;
@property(readonly, nonatomic) NSArray *car_people;
@end

