//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MICapabilitiesManager : NSObject
{
}

+ (id)defaultManager;	// IMP=0x0000000100028ff0
- (id)checkCapabilities:(id)arg1 withOptions:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000290a4

@end

