//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "RTCReportingBackend.h"

@class NSMutableArray, NSObject, NSString;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface DashboardBackend : RTCReportingBackend
{
    int _socketDescriptor;	// 220 = 0xdc
    NSMutableArray *_messageQueue;	// 224 = 0xe0
    _Bool _reliableUDP;	// 232 = 0xe8
    _Bool _usingProfile;	// 233 = 0xe9
    NSObject<OS_dispatch_queue> *_networkProcQueue;	// 240 = 0xf0
    NSObject<OS_dispatch_source> *_readSource;	// 248 = 0xf8
    NSObject<OS_dispatch_source> *_timer;	// 256 = 0x100
    int _cleanupState;	// 264 = 0x108
    NSString *_postURL;	// 272 = 0x110
}

- (_Bool)uploadLogData:(id)arg1;	// IMP=0x0000000100013634
- (id)sendMessage:(id)arg1 timestamp:(const struct timeval *)arg2 method:(unsigned short)arg3 respCode:(unsigned short)arg4 eventID:(unsigned short)arg5;	// IMP=0x00000001000131b4
- (void)dealloc;	// IMP=0x000000010001313c
- (void)cleanup;	// IMP=0x0000000100013074
- (id)initWithName:(id)arg1 serverIP:(id)arg2 serverPort:(unsigned short)arg3 productFamily:(id)arg4;	// IMP=0x0000000100013038
- (id)initWithName:(id)arg1 profile:(id)arg2 serverIP:(id)arg3 serverPort:(unsigned short)arg4 productFamily:(id)arg5;	// IMP=0x0000000100012b84
- (id)initWithName:(id)arg1 profile:(id)arg2 productFamily:(id)arg3;	// IMP=0x0000000100012ae8
- (id)writeLocalLog:(struct tagReportingPacket *)arg1;	// IMP=0x0000000100014134
- (void)tryToSendMsg:(struct tagReportingPacket *)arg1 length:(unsigned short)arg2 eventNumber:(unsigned short)arg3;	// IMP=0x000000010001401c
- (id)sanitize:(id)arg1;	// IMP=0x0000000100013f90
- (id)descriptionForObject:(id)arg1;	// IMP=0x0000000100013f1c
- (void)processSocketRead;	// IMP=0x0000000100013d90
- (void)myPeriodicTask;	// IMP=0x0000000100013988
- (void)cleanupSources;	// IMP=0x000000010001392c
- (void)useReliableUDP;	// IMP=0x000000010001377c

@end

