//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, ReportingdAgent;
@protocol OS_dispatch_queue;

@interface RTCSelfReporter : NSObject
{
    NSMutableDictionary *_performanceData;	// 8 = 0x8
    NSMutableDictionary *_internalState;	// 16 = 0x10
    ReportingdAgent *_agent;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_reportQueue;	// 32 = 0x20
    int _numberOfPOSTFailures;	// 40 = 0x28
    int _numberOfStorebagDownloadFailures;	// 44 = 0x2c
    int _numberOfStorebagReadFailures;	// 48 = 0x30
    int _numberOfStorebagWriteFailures;	// 52 = 0x34
    int _numberOfStorebagValidationFailures;	// 56 = 0x38
    int _numberOfStorebagDownloadSuccess;	// 60 = 0x3c
    int _numberOfSuccessfulPOSTs;	// 64 = 0x40
    int _numberOfCoreDuetNRMWakeUps;	// 68 = 0x44
    int _numberOfCoreDuetPRTWakeUps;	// 72 = 0x48
    int _numberOfCoreDuetARTWakeUps;	// 76 = 0x4c
    int _bytesFailed;	// 80 = 0x50
    int _bytesSucceeded;	// 84 = 0x54
    int _numFailedDiskCacheWrite;	// 88 = 0x58
    int _numSuccessfulDiskCacheWrite;	// 92 = 0x5c
    int _numEventsNRM;	// 96 = 0x60
    int _numEventsPRT;	// 100 = 0x64
    int _numEventsART;	// 104 = 0x68
    int _numLostEventsNRM;	// 108 = 0x6c
    int _numLostEventsPRT;	// 112 = 0x70
    int _numLostEventsART;	// 116 = 0x74
    int _lostEventsNRM;	// 120 = 0x78
    int _lostEventsPRT;	// 124 = 0x7c
    int _lostEventsART;	// 128 = 0x80
}

- (void)reportSession:(id)arg1 type:(int)arg2;	// IMP=0x0000000100015ed0
- (void)sendFailureSummary:(id)arg1 forType:(int)arg2;	// IMP=0x0000000100015d5c
- (void)sendFailureSummary:(id)arg1;	// IMP=0x0000000100015d10
- (void)addFailure:(int)arg1 forPrefix:(id)arg2 withPayload:(id)arg3;	// IMP=0x0000000100015bb0
- (void)sendDailySummary;	// IMP=0x0000000100015aec
- (void)resetData;	// IMP=0x0000000100015acc
- (void)updatePerformanceData;	// IMP=0x00000001000157f0
- (void)updateFromDisk;	// IMP=0x000000010001559c
- (void)lostEventsForPrefix:(id)arg1 filepath:(id)arg2;	// IMP=0x0000000100015474
- (void)removeEventForPrefix:(id)arg1 filepath:(id)arg2;	// IMP=0x00000001000153a4
- (void)addEventForPrefix:(id)arg1 filepath:(id)arg2;	// IMP=0x00000001000152d4
- (void)successToWriteDiskCache;	// IMP=0x00000001000152c4
- (void)failedToWriteDiskCache;	// IMP=0x00000001000152b4
- (void)wokeupForPrefix:(id)arg1;	// IMP=0x000000010001521c
- (void)failedToWWriteStorebag;	// IMP=0x000000010001520c
- (void)failedToReadStorebag;	// IMP=0x00000001000151fc
- (void)failedStorebagValidation;	// IMP=0x00000001000151ec
- (void)successfulStorebagFetch;	// IMP=0x00000001000151dc
- (void)failedStorebagFetch;	// IMP=0x00000001000151cc
- (void)successfulPOST:(int)arg1;	// IMP=0x00000001000151b0
- (void)failedToPOST:(int)arg1;	// IMP=0x0000000100015194
- (void)readFromDisk;	// IMP=0x0000000100015048
- (void)writeToDisk;	// IMP=0x0000000100014e20
- (void)flushOverdue;	// IMP=0x0000000100014ce0
- (void)dealloc;	// IMP=0x0000000100014c84
- (id)initWithAgent:(id)arg1;	// IMP=0x0000000100014ad8

@end

