//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NSString;

@interface ACXGizmoAppState : NSObject <NSSecureCoding, NSCopying>
{
    NSString *_watchAppBundleID;	// 8 = 0x8
    NSString *_companionAppBundleID;	// 16 = 0x10
    unsigned long long _installStatus;	// 24 = 0x18
    NSString *_uniqueInstallID;	// 32 = 0x20
    NSString *_watchKitAppExecutableHash;	// 40 = 0x28
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100010af4
- (void).cxx_destruct;	// IMP=0x00000001000118c8
@property(copy, nonatomic) NSString *watchKitAppExecutableHash; // @synthesize watchKitAppExecutableHash=_watchKitAppExecutableHash;
@property(readonly, copy, nonatomic) NSString *uniqueInstallID; // @synthesize uniqueInstallID=_uniqueInstallID;
@property(nonatomic) unsigned long long installStatus; // @synthesize installStatus=_installStatus;
@property(copy, nonatomic) NSString *companionAppBundleID; // @synthesize companionAppBundleID=_companionAppBundleID;
@property(readonly, copy, nonatomic) NSString *watchAppBundleID; // @synthesize watchAppBundleID=_watchAppBundleID;
- (id)description;	// IMP=0x0000000100011834
- (void)regenerateUniqueInstallID;	// IMP=0x0000000100011698
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100010ff0
- (id)initWithWatchBundleID:(id)arg1 companionBundleID:(id)arg2;	// IMP=0x0000000100010f48
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0000000100010e3c
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100010c70
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100010afc

@end

