//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "MCSChange.h"

@class MCSMailboxOperation;

@interface MailMailboxChangeSet : MCSChange
{
    MCSMailboxOperation *_mailboxOperation;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x000000010003eef4
- (id)URLStrings;	// IMP=0x000000010003eeec
- (id)stores;	// IMP=0x000000010003eee4
- (id)accounts;	// IMP=0x000000010003ee30
- (id)mailboxParentForMove;	// IMP=0x000000010003ee18
- (id)mailboxToMoveOrRename;	// IMP=0x000000010003ee00
- (id)mailboxToRemove;	// IMP=0x000000010003ede8
- (id)modifiedMailboxName;	// IMP=0x000000010003edd0
- (unsigned long long)adjustUnreadCount:(unsigned long long)arg1 withCriterion:(id)arg2;	// IMP=0x000000010003edc8
- (id)copyChangeSetForFullPath:(id)arg1;	// IMP=0x000000010003edc0
- (id)description;	// IMP=0x000000010003ed0c
- (long long)localizedChangeDescriptionPriority;	// IMP=0x000000010003ed04
- (id)localizedChangeDescription;	// IMP=0x000000010003ecf8
- (id)localizedErrorTitle;	// IMP=0x000000010003ece0
- (id)localizedErrorDescription;	// IMP=0x000000010003ecc8
- (_Bool)revert;	// IMP=0x000000010003ec84
- (_Bool)commit;	// IMP=0x000000010003eb80
- (id)applyPendingChangeToObjects:(id)arg1;	// IMP=0x000000010003eb78
- (id)initWithOperation:(id)arg1;	// IMP=0x000000010003eac8

@end

