//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MFMailMessageLibrary, NSMapTable;

@interface MessageToMailboxUidCache : NSObject
{
    NSMapTable *_mailboxCache;	// 8 = 0x8
    MFMailMessageLibrary *_library;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x000000010005b424
- (id)debugDescription;	// IMP=0x000000010005b208
- (id)_mailboxWithMailboxLibraryID:(long long)arg1;	// IMP=0x000000010005b18c
- (unsigned long long)count;	// IMP=0x000000010005b17c
- (void)removeAllObjects;	// IMP=0x000000010005b16c
- (id)mailboxForMessageInfo:(id)arg1;	// IMP=0x000000010005af2c
- (id)mailboxForMessage:(id)arg1;	// IMP=0x000000010005ad78
- (id)init;	// IMP=0x000000010005acec
- (id)initWithLibrary:(id)arg1;	// IMP=0x000000010005ab40

@end

