//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MFMessageRule-Protocol.h"

@class MFMailMessageStore, NSString;

@interface MFBlockedSenderMessageRule : NSObject <MFMessageRule>
{
    MFMailMessageStore *_store;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010006457c
@property(retain, nonatomic) MFMailMessageStore *store; // @synthesize store=_store;
- (_Bool)shouldIncludeInNewMessagesSet;	// IMP=0x0000000100064560
- (void)performOperationOnMessages:(id)arg1 withMessageChangeManager:(id)arg2;	// IMP=0x0000000100064168
- (_Bool)canExecuteRuleOnMessage:(id)arg1;	// IMP=0x0000000100063f70

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

