//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <EmailDaemon/EDOutgoingMessageRepository.h>

@interface OutgoingMessageRepository_iOS : EDOutgoingMessageRepository
{
}

+ (id)log;	// IMP=0x00000001000d04d0
- (id)messagesForDocumentID:(id)arg1 mailboxID:(id)arg2;	// IMP=0x00000001000d1134
- (void)suspendDeliveryQueue;	// IMP=0x00000001000d106c
- (void)resumeDeliveryQueue;	// IMP=0x00000001000d0fa4
- (void)processAllQueuedMessages;	// IMP=0x00000001000d0ed0
- (void)outboxContainsMessageFromAccountObjectID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d0bc0
- (void)numberOfPendingMessagesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000d0b24
- (void)isProcessingWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000d0a88
- (id)deliverMessageSynchronously:(id)arg1 usingMailDrop:(_Bool)arg2;	// IMP=0x00000001000d05c0

@end

