//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "EMVIPManager-Protocol.h"

@class EAEmailAddressSet, NSLock, NSSet, NSString;
@protocol EMVIPManager, OS_dispatch_queue;

@interface VIPManager : NSObject <EMVIPManager>
{
    NSLock *_abPersonByVIPIdentifierLock;	// 8 = 0x8
    struct __CFDictionary *_abPersonByVIPIdentifier;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_queue;	// 24 = 0x18
    id <EMVIPManager> _backingManager;	// 32 = 0x20
}

+ (id)defaultInstance;	// IMP=0x00000001000dc67c
+ (void)setBackingManager:(id)arg1;	// IMP=0x00000001000dc5d0
+ (struct os_unfair_lock_s *)defaultInstanceLock;	// IMP=0x00000001000dc5c4
- (void).cxx_destruct;	// IMP=0x00000001000de118
@property(readonly, nonatomic) id <EMVIPManager> backingManager; // @synthesize backingManager=_backingManager;
- (id)allVIPEmailAddressesCriterion;	// IMP=0x00000001000de098
- (id)vipCriteria;	// IMP=0x00000001000dde5c
- (id)criterionForEmailAddresses:(id)arg1;	// IMP=0x00000001000ddbdc
- (const void *)existingPersonForVIP:(id)arg1 usingAddressBook:(void *)arg2;	// IMP=0x00000001000dd9d0
- (id)vipForEmailAddresses:(id)arg1 andDisplayNames:(id)arg2;	// IMP=0x00000001000dd5dc
- (id)sortedVIPs;	// IMP=0x00000001000dd42c
- (void)deleteVIPWithIdentifier:(id)arg1;	// IMP=0x00000001000dd2fc
- (void)saveVIP:(id)arg1;	// IMP=0x00000001000dd1cc
- (void)_vipsDidChange:(id)arg1;	// IMP=0x00000001000dcd2c
- (void)removeVIPsWithEmailAddresses:(id)arg1;	// IMP=0x00000001000dcc9c
- (void)removeVIPsWithIdentifiers:(id)arg1;	// IMP=0x00000001000dcc0c
- (void)saveVIPs:(id)arg1;	// IMP=0x00000001000dcb7c
- (_Bool)isVIPAddress:(id)arg1;	// IMP=0x00000001000dcae0
- (id)vipWithIdentifier:(id)arg1;	// IMP=0x00000001000dca3c
@property(readonly, copy, nonatomic) EAEmailAddressSet *allVIPEmailAddresses;
@property(readonly, copy, nonatomic) NSSet *allVIPs;
@property(readonly, nonatomic) _Bool hasVIPs;
- (id)initWithBackingManager:(id)arg1;	// IMP=0x00000001000dc7b4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

