//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AppInstallsDatabaseSession.h"

#import "SQLiteDatabaseTransaction-Protocol.h"

@class AppInstallsDatabaseChangeset, NSString, SQLiteConnection;

@interface AppInstallsDatabaseTransaction : AppInstallsDatabaseSession <SQLiteDatabaseTransaction>
{
    AppInstallsDatabaseChangeset *_changeset;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00000001001b9e3c
@property(readonly) AppInstallsDatabaseChangeset *changeset; // @synthesize changeset=_changeset;
- (id)_summaryEventForEntity:(id)arg1;	// IMP=0x00000001001b9c14
- (void)setCoordinator:(id)arg1 forInstallID:(long long)arg2;	// IMP=0x00000001001b9ad0
- (void)userInitiateInstallID:(long long)arg1;	// IMP=0x00000001001b9620
- (_Bool)updateInstalls:(id)arg1;	// IMP=0x00000001001b9324
- (void)setInstallPhase:(long long)arg1 forInstallID:(long long)arg2;	// IMP=0x00000001001b90e0
- (void)resumeInstallID:(long long)arg1;	// IMP=0x00000001001b8ec8
- (void)restartInstallID:(long long)arg1;	// IMP=0x00000001001b8e68
- (void)prioritizeInstallID:(long long)arg1;	// IMP=0x00000001001b8da0
- (void)pauseInstallID:(long long)arg1 withPhase:(long long)arg2 forReason:(long long)arg3;	// IMP=0x00000001001b897c
- (void)pauseInstallID:(long long)arg1;	// IMP=0x00000001001b8968
- (_Bool)importRemoteIntalls:(id)arg1;	// IMP=0x00000001001b8714
- (id)importInstalls:(id)arg1;	// IMP=0x00000001001b858c
- (CDStruct_912cb5d2)importInstall:(id)arg1 error:(id *)arg2;	// IMP=0x00000001001b7c6c
- (id)importInstall:(id)arg1;	// IMP=0x00000001001b7b6c
- (void)finishInstallID:(long long)arg1 withFinalPhase:(long long)arg2;	// IMP=0x00000001001b71f0
- (void)finishHardFailInstalls:(id)arg1;	// IMP=0x00000001001b6f40
- (void)failInstallID:(long long)arg1 withError:(id)arg2;	// IMP=0x00000001001b6b80
- (void)completeInstallID:(long long)arg1;	// IMP=0x00000001001b6ac8
- (id)initWithConnection:(id)arg1;	// IMP=0x00000001001b6a5c

// Remaining properties
@property(readonly) SQLiteConnection *connection;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

