//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSHashTable;

@interface PIDHashTable : NSObject
{
    NSHashTable *_hash;	// 8 = 0x8
}

+ (id)hashTable;	// IMP=0x0000000100173764
- (void).cxx_destruct;	// IMP=0x00000001001739a0
- (id)_initWithHashTable:(id)arg1;	// IMP=0x0000000100173928
- (id)description;	// IMP=0x0000000100173874
- (void)removePID:(long long)arg1;	// IMP=0x000000010017384c
- (_Bool)containsPID:(long long)arg1;	// IMP=0x000000010017381c
- (void)addPID:(long long)arg1;	// IMP=0x00000001001737f4

@end

