//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class NSMutableSet, NSString, NSXPCListener, XPCServiceCatalog;
@protocol OS_dispatch_queue;

@interface XPCServiceBroker : NSObject <NSXPCListenerDelegate>
{
    NSMutableSet *_activeClients;	// 8 = 0x8
    XPCServiceCatalog *_catalog;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 24 = 0x18
    NSXPCListener *_listener;	// 32 = 0x20
}

+ (id)newServerWithCatalog:(id)arg1 forMachServiceName:(id)arg2;	// IMP=0x000000010024cf18
- (void).cxx_destruct;	// IMP=0x000000010024d3c0
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x000000010024d0f0
- (id)initWithCatalog:(id)arg1 andListener:(id)arg2;	// IMP=0x000000010024cfbc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

