//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <OSAnalytics/OSAReport.h>

@class NSData, NSString;

@interface LegacyGasGuageReport : OSAReport
{
    NSString *_content;	// 48 = 0x30
    NSData *_ota_id;	// 56 = 0x38
}

- (int)streamContentAtLevel:(_Bool)arg1 withBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100005448
- (void)generateCustomLogAtLevel:(_Bool)arg1 withBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001000052a8
- (void)generateLogAtLevel:(_Bool)arg1 withBlock:(CDUnknownBlockType)arg2;	// IMP=0x000000010000529c
- (id)reportNamePrefix;	// IMP=0x0000000100005290
- (id)appleCareDetails;	// IMP=0x0000000100005280
- (id)problemType;	// IMP=0x0000000100005270
- (void)dealloc;	// IMP=0x0000000100005210
- (id)initWithTime:(double)arg1 forString:(id)arg2 withOTAID:(id)arg3;	// IMP=0x0000000100005174

@end

