//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NanoRoutePlanningStateManager, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface NanoRoutePlanningState : NSObject
{
    NSObject<OS_dispatch_queue> *_isolationQueue;	// 8 = 0x8
    long long _previousState;	// 16 = 0x10
    long long _nextState;	// 24 = 0x18
    long long _sessionState;	// 32 = 0x20
    double _timestampStarted;	// 40 = 0x28
    _Bool _active;	// 48 = 0x30
    id <NanoRoutePlanningStateManager> _manager;	// 56 = 0x38
}

+ (long long)requiredInitialStateForRequest:(id)arg1;	// IMP=0x000000010000e844
- (void).cxx_destruct;	// IMP=0x000000010000ef20
@property(nonatomic) __weak id <NanoRoutePlanningStateManager> manager; // @synthesize manager=_manager;
@property(readonly, nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
@property(readonly, nonatomic) long long sessionState;
- (void)resume;	// IMP=0x000000010000eee8
- (void)pause;	// IMP=0x000000010000eee4
- (void)setActive:(_Bool)arg1;	// IMP=0x000000010000ed2c
- (void)stop;	// IMP=0x000000010000ed28
- (void)start;	// IMP=0x000000010000ed24
- (void)leaveToState:(long long)arg1;	// IMP=0x000000010000eb00
- (void)enterToState:(long long)arg1 fromState:(long long)arg2;	// IMP=0x000000010000e8ec
- (id)initWithStateManager:(id)arg1 isolationQueue:(id)arg2;	// IMP=0x000000010000e84c

@end

