//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "MapsSuggestionsSourceDelegate-Protocol.h"

@class MapsSuggestionsRemoteSource, NSLock, NSMutableDictionary, NSString;
@protocol NMCSuggestionsProviderDelegate;

__attribute__((visibility("hidden")))
@interface NMCSuggestionsProvider : NSObject <MapsSuggestionsSourceDelegate>
{
    MapsSuggestionsRemoteSource *_connectionToDestinationd;	// 8 = 0x8
    NSMutableDictionary *_storage;	// 16 = 0x10
    unsigned long long _changeCount;	// 24 = 0x18
    NSLock *_lock;	// 32 = 0x20
    _Bool _hasOngoingRequest;	// 40 = 0x28
    id <NMCSuggestionsProviderDelegate> _delegate;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x0000000100035c7c
@property(nonatomic) __weak id <NMCSuggestionsProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)hintRefreshOfType:(long long)arg1;	// IMP=0x0000000100035c54
- (_Bool)detachSource:(id)arg1;	// IMP=0x0000000100035c4c
- (_Bool)attachSource:(id)arg1;	// IMP=0x0000000100035c44
- (unsigned long long)addOrUpdateSuggestionEntries:(id)arg1 source:(id)arg2;	// IMP=0x0000000100035a48
- (unsigned long long)_replaceEntriesFromSource:(id)arg1 withEntries:(id)arg2;	// IMP=0x0000000100035614
- (unsigned long long)_mergeInEntries:(id)arg1 fromSource:(id)arg2;	// IMP=0x00000001000351ec
- (id)_entriesForSource:(id)arg1 createIfNeeded:(_Bool)arg2;	// IMP=0x0000000100035158
- (_Bool)_isEntry:(id)arg1 probablyEqualToNewEntry:(id)arg2;	// IMP=0x0000000100034df0
- (void)_notifyDelegateOfChangesFinishingRequest:(_Bool)arg1;	// IMP=0x0000000100034ab4
- (void)_notifyDelegateOfChanges;	// IMP=0x0000000100034aa4
- (void)requestBlob;	// IMP=0x000000010003496c
- (void)_disconnectFromDestinationd;	// IMP=0x00000001000348c4
- (void)_connectToDestinationd;	// IMP=0x00000001000347fc
- (void)dealloc;	// IMP=0x0000000100034768
- (id)initWithDelegate:(id)arg1;	// IMP=0x00000001000346a0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

