//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "SYChangeSerializer-Protocol.h"
#import "SYSerialization-Protocol.h"

@class NSString;

@interface NARSYStoreSerializer : NSObject <SYSerialization, SYChangeSerializer>
{
}

- (id)decodeChangeData:(id)arg1 fromProtocolVersion:(long long)arg2 ofType:(long long)arg3;	// IMP=0x0000000100005e6c
- (id)changeFromData:(id)arg1 ofType:(long long)arg2;	// IMP=0x0000000100005e60
- (id)dataFromChange:(id)arg1;	// IMP=0x0000000100005e54
- (id)SYObjectWithData:(id)arg1;	// IMP=0x0000000100005d80
- (id)dataWithSYObject:(id)arg1;	// IMP=0x0000000100005ca8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

