//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol SDRuntimeFlagDelegate <NSObject>
@property(retain) NSDictionary *capOverride;
@property(retain) NSString *providedPIDorProcess;
@property _Bool isTestingMode;
@property _Bool screenShot;
@property _Bool shouldGetFeedbackData;
@property _Bool shouldPostProcess;
@property _Bool shouldRunIDSDump;
@property _Bool shouldRunOSLogArchive;
@property _Bool shouldRunLogGenerationTasks;
@property _Bool shouldRunLogCopyTasks;
@property _Bool shouldRunTimeSensitiveTasks;
@end

