//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;
@protocol OS_dispatch_group, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface SystemDiagnosticBT : NSObject
{
    _Bool _attachedToBTSession;	// 8 = 0x8
    _Bool _waitingToCaptureAirPodLogs;	// 9 = 0x9
    _Bool _waitingToCaptureExposureNotificationLogs;	// 10 = 0xa
    NSObject<OS_dispatch_group> *_remoteGroup;	// 16 = 0x10
    NSString *_accessoryLogs;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_bluetoothQueue;	// 32 = 0x20
    CDStruct_1f5d48d3 _callbackSessions;	// 40 = 0x28
    NSObject<OS_dispatch_group> *_exposureNotificationGroup;	// 48 = 0x30
    NSURL *_exposureNotificationDBURL;	// 56 = 0x38
}

+ (id)sharedInstance;	// IMP=0x0000000100001f1c
- (void).cxx_destruct;	// IMP=0x00000001000030b4
@property(retain, nonatomic) NSURL *exposureNotificationDBURL; // @synthesize exposureNotificationDBURL=_exposureNotificationDBURL;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *exposureNotificationGroup; // @synthesize exposureNotificationGroup=_exposureNotificationGroup;
@property _Bool waitingToCaptureExposureNotificationLogs; // @synthesize waitingToCaptureExposureNotificationLogs=_waitingToCaptureExposureNotificationLogs;
@property _Bool waitingToCaptureAirPodLogs; // @synthesize waitingToCaptureAirPodLogs=_waitingToCaptureAirPodLogs;
@property(nonatomic) _Bool attachedToBTSession; // @synthesize attachedToBTSession=_attachedToBTSession;
@property(nonatomic) CDStruct_1f5d48d3 callbackSessions; // @synthesize callbackSessions=_callbackSessions;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *bluetoothQueue; // @synthesize bluetoothQueue=_bluetoothQueue;
@property(retain, nonatomic) NSString *accessoryLogs; // @synthesize accessoryLogs=_accessoryLogs;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *remoteGroup; // @synthesize remoteGroup=_remoteGroup;
- (void)triggerAirPodLogsIfConnected;	// IMP=0x0000000100002da4
- (void)endAirPodSession;	// IMP=0x0000000100002d20
- (void)deregisterBTSessionIfDone;	// IMP=0x0000000100002cc8
- (void)deregisterBTSession;	// IMP=0x0000000100002c60
- (id)waitForAirPodLogsIfAvailableAndEndBTSession;	// IMP=0x0000000100002b1c
- (void)startBTSessionAndTriggerAirPodLogsIfConnected:(id)arg1;	// IMP=0x0000000100002980
- (void)triggerExposureNotificationLogs;	// IMP=0x00000001000026c4
- (id)waitForExposureNotificationLogsIfAvailable:(long long)arg1;	// IMP=0x0000000100002530
- (void)startBTSessionAndTriggerExposureNotificationLogs:(id)arg1;	// IMP=0x0000000100002304
- (void)startBTSession:(id)arg1;	// IMP=0x0000000100002154
- (id)init;	// IMP=0x0000000100001f88

@end

