//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "VCPClientHandler.h"

#import "VCPHomeKitAnalysisServerProtocol-Protocol.h"

@class NSMutableDictionary, NSObject, NSXPCConnection;
@protocol OS_dispatch_queue, VCPHomeKitAnalysisClientProtocol;

__attribute__((visibility("hidden")))
@interface VCPHomeKitAnalysisClientHandler : VCPClientHandler <VCPHomeKitAnalysisServerProtocol>
{
    NSXPCConnection *_connection;	// 8 = 0x8
    id <VCPHomeKitAnalysisClientProtocol> _clientProxy;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_managementQueue;	// 24 = 0x18
    NSMutableDictionary *_taskIDMapping;	// 32 = 0x20
}

+ (id)errorForStatus:(int)arg1;	// IMP=0x000000010002ada4
+ (id)clientHandlerWithXPCConnection:(id)arg1;	// IMP=0x000000010002ad30
- (void).cxx_destruct;	// IMP=0x000000010002c160
- (void)cancelAllRequests;	// IMP=0x000000010002bed4
- (void)cancelRequest:(int)arg1;	// IMP=0x000000010002bd10
- (void)requestAnalysis:(unsigned long long)arg1 ofFragmentSurface:(id)arg2 withRequestID:(int)arg3 properties:(id)arg4 andReply:(CDUnknownBlockType)arg5;	// IMP=0x000000010002b600
- (void)requestAnalysis:(unsigned long long)arg1 ofFragmentData:(id)arg2 withRequestID:(int)arg3 properties:(id)arg4 andReply:(CDUnknownBlockType)arg5;	// IMP=0x000000010002aed8
- (id)initWithXPCConnection:(id)arg1;	// IMP=0x000000010002a810
- (id)init;	// IMP=0x000000010002a7f8

@end

