//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDSServiceDelegate-Protocol.h"

@class IDSService, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface NBRemoteObject : NSObject <IDSServiceDelegate>
{
    NSMutableDictionary *_idsSendIDToCompletionHandler;	// 8 = 0x8
    NSMutableDictionary *_idsSendIDToResponseHandler;	// 16 = 0x10
    NSMutableDictionary *_idsSendIDToTimer;	// 24 = 0x18
    NSString *_serviceName;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_idsQueue;	// 40 = 0x28
    NSMutableDictionary *_idsRequestMessageTypeToSelector;	// 48 = 0x30
    NSObject<OS_dispatch_queue> *_clientQueue;	// 56 = 0x38
    id _delegate;	// 64 = 0x40
    IDSService *_service;	// 72 = 0x48
}

+ (_Bool)messagesShouldHaveValidSender;	// IMP=0x0000000100011678
- (void).cxx_destruct;	// IMP=0x0000000100014398
@property(readonly, nonatomic) IDSService *service; // @synthesize service=_service;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *clientQueue; // @synthesize clientQueue=_clientQueue;
- (void)service:(id)arg1 didSwitchActivePairedDevice:(id)arg2 acknowledgementBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000142a8
- (void)service:(id)arg1 account:(id)arg2 incomingResourceAtURL:(id)arg3 metadata:(id)arg4 fromID:(id)arg5 context:(id)arg6;	// IMP=0x0000000100013c8c
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5;	// IMP=0x00000001000138ec
- (void)_queueSendMessage:(id)arg1 orPath:(id)arg2 type:(unsigned short)arg3 requestUUID:(id)arg4 withTimeout:(id)arg5 withResponseTimeout:(id)arg6 withDescription:(id)arg7 onlyOneFor:(id)arg8 didSend:(CDUnknownBlockType)arg9 andResponse:(CDUnknownBlockType)arg10;	// IMP=0x0000000100012f7c
- (void)_messageResponseTimeout:(id)arg1;	// IMP=0x0000000100012d4c
- (void)_sendMessage:(id)arg1 type:(unsigned short)arg2 requestUUID:(id)arg3 withTimeout:(id)arg4 withResponseTimeout:(id)arg5 withDescription:(id)arg6 onlyOneFor:(id)arg7 didSend:(CDUnknownBlockType)arg8 andResponse:(CDUnknownBlockType)arg9;	// IMP=0x0000000100012a20
- (void)sendResponse:(id)arg1 type:(unsigned short)arg2 requestUUID:(id)arg3 withTimeout:(id)arg4 withDescription:(id)arg5 onlyOneFor:(id)arg6 didSend:(CDUnknownBlockType)arg7;	// IMP=0x000000010001293c
- (void)sendResponse:(id)arg1 type:(unsigned short)arg2 withRequest:(id)arg3 withTimeout:(id)arg4 withDescription:(id)arg5 onlyOneFor:(id)arg6 didSend:(CDUnknownBlockType)arg7;	// IMP=0x00000001000127c0
- (void)sendFileRequest:(id)arg1 type:(unsigned short)arg2 withTimeout:(id)arg3 withResponseTimeout:(id)arg4 withDescription:(id)arg5 onlyOneFor:(id)arg6 didSend:(CDUnknownBlockType)arg7 andResponse:(CDUnknownBlockType)arg8;	// IMP=0x00000001000124e0
- (void)sendRequest:(id)arg1 type:(unsigned short)arg2 withTimeout:(id)arg3 withResponseTimeout:(id)arg4 withDescription:(id)arg5 onlyOneFor:(id)arg6 didSend:(CDUnknownBlockType)arg7 andResponse:(CDUnknownBlockType)arg8;	// IMP=0x00000001000123e0
- (void)sendRequest:(id)arg1 type:(unsigned short)arg2 withTimeout:(id)arg3 withDescription:(id)arg4 didSend:(CDUnknownBlockType)arg5;	// IMP=0x0000000100012338
- (void)sendRequest:(id)arg1 type:(unsigned short)arg2 withTimeout:(id)arg3 didSend:(CDUnknownBlockType)arg4;	// IMP=0x00000001000122b8
- (void)sendRequest:(id)arg1 type:(unsigned short)arg2 didSend:(CDUnknownBlockType)arg3;	// IMP=0x000000010001225c
- (void)sendRequest:(id)arg1 type:(unsigned short)arg2;	// IMP=0x000000010001224c
- (void)registerProtobufHandlers;	// IMP=0x0000000100012248
- (void)setProtobufAction:(SEL)arg1 forIncomingResponsesOfType:(unsigned short)arg2;	// IMP=0x00000001000121d4
- (void)setProtobufAction:(SEL)arg1 forIncomingRequestsOfType:(unsigned short)arg2;	// IMP=0x000000010001216c
- (void)_storeProtobufAction:(SEL)arg1 messageType:(unsigned short)arg2 messageSendType:(long long)arg3;	// IMP=0x000000010001209c
- (void)handleIncomingMessage:(id)arg1;	// IMP=0x0000000100011680
- (void)invalidate;	// IMP=0x0000000100010e54
- (id)initWithServiceName:(id)arg1 andDelegate:(id)arg2 andClientQueue:(id)arg3;	// IMP=0x0000000100010b6c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

