//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BTAVRCP_VFSFolder.h"

@class NSArray;

@interface BTAVRCP_MyMusicFolder : BTAVRCP_VFSFolder
{
    NSArray *_activeCategories;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100012ccc
@property(retain, nonatomic) NSArray *activeCategories; // @synthesize activeCategories=_activeCategories;
- (unsigned char)playItemWithUid:(unsigned long long)arg1;	// IMP=0x0000000100012c10
- (id)replyAttributesForUid:(unsigned long long)arg1 attributeIDs:(id)arg2;	// IMP=0x0000000100012b6c
- (id)replyItemAtIndex:(unsigned long long)arg1 attributeIDs:(id)arg2;	// IMP=0x0000000100012a0c
- (unsigned char)createFolderWithUid:(unsigned long long)arg1 folder:(id *)arg2;	// IMP=0x00000001000126d0
- (unsigned long long)childrenCount;	// IMP=0x0000000100012684
- (id)baseQuery;	// IMP=0x0000000100012670
- (unsigned char)folderTypeForUid:(unsigned long long)arg1;	// IMP=0x0000000100012640
- (id)folderNameForUid:(unsigned long long)arg1;	// IMP=0x0000000100012510
- (void)refreshActiveCategories;	// IMP=0x00000001000122dc
- (void)dealloc;	// IMP=0x0000000100012268
- (id)initWithName:(id)arg1 uid:(unsigned long long)arg2;	// IMP=0x0000000100012184

@end

