//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "UAActivityReplay.h"

#import "NSStreamDelegate-Protocol.h"

@class NSInputStream, NSMutableData, NSOutputStream, NSString, NSUUID;

@interface UANetworkReplayController : UAActivityReplay <NSStreamDelegate>
{
    NSInputStream *_inputStream;	// 8 = 0x8
    NSOutputStream *_outputStream;	// 16 = 0x10
    NSMutableData *_readBuffer;	// 24 = 0x18
    NSMutableData *_writeBuffer;	// 32 = 0x20
    NSString *_peerName;	// 40 = 0x28
    NSUUID *_peerUUID;	// 48 = 0x30
}

+ (_Bool)createConnection:(id)arg1 host:(id)arg2 port:(long long)arg3;	// IMP=0x0000000100079090
- (void).cxx_destruct;	// IMP=0x000000010007928c
@property(copy) NSUUID *peerUUID; // @synthesize peerUUID=_peerUUID;
@property(copy) NSString *peerName; // @synthesize peerName=_peerName;
@property(retain) NSMutableData *writeBuffer; // @synthesize writeBuffer=_writeBuffer;
@property(retain) NSMutableData *readBuffer; // @synthesize readBuffer=_readBuffer;
@property(retain) NSOutputStream *outputStream; // @synthesize outputStream=_outputStream;
@property(retain) NSInputStream *inputStream; // @synthesize inputStream=_inputStream;
- (_Bool)terminate;	// IMP=0x0000000100078e90
- (id)statusString;	// IMP=0x0000000100078d24
- (_Bool)sendResponse:(id)arg1;	// IMP=0x0000000100078a2c
- (_Bool)processCommand:(id)arg1;	// IMP=0x0000000100077f38
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;	// IMP=0x0000000100076ef8
- (id)initWithManager:(id)arg1 service:(id)arg2;	// IMP=0x0000000100076c40
- (id)initWithManager:(id)arg1 inputStream:(id)arg2 outputStream:(id)arg3 name:(id)arg4;	// IMP=0x0000000100076994

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

