//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@class NSData, NSError, UASharedPasteboardInfo;

@interface UASharedPasteboardInfoWrapper : NSObject <NSSecureCoding>
{
    UASharedPasteboardInfo *_pbinfo;	// 8 = 0x8
    NSData *_extraData;	// 16 = 0x10
    long long _extraDataType;	// 24 = 0x18
    NSError *_error;	// 32 = 0x20
    long long _protocolVersion;	// 40 = 0x28
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100080804
- (void).cxx_destruct;	// IMP=0x0000000100080c48
@property long long protocolVersion; // @synthesize protocolVersion=_protocolVersion;
@property(retain) NSError *error; // @synthesize error=_error;
@property long long extraDataType; // @synthesize extraDataType=_extraDataType;
@property(retain) NSData *extraData; // @synthesize extraData=_extraData;
@property(retain) UASharedPasteboardInfo *pbinfo; // @synthesize pbinfo=_pbinfo;
- (id)description;	// IMP=0x0000000100080af8
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001000809a4
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010008080c

@end

