//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLGeomagneticModelProviderProtocol-Protocol.h"

@class NSString;

@interface CLGeomagneticModelProviderLocationdAdapter : CLNotifierServiceAdapter <CLGeomagneticModelProviderProtocol>
{
}

+ (id)getSilo;	// IMP=0x00000001006d4338
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001006d4314
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0000000100cea47c
- (void)fetchGeomagneticModelData:(CDUnknownBlockType)arg1;	// IMP=0x00000001006d4560
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x00000001006d4524
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001006d44e0
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x00000001006d44ac
- (struct CLGeomagneticModelProvider *)adaptee;	// IMP=0x00000001006d4470
- (void)endService;	// IMP=0x00000001006d444c
- (void)beginService;	// IMP=0x00000001006d43f4
- (id)init;	// IMP=0x00000001006d43b0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

