//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <LocationSupport/CLIntersiloService.h>

#import "CLSimulationControllerProtocol-Protocol.h"
#import "CLSimulationXPCServerInterface-Protocol.h"
#import "NSXPCListenerDelegate-Protocol.h"

@class NSString, NSXPCConnection, NSXPCListener;

@interface CLSimulationControllerAdapter : CLIntersiloService <CLSimulationControllerProtocol, NSXPCListenerDelegate, CLSimulationXPCServerInterface>
{
    NSXPCListener *_listener;	// 8 = 0x8
    NSXPCConnection *_connection;	// 16 = 0x10
    struct CLSimulationController *_controller;	// 24 = 0x18
}

+ (id)getSilo;	// IMP=0x00000001005ee208
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x00000001005ee1e4
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0000000100ce44f8
@property(nonatomic) struct CLSimulationController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSXPCListener *listener; // @synthesize listener=_listener;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00000001005ef910
- (void)simulateBeaconWithProximityUUID:(id)arg1 major:(long long)arg2 minor:(long long)arg3 eventType:(unsigned char)arg4;	// IMP=0x00000001005ef790
- (void)simulateFenceWithBundleID:(id)arg1 andFenceID:(id)arg2 eventType:(unsigned char)arg3 atLocation:(id)arg4;	// IMP=0x00000001005ef600
- (void)getFencesForBundleID:(id)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x00000001005ef47c
- (void)simulateSignificantLocationChange:(id)arg1;	// IMP=0x00000001005ef330
- (void)simulateVisit:(id)arg1;	// IMP=0x00000001005ef208
- (void)setLocationTravellingSpeed:(double)arg1;	// IMP=0x00000001005ef0e0
- (void)setLocationInterval:(double)arg1;	// IMP=0x00000001005eefb8
- (void)setIntermediateLocationDistance:(double)arg1;	// IMP=0x00000001005eee90
- (void)setLocationRepeatBehavior:(unsigned char)arg1;	// IMP=0x00000001005eed8c
- (void)setLocationDeliveryBehavior:(unsigned char)arg1;	// IMP=0x00000001005eec48
- (void)clearSimulatedLocations;	// IMP=0x00000001005eec34
- (void)appendSimulatedLocations:(id)arg1;	// IMP=0x00000001005ee9cc
- (void)setSimulationScenario:(id)arg1;	// IMP=0x00000001005ee964
- (void)startLocationSimulation;	// IMP=0x00000001005ee760
- (void)stopLocationSimulation;	// IMP=0x00000001005ee550
- (void)shutdown;	// IMP=0x00000001005ee54c
- (void)endService;	// IMP=0x00000001005ee520
- (void)beginService;	// IMP=0x00000001005ee2c4
- (id)init;	// IMP=0x00000001005ee280

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

