//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CLNotifierServiceAdapter.h"

#import "CLSkiNotifierProtocol-Protocol.h"

@class NSString;

@interface CLSkiNotifierAdapter : CLNotifierServiceAdapter <CLSkiNotifierProtocol>
{
}

+ (id)getSilo;	// IMP=0x000000010072a5c4
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x000000010072a5a0
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0000000100cec03c
+ (_Bool)isSupported;	// IMP=0x000000010072a914
- (void)queryUsingRecord:(struct CLSkiEntry)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010072a7ec
- (_Bool)syncgetDoSync:(CDUnknownBlockType)arg1;	// IMP=0x000000010072a7b0
- (void)doAsync:(CDUnknownBlockType)arg1 withReply:(CDUnknownBlockType)arg2;	// IMP=0x000000010072a76c
- (void)doAsync:(CDUnknownBlockType)arg1;	// IMP=0x000000010072a738
- (struct CLSkiNotifier *)adaptee;	// IMP=0x000000010072a6fc
- (void)endService;	// IMP=0x000000010072a6d8
- (void)beginService;	// IMP=0x000000010072a680
- (id)init;	// IMP=0x000000010072a63c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

