//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSSet.h>

@interface NSSet (CKDLogging)
- (id)logIDs;	// IMP=0x000000010000b5e8
- (id)logKeys;	// IMP=0x000000010000b5d4
- (_Bool)isEmpty;	// IMP=0x000000010001073c
- (_Bool)containsElementsNotIn:(id)arg1;	// IMP=0x0000000100010614
- (id)shortDescription;	// IMP=0x0000000100010344
- (id)sortedElementsTruncated:(unsigned long long)arg1 JoinedByString:(id)arg2;	// IMP=0x0000000100010424
- (id)sortedElementsJoinedByString:(id)arg1;	// IMP=0x0000000100010410
@end

