//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface IndoorServiceTransactionManager : NSObject
{
    NSMutableDictionary *_activeTransactions;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100368080
- (_Bool)closeTransactionWithDescription:(id)arg1;	// IMP=0x0000000100367b14
- (_Bool)isLastOpenTransactionWithDescription:(id)arg1;	// IMP=0x0000000100367a90
- (unsigned long long)numOpenTransactions;	// IMP=0x0000000100367910
- (_Bool)hasOpenTransactionWithDescription:(id)arg1;	// IMP=0x0000000100367884
- (void)openTransactionWithDescription:(id)arg1;	// IMP=0x00000001003675e0
- (_Bool)hasAnyOpenTransaction;	// IMP=0x00000001003675bc
- (void)dealloc;	// IMP=0x000000010036753c
- (id)init;	// IMP=0x00000001003674b8

@end

