//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BMMiningTaskDelegate-Protocol.h"

@class BMMiningTask, NSString;
@protocol OS_dispatch_source, OS_xpc_object;

@interface BMDaemon : NSObject <BMMiningTaskDelegate>
{
    NSObject<OS_xpc_object> *_activity;	// 8 = 0x8
    NSObject<OS_dispatch_source> *_deferralTimer;	// 16 = 0x10
    BMMiningTask *_task;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000032b0
@property(retain, nonatomic) BMMiningTask *task; // @synthesize task=_task;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *deferralTimer; // @synthesize deferralTimer=_deferralTimer;
@property(retain, nonatomic) NSObject<OS_xpc_object> *activity; // @synthesize activity=_activity;
- (void)run;	// IMP=0x00000001000031f8
- (void)miningTaskDidFinish:(id)arg1;	// IMP=0x0000000100002d6c
- (void)miningTask:(id)arg1 didExtractRules:(id)arg2;	// IMP=0x0000000100002c6c
- (void)periodicallyCheckDeferral;	// IMP=0x0000000100002a30
- (void)registerXPCActivity;	// IMP=0x0000000100002858
- (id)init;	// IMP=0x0000000100002774

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

