//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "IDSServiceDelegate-Protocol.h"

@class IDSService, NSString;
@protocol OS_dispatch_queue, STLocalIDSTransportDelegate, STLocalIDSTransportReachabilityDelegate;

@interface STLocalIDSTransport : NSObject <IDSServiceDelegate>
{
    id <STLocalIDSTransportDelegate> _delegate;	// 8 = 0x8
    id <STLocalIDSTransportReachabilityDelegate> _reachabilityDelegate;	// 16 = 0x10
    IDSService *_service;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_serviceQueue;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010002655c
@property(readonly) NSObject<OS_dispatch_queue> *serviceQueue; // @synthesize serviceQueue=_serviceQueue;
@property(readonly) IDSService *service; // @synthesize service=_service;
@property __weak id <STLocalIDSTransportReachabilityDelegate> reachabilityDelegate; // @synthesize reachabilityDelegate=_reachabilityDelegate;
@property __weak id <STLocalIDSTransportDelegate> delegate; // @synthesize delegate=_delegate;
- (void)service:(id)arg1 account:(id)arg2 incomingData:(id)arg3 fromID:(id)arg4 context:(id)arg5;	// IMP=0x0000000100026270
- (void)sendPayload:(id)arg1;	// IMP=0x0000000100025e14
- (id)init;	// IMP=0x0000000100025cd0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

