//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "BSDescriptionProviding-Protocol.h"

@class NSSet, NSString;
@protocol BKHIDEventSenderInfo;

@interface _BKPointerEventRecord : NSObject <BSDescriptionProviding>
{
    _Bool _didTrackPointerMovement;	// 8 = 0x8
    _Bool _didTrackButtonDown;	// 9 = 0x9
    _Bool _trackingPointerMovement;	// 10 = 0xa
    _Bool _trackingButtonDown;	// 11 = 0xb
    id <BKHIDEventSenderInfo> _senderInfo;	// 16 = 0x10
    NSSet *_destinations;	// 24 = 0x18
    double _destinationCaptureTime;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000769a0
@property(nonatomic) _Bool trackingButtonDown; // @synthesize trackingButtonDown=_trackingButtonDown;
@property(nonatomic) _Bool trackingPointerMovement; // @synthesize trackingPointerMovement=_trackingPointerMovement;
@property(nonatomic) double destinationCaptureTime; // @synthesize destinationCaptureTime=_destinationCaptureTime;
@property(retain, nonatomic) NSSet *destinations; // @synthesize destinations=_destinations;
@property(retain, nonatomic) id <BKHIDEventSenderInfo> senderInfo; // @synthesize senderInfo=_senderInfo;
- (id)succinctDescriptionBuilder;	// IMP=0x0000000100076884
- (id)succinctDescription;	// IMP=0x0000000100076830
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x00000001000767dc
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x00000001000766e8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

