//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BKAccelerometerClient.h"

@interface BKAccelerometerClientBKSAccelerometer : BKAccelerometerClient
{
}

- (void)handleOrientationEvent:(long long)arg1 orientationLocked:(_Bool)arg2;	// IMP=0x0000000100046898
- (void)handleAccelerometerEventWithTimestamp:(double)arg1 x:(float)arg2 y:(float)arg3 z:(float)arg4 samplingInterval:(double)arg5;	// IMP=0x0000000100046764
- (void)_queue_invalidate;	// IMP=0x0000000100046730
- (_Bool)_deathBySendRight;	// IMP=0x0000000100046728
- (_Bool)_deathByPid;	// IMP=0x0000000100046720

@end

