//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableOrderedSet, NSString;

@interface BKNamespaceNode : NSObject
{
    NSString *_name;	// 8 = 0x8
    NSObject *_object;	// 16 = 0x10
    NSMutableOrderedSet *_subnodes;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010008a5d0
@property(retain, nonatomic) NSMutableOrderedSet *subnodes; // @synthesize subnodes=_subnodes;
@property(retain, nonatomic) NSObject *object; // @synthesize object=_object;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void)_dumpNodeTree:(id)arg1 level:(long long)arg2;	// IMP=0x000000010008a344
- (id)_enumerateKeyPathNodesByComponent:(id)arg1 options:(long long)arg2 ifFound:(CDUnknownBlockType)arg3 ifMissing:(CDUnknownBlockType)arg4;	// IMP=0x0000000100089fb0
- (void)_enumerateNodesWithOptions:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100089e48
- (void)dumpNodeTree;	// IMP=0x0000000100089e34
- (id)enumerateKeyPathNodes:(id)arg1 options:(long long)arg2 ifFound:(CDUnknownBlockType)arg3 ifMissing:(CDUnknownBlockType)arg4;	// IMP=0x0000000100089d60
- (void)enumerateNodesWithOptions:(long long)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0000000100089d54
- (id)setObject:(id)arg1 atKeyPath:(id)arg2;	// IMP=0x0000000100089cd4
- (id)objectAtKeyPath:(id)arg1;	// IMP=0x0000000100089c80
- (id)nodeAtKeyPath:(id)arg1;	// IMP=0x0000000100089c68
- (void)removeNodeAtKeyPath:(id)arg1;	// IMP=0x0000000100089b20
- (_Bool)isEqual:(id)arg1;	// IMP=0x0000000100089a00
- (unsigned long long)hash;	// IMP=0x00000001000899f0
- (id)description;	// IMP=0x00000001000899e0
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;	// IMP=0x00000001000898a0
- (id)descriptionWithMultilinePrefix:(id)arg1;	// IMP=0x000000010008984c
- (id)succinctDescriptionBuilder;	// IMP=0x0000000100089834
- (id)succinctDescription;	// IMP=0x00000001000897e0
- (id)init;	// IMP=0x000000010008977c

@end

