//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSXPCInterface.h>

@interface NSXPCInterface (MapsBrokerExtras)
+ (id)_maps_mapsConnectionBrokerEndpointProviderInterface;	// IMP=0x0000000100016928
+ (id)_maps_mapsConnectionBrokerEndpointRecorderInterface;	// IMP=0x000000010001690c
+ (id)_maps_mapsConnectionBrokerEndpointConsumerInterface;	// IMP=0x00000001000168f0
+ (id)_maps_mapsConnectionBrokerEndpointSourceInterface;	// IMP=0x00000001000168d4
+ (id)_maps_mapsPushDaemonXPCClientInterface;	// IMP=0x0000000100020ec4
+ (id)_maps_mapsPushDaemonXPCInterface;	// IMP=0x0000000100020d80
@end

