//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIControl.h>

@class CNAvatarViewController, NSLayoutConstraint, UILabel, UIView;

@interface PHCarPlayPhoneCallViewCell : UIControl
{
    NSLayoutConstraint *_containerSpecificLeftConstraint;	// 8 = 0x8
    NSLayoutConstraint *_containerSpecificRightConstraint;	// 16 = 0x10
    CNAvatarViewController *_avatarViewController;	// 24 = 0x18
    UILabel *_mainLabel;	// 32 = 0x20
    UILabel *_subtitleLabel;	// 40 = 0x28
    UIView *_avatarContentView;	// 48 = 0x30
    NSLayoutConstraint *_topMainLabelConstraint;	// 56 = 0x38
    NSLayoutConstraint *_topAvatarConstraint;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0000000100023484
@property(retain, nonatomic) NSLayoutConstraint *topAvatarConstraint; // @synthesize topAvatarConstraint=_topAvatarConstraint;
@property(retain, nonatomic) NSLayoutConstraint *topMainLabelConstraint; // @synthesize topMainLabelConstraint=_topMainLabelConstraint;
@property(readonly, nonatomic) UIView *avatarContentView; // @synthesize avatarContentView=_avatarContentView;
@property(retain) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain) UILabel *mainLabel; // @synthesize mainLabel=_mainLabel;
@property(retain, nonatomic) CNAvatarViewController *avatarViewController; // @synthesize avatarViewController=_avatarViewController;
@property(retain) NSLayoutConstraint *containerSpecificRightConstraint; // @synthesize containerSpecificRightConstraint=_containerSpecificRightConstraint;
@property(retain) NSLayoutConstraint *containerSpecificLeftConstraint; // @synthesize containerSpecificLeftConstraint=_containerSpecificLeftConstraint;
- (_Bool)canBecomeFocused;	// IMP=0x00000001000233a4
- (void)setTitle:(id)arg1 subtitle:(id)arg2 animated:(_Bool)arg3;	// IMP=0x0000000100022f10
- (void)setDimmed:(_Bool)arg1 animated:(_Bool)arg2;	// IMP=0x0000000100022e1c
- (void)setEnabled:(_Bool)arg1;	// IMP=0x0000000100022dc4
- (void)layoutSubviews;	// IMP=0x0000000100022ca4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0000000100022244

@end

