//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface PHHIDEventMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    struct __IOHIDEventSystemClient *_HIDEventSystemClient;	// 16 = 0x10
}

+ (id)HIDEventMonitor;	// IMP=0x0000000100070770
- (void).cxx_destruct;	// IMP=0x0000000100070fb8
@property(nonatomic) struct __IOHIDEventSystemClient *HIDEventSystemClient; // @synthesize HIDEventSystemClient=_HIDEventSystemClient;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
- (id)stringFromIOHIDUsagePage:(long long)arg1;	// IMP=0x0000000100070f74
- (id)stringFromIOHIDUsage:(long long)arg1;	// IMP=0x0000000100070e04
- (void)handleKeyboardEvent:(struct __IOHIDEvent *)arg1;	// IMP=0x0000000100070c90
- (void)stop;	// IMP=0x0000000100070b8c
- (void)start;	// IMP=0x0000000100070910
- (void)dealloc;	// IMP=0x0000000100070818
- (id)init;	// IMP=0x000000010007078c

@end

