//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (PHInCallUIUtilities)
- (double)yOriginForCenterOfSuperview;	// IMP=0x0000000100013774
- (double)xOriginForCenterOfSuperview;	// IMP=0x000000010001361c
- (struct CGAffineTransform)transformToAbutToEdge:(unsigned long long)arg1 ofView:(id)arg2;	// IMP=0x00000001000133e0
@property(nonatomic) long long action;
@end

