//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "DADevice-Protocol.h"
#import "DADeviceConnectionDelegate-Protocol.h"
#import "DATestQueueDelegate-Protocol.h"

@class DAAdapterAccessory, DADeviceConnectionLocal, DADeviceState, DATestQueue, DKDiagnosticManager, DKReportManager, NSString;

@interface DADeviceAccessory : NSObject <DADeviceConnectionDelegate, DATestQueueDelegate, DADevice>
{
    DAAdapterAccessory *_accessory;	// 8 = 0x8
    DADeviceConnectionLocal *_connection;	// 16 = 0x10
    DKDiagnosticManager *_diagnosticsManager;	// 24 = 0x18
    DKReportManager *_reportManager;	// 32 = 0x20
    DATestQueue *_testQueue;	// 40 = 0x28
    DADeviceState *_state;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x000000010001f5d4
@property(retain, nonatomic) DADeviceState *state; // @synthesize state=_state;
@property(retain, nonatomic) DATestQueue *testQueue; // @synthesize testQueue=_testQueue;
@property(retain, nonatomic) DKReportManager *reportManager; // @synthesize reportManager=_reportManager;
@property(retain, nonatomic) DKDiagnosticManager *diagnosticsManager; // @synthesize diagnosticsManager=_diagnosticsManager;
@property(retain, nonatomic) DADeviceConnectionLocal *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) DAAdapterAccessory *accessory; // @synthesize accessory=_accessory;
- (id)_marketingName;	// IMP=0x000000010001f508
- (id)_productClass;	// IMP=0x000000010001f4f8
- (id)_serialNumber;	// IMP=0x000000010001f4a4
- (id)_deviceImageName;	// IMP=0x000000010001f420
- (void)_profileWithCommand:(id)arg1;	// IMP=0x000000010001ee14
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;	// IMP=0x000000010001ec98
@property(readonly) unsigned long long hash;
- (void)deviceConnection:(id)arg1 didRecieveCommand:(id)arg2;	// IMP=0x000000010001ebd4
- (void)executeTestWithTestAttributes:(id)arg1 parameters:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x000000010001eb00
- (void)cancelTestWithCommand:(id)arg1;	// IMP=0x000000010001ea68
- (void)startTestWithCommand:(id)arg1;	// IMP=0x000000010001e894
- (void)end;	// IMP=0x000000010001e7d4
- (void)resumeTests;	// IMP=0x000000010001e6f4
- (void)suspendTests;	// IMP=0x000000010001e5e4
- (void)idle;	// IMP=0x000000010001e5a4
- (void)start;	// IMP=0x000000010001e564
- (void)connect;	// IMP=0x000000010001e560
@property(readonly, nonatomic, getter=isLocal) _Bool local;
- (id)initWithAccessory:(id)arg1;	// IMP=0x000000010001e264
- (id)init;	// IMP=0x000000010001e254

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

