//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSXPCConnection, PKEntitlementWhitelist;

@interface NPKPassLibraryFilter : NSObject
{
    PKEntitlementWhitelist *_whitelist;	// 8 = 0x8
    NSXPCConnection *_connection;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0000000100034bd8
@property(retain) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(retain) PKEntitlementWhitelist *whitelist; // @synthesize whitelist=_whitelist;
- (_Bool)_entitledForPassTypeID:(id)arg1 teamID:(id)arg2 associatedPassTypeIdentifiers:(id)arg3;	// IMP=0x0000000100034a2c
- (_Bool)_entitledForObject:(id)arg1;	// IMP=0x0000000100034878
- (id)entitlementFilteredPasses:(id)arg1;	// IMP=0x00000001000347a4
@property(readonly) _Bool allowsSilentAdd;
- (id)filterPassIfNeeded:(id)arg1;	// IMP=0x00000001000346f4
- (_Bool)allowAccessToPass:(id)arg1;	// IMP=0x00000001000346e8
- (id)initWithConnection:(id)arg1;	// IMP=0x0000000100034630

@end

