//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "AMSDTask.h"

@interface AMSDRefreshMultiUserTask : AMSDTask
{
}

+ (_Bool)_shouldSkipCloudKitOperationsForHomes:(id)arg1;	// IMP=0x000000010002ead8
+ (void)_saveRelevantSettingsForHomeIfNecessary:(id)arg1;	// IMP=0x000000010002dfd4
+ (_Bool)_reconcileiTunesAccountsForUsersInHome:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002d444
+ (_Bool)_reconcileiTunesAccountsForHomes:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002d030
+ (void)_mergeHomeUserIdentifiersAndRecordZoneNames;	// IMP=0x000000010002cc80
+ (_Bool)_isErrorFatal:(id)arg1;	// IMP=0x000000010002cc14
+ (_Bool)_isCloudKitAvailable;	// IMP=0x000000010002cb94
+ (_Bool)_deleteRecordZonesIfNecessaryUsingHomes:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002beb0
+ (_Bool)_createMultiUserTokenForHomeIfNecessary:(id)arg1 error:(id *)arg2;	// IMP=0x000000010002b66c
+ (void)_cacheSuccessfulRefreshForHomes:(id)arg1;	// IMP=0x000000010002b508
- (id)performTask;	// IMP=0x000000010002a1e0

@end

