//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE, NSString;

@interface _TtC6FindMy17FMAddToListButton : UIView
{
    MISSING_TYPE *titleLabel;	// 8 = 0x8
    MISSING_TYPE *iconView;	// 16 = 0x10
    MISSING_TYPE *isTouched;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00000001000b8d38
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000001000b8d70
- (void)layoutSubviews;	// IMP=0x00000001000b8c7c
- (void)traitCollectionDidChange:(id)arg1;	// IMP=0x00000001000b8c30
- (void)setEnabled:(_Bool)arg1;	// IMP=0x00000001000b8bc8
@property(nonatomic, copy) NSString *accessibilityLabel;
@property(nonatomic) unsigned long long accessibilityTraits;
@property(nonatomic) _Bool isAccessibilityElement;
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000b8338

@end

