//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CDMComposerContext, CDMComposerTask;
@protocol CDMCommand;

@protocol CDMComposerTaskDelegate <NSObject>
- (void)composerTask:(CDMComposerTask *)arg1 finishedWithContext:(CDMComposerContext *)arg2;
- (void)composerTask:(CDMComposerTask *)arg1 updatedWithContext:(CDMComposerContext *)arg2;
- (void)composerTask:(CDMComposerTask *)arg1 request:(id <CDMCommand>)arg2 withCallback:(void (^)(id <CDMCommand>, NSError *))arg3;
@end

