//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CDMSyncSource.h"

@class NSObject;
@protocol OS_dispatch_queue;

@interface CDMSyncContactSource : CDMSyncSource
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0000000100009ebc
- (void)fetchInBackground:(id)arg1;	// IMP=0x00000001000097dc
- (void)_contactsChanged:(id)arg1;	// IMP=0x00000001000096b8
- (void)_stopObserving;	// IMP=0x0000000100009668
- (void)_startObserving;	// IMP=0x00000001000095a4
- (void)cleanup;	// IMP=0x0000000100009598
- (void)setup;	// IMP=0x00000001000094a4

@end

