//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CDMBaseService.h"

@class CDMDateTimeSpanMatcher, CDMFullUtteranceSpanMatcher, CDMMachineUtteranceSpanMatcher, CDMRegexSpanMatcher, CDMSpanMatchConfig, CDMUserVocabSpanMatcher, CDMVocFileSpanMatcher, NSObject;
@protocol OS_dispatch_queue;

@interface CDMSpanMatchService : CDMBaseService
{
    NSObject<OS_dispatch_queue> *_queue;	// 16 = 0x10
    CDMSpanMatchConfig *_config;	// 24 = 0x18
    CDMUserVocabSpanMatcher *_userVocabMatcher;	// 32 = 0x20
    CDMVocFileSpanMatcher *_vocFileMatcher;	// 40 = 0x28
    CDMDateTimeSpanMatcher *_dateTimeMatcher;	// 48 = 0x30
    CDMFullUtteranceSpanMatcher *_fullUtteranceMatcher;	// 56 = 0x38
    CDMRegexSpanMatcher *_regexMatcherExperimental;	// 64 = 0x40
    CDMMachineUtteranceSpanMatcher *_machineUtteranceMatcherExperimental;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x000000010002cb08
- (void)_handleUpdatedUserData:(id)arg1;	// IMP=0x000000010002ca44
- (void)_handleSpanMatchRequest:(id)arg1 withCallback:(CDUnknownBlockType)arg2;	// IMP=0x000000010002c3a8
- (void)_handleSetupRequest:(id)arg1 withCallback:(CDUnknownBlockType)arg2;	// IMP=0x000000010002ba54
- (void)handleCommand:(id)arg1 withCallback:(CDUnknownBlockType)arg2;	// IMP=0x000000010002b7bc
- (id)supportedCommands;	// IMP=0x000000010002b6c8
- (id)initWithConfig:(id)arg1;	// IMP=0x000000010002b668

@end

