//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class VNFaceObservation;

@interface AXMTTrackingFace : NSObject
{
    VNFaceObservation *_faceObservation;	// 8 = 0x8
    double _normalizedBoundsArea;	// 16 = 0x10
    struct CGPoint _normalizedBoundsCenter;	// 24 = 0x18
    struct CGPoint __normalizedLeftEyePosition;	// 40 = 0x28
    struct CGPoint __normalizedRightEyePosition;	// 56 = 0x38
    struct CGPoint __normalizedMouthPosition;	// 72 = 0x48
    struct CGRect _normalizedBounds;	// 88 = 0x58
}

+ (id)trackingFaceFromFaceObservation:(id)arg1 withinImageSize:(struct CGSize)arg2;	// IMP=0x00000001000118bc
- (void).cxx_destruct;	// IMP=0x0000000100011c80
@property(nonatomic) struct CGPoint _normalizedMouthPosition; // @synthesize _normalizedMouthPosition=__normalizedMouthPosition;
@property(nonatomic) struct CGPoint _normalizedRightEyePosition; // @synthesize _normalizedRightEyePosition=__normalizedRightEyePosition;
@property(nonatomic) struct CGPoint _normalizedLeftEyePosition; // @synthesize _normalizedLeftEyePosition=__normalizedLeftEyePosition;
@property(nonatomic) double normalizedBoundsArea; // @synthesize normalizedBoundsArea=_normalizedBoundsArea;
@property(nonatomic) struct CGPoint normalizedBoundsCenter; // @synthesize normalizedBoundsCenter=_normalizedBoundsCenter;
@property(nonatomic) struct CGRect normalizedBounds; // @synthesize normalizedBounds=_normalizedBounds;
@property(retain, nonatomic) VNFaceObservation *faceObservation; // @synthesize faceObservation=_faceObservation;
- (_Bool)isLikelyTheSameFaceAs:(id)arg1;	// IMP=0x0000000100011ad8

@end

