//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BCMutableCloudData.h"

#import "BCSecureUserDatum-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class CKRecord, NSData, NSDate, NSString;
@protocol BCCloudDataPrivacyDelegate;

@interface BCMutableSecureUserDatum : BCMutableCloudData <BCSecureUserDatum, NSSecureCoding>
{
    NSString *_key;	// 8 = 0x8
    NSString *_value;	// 16 = 0x10
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010004388c
- (void).cxx_destruct;	// IMP=0x0000000100043a40
@property(copy, nonatomic) NSString *value; // @synthesize value=_value;
@property(readonly, copy, nonatomic) NSString *key; // @synthesize key=_key;
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100043938
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100043894
- (id)configuredRecordFromAttributes;	// IMP=0x00000001000437fc
- (id)zoneName;	// IMP=0x00000001000437ec
- (id)identifier;	// IMP=0x00000001000437e0
- (id)recordType;	// IMP=0x00000001000437d4
@property(readonly, copy) NSString *description;
- (id)initWithRecord:(id)arg1;	// IMP=0x0000000100043600
- (id)initWithCloudData:(id)arg1;	// IMP=0x000000010004348c
- (id)initWithKey:(id)arg1;	// IMP=0x00000001000433c0

// Remaining properties
@property(readonly, copy, nonatomic) NSData *ckSystemFields;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) _Bool deletedFlag;
@property(readonly, nonatomic) long long editGeneration;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSDate *modificationDate;
@property(nonatomic) __weak id <BCCloudDataPrivacyDelegate> privacyDelegate;
@property(readonly) Class superclass;
@property(readonly, nonatomic) long long syncGeneration;
@property(readonly, copy, nonatomic) CKRecord *systemFields;

@end

