//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSXPCListenerDelegate-Protocol.h"

@class NSString;
@protocol OS_dispatch_queue;

@interface CKDiscretionaryDaemon : NSObject <NSXPCListenerDelegate>
{
    NSObject<OS_dispatch_queue> *_serialQueue;	// 8 = 0x8
    Class _schedulerClass;	// 16 = 0x10
}

+ (void)setupSandbox;	// IMP=0x0000000100002848
- (void).cxx_destruct;	// IMP=0x0000000100002954
@property(nonatomic) Class schedulerClass; // @synthesize schedulerClass=_schedulerClass;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serialQueue; // @synthesize serialQueue=_serialQueue;
- (id)initWithSchedulerClass:(Class)arg1;	// IMP=0x0000000100002898
- (id)initWithInSyncBubble:(_Bool)arg1;	// IMP=0x000000010000284c
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00000001000042e4

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

