//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSManagedObjectContext, NSManagedObjectID;

@interface RMCommandEngine : NSObject
{
    _Bool _executingCommands;	// 8 = 0x8
    NSManagedObjectID *_managementSourceObjectID;	// 16 = 0x10
    NSManagedObjectContext *_context;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x000000010001e4e0
@property(nonatomic) _Bool executingCommands; // @synthesize executingCommands=_executingCommands;
@property(readonly, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) NSManagedObjectID *managementSourceObjectID; // @synthesize managementSourceObjectID=_managementSourceObjectID;
- (_Bool)_handleResultForCommand:(id)arg1 status:(short)arg2 result:(id)arg3 reasons:(id)arg4 unknownPayloadKeys:(id)arg5 error:(id)arg6 outError:(id *)arg7;	// IMP=0x000000010001de00
- (id)_fetchCommand;	// IMP=0x000000010001dc3c
- (_Bool)_executeCommand:(id)arg1 managementChannel:(id)arg2 error:(id *)arg3;	// IMP=0x000000010001d67c
- (void)_processCommand:(CDUnknownBlockType)arg1;	// IMP=0x000000010001cce8
- (void)syncWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x000000010001cbe0
- (id)initWithManagementSourceObjectID:(id)arg1 context:(id)arg2;	// IMP=0x000000010001cb3c

@end

