//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSArray, NSDate, NSDictionary, RMCommandPayload;

@interface RMCommandPayloadState : NSManagedObject
{
}

- (void)markPending;	// IMP=0x000000010001fb90
- (void)markFailedWithError:(id)arg1 reasons:(id)arg2;	// IMP=0x000000010001f894
- (void)markExecutedWithResult:(id)arg1 reasons:(id)arg2 unknownPayloadKeys:(id)arg3;	// IMP=0x000000010001f570
- (void)markQueued;	// IMP=0x000000010001f508

// Remaining properties
@property(retain, nonatomic) RMCommandPayload *command; // @dynamic command;
@property(copy, nonatomic) NSDate *modifiedDate; // @dynamic modifiedDate;
@property(copy, nonatomic) NSArray *reasons; // @dynamic reasons;
@property(copy, nonatomic) NSDictionary *result; // @dynamic result;
@property(nonatomic) short status; // @dynamic status;

@end

