//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class WebSheetRemoteAlertPresentationViewController;

@interface WebSheetViewController : UIViewController
{
    WebSheetRemoteAlertPresentationViewController *_remotePresentationController;	// 8 = 0x8
}

@property(nonatomic) WebSheetRemoteAlertPresentationViewController *remotePresentationController; // @synthesize remotePresentationController=_remotePresentationController;
- (id)webSheetView;	// IMP=0x000000010000939c
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x0000000100009394
- (_Bool)shouldAutorotate;	// IMP=0x000000010000938c
- (void)dismissViewController;	// IMP=0x0000000100009364
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000092fc
- (void)loadView;	// IMP=0x000000010000924c

@end

