//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "REMCDObject.h"

@class NSString, NSUUID, REMCDList;

@interface REMCDSharee : REMCDObject
{
}

+ (_Bool)shouldSyncToCloud;	// IMP=0x000000010004dbf0
+ (id)fetchRequest;	// IMP=0x0000000100056dec
- (_Bool)isConnectedToAccountObject:(id)arg1;	// IMP=0x00000001000550bc

// Remaining properties
@property(nonatomic) short accessLevel; // @dynamic accessLevel;
@property(copy, nonatomic) NSString *address; // @dynamic address;
@property(copy, nonatomic) NSString *displayName; // @dynamic displayName;
@property(copy, nonatomic) NSString *firstName; // @dynamic firstName;
@property(copy, nonatomic) NSString *lastName; // @dynamic lastName;
@property(retain, nonatomic) REMCDList *list; // @dynamic list;
@property(copy, nonatomic) NSString *middleName; // @dynamic middleName;
@property(copy, nonatomic) NSString *namePrefix; // @dynamic namePrefix;
@property(copy, nonatomic) NSString *nameSuffix; // @dynamic nameSuffix;
@property(copy, nonatomic) NSString *nickname; // @dynamic nickname;
@property(copy, nonatomic) NSUUID *owningListIdentifier; // @dynamic owningListIdentifier;
@property(nonatomic) short status; // @dynamic status;

@end

