//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ReminderKit/REMStoreInvocation.h>

@interface REMComplicationDataViewFetchModelInvocation : REMStoreInvocation
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100357094
- (id)init;	// IMP=0x00000001003570ac
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001003570a0
- (void)encodeWithCoder:(id)arg1;	// IMP=0x000000010035709c

@end

