//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <ReminderKit/REMStoreSwiftInvocation.h>

@interface REMRemindersListDataView_SearchInvocation : REMStoreSwiftInvocation
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x000000010031bdc8
- (id)initWithCoder:(id)arg1;	// IMP=0x000000010032ac3c
- (id)initWithFetchResultTokenToDiffAgainst:(id)arg1;	// IMP=0x000000010032a950

@end

