//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FMFBaseCmd.h"

@class NSArray, NSDictionary, NSSet;

@interface FMFStatusCommand : FMFBaseCmd
{
    NSDictionary *_following;	// 16 = 0x10
    NSDictionary *_follower;	// 24 = 0x18
    NSArray *_offerPending;	// 32 = 0x20
    NSArray *_invitePending;	// 40 = 0x28
    NSSet *_handles;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x000000010003b0fc
@property(retain, nonatomic) NSSet *handles; // @synthesize handles=_handles;
@property(copy, nonatomic) NSArray *invitePending; // @synthesize invitePending=_invitePending;
@property(copy, nonatomic) NSArray *offerPending; // @synthesize offerPending=_offerPending;
@property(copy, nonatomic) NSDictionary *follower; // @synthesize follower=_follower;
@property(copy, nonatomic) NSDictionary *following; // @synthesize following=_following;
- (void)processCommandResponse:(id)arg1;	// IMP=0x000000010003ad28
- (id)jsonBodyDictionary;	// IMP=0x000000010003ab18
- (id)pathSuffix;	// IMP=0x000000010003ab0c
- (id)initWithClientSession:(id)arg1 handles:(id)arg2 groupId:(id)arg3;	// IMP=0x000000010003aa24

@end

