//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "SetupChoiceController.h"

#import "BuddyCloudConfigWebAuthDelegate-Protocol.h"

@class BFFLinkLabelFooterView, BuddyCloudConfigAboutConfigurationContainerController, BuddyCloudConfigController, NSError, NSString, SetupChoice, UIButton, UINavigationController, UITableViewCell;

@interface BuddyCloudConfigDisclosureViewController : SetupChoiceController <BuddyCloudConfigWebAuthDelegate>
{
    _Bool _isMandatory;	// 8 = 0x8
    BuddyCloudConfigController *_configController;	// 16 = 0x10
    NSError *_lastRetrievalError;	// 24 = 0x18
    SetupChoice *_acceptChoice;	// 32 = 0x20
    SetupChoice *_skipChoice;	// 40 = 0x28
    UINavigationController *_aboutController;	// 48 = 0x30
    BuddyCloudConfigAboutConfigurationContainerController *_aboutConfigurationContainerController;	// 56 = 0x38
    UIButton *_leaveRemoteManagementButton;	// 64 = 0x40
    UIButton *_aboutRemoteManagementButton;	// 72 = 0x48
    UITableViewCell *_aboutRemoteManagementCell;	// 80 = 0x50
    BFFLinkLabelFooterView *_aboutRemoteManagementContentView;	// 88 = 0x58
}

+ (id)cloudConfigSkipKey;	// IMP=0x00000001000f261c
- (void).cxx_destruct;	// IMP=0x00000001000f6fe8
@property(retain, nonatomic) BFFLinkLabelFooterView *aboutRemoteManagementContentView; // @synthesize aboutRemoteManagementContentView=_aboutRemoteManagementContentView;
@property(retain, nonatomic) UITableViewCell *aboutRemoteManagementCell; // @synthesize aboutRemoteManagementCell=_aboutRemoteManagementCell;
@property(retain, nonatomic) UIButton *aboutRemoteManagementButton; // @synthesize aboutRemoteManagementButton=_aboutRemoteManagementButton;
@property(retain, nonatomic) UIButton *leaveRemoteManagementButton; // @synthesize leaveRemoteManagementButton=_leaveRemoteManagementButton;
@property(retain, nonatomic) BuddyCloudConfigAboutConfigurationContainerController *aboutConfigurationContainerController; // @synthesize aboutConfigurationContainerController=_aboutConfigurationContainerController;
@property(retain, nonatomic) UINavigationController *aboutController; // @synthesize aboutController=_aboutController;
@property(nonatomic) _Bool isMandatory; // @synthesize isMandatory=_isMandatory;
@property(retain, nonatomic) SetupChoice *skipChoice; // @synthesize skipChoice=_skipChoice;
@property(retain, nonatomic) SetupChoice *acceptChoice; // @synthesize acceptChoice=_acceptChoice;
@property(retain, nonatomic) NSError *lastRetrievalError; // @synthesize lastRetrievalError=_lastRetrievalError;
@property(nonatomic) __weak BuddyCloudConfigController *configController; // @synthesize configController=_configController;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000f6d4c
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00000001000f6c6c
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00000001000f6c34
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;	// IMP=0x00000001000f6ac0
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;	// IMP=0x00000001000f69a0
- (void)showAboutConfiguration;	// IMP=0x00000001000f67d0
- (void)controllerDone;	// IMP=0x00000001000f6574
- (void)recievedProfile:(id)arg1;	// IMP=0x00000001000f63e4
- (void)webAuthCanceled:(id)arg1;	// IMP=0x00000001000f61e4
- (id)_machineInfo;	// IMP=0x00000001000f6188
- (void)_retrieveEnterpriseConfigurationFromWebURL:(id)arg1 withAnchorCerts:(id)arg2;	// IMP=0x00000001000f6054
- (void)_retrieveEnterpriseConfigurationForManagementVersion2;	// IMP=0x00000001000f5b68
- (void)_retrieveEnterpriseConfigurationForManagementVersion1;	// IMP=0x00000001000f52dc
- (void)_retrieveEnterpriseConfiguration;	// IMP=0x00000001000f515c
- (void)viewDidLayoutSubviews;	// IMP=0x00000001000f4e74
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00000001000f4d64
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00000001000f4d10
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00000001000f4c74
- (id)_remoteManagementText;	// IMP=0x00000001000f4954
- (void)_leaveRemoteManagementAndErase;	// IMP=0x00000001000f4498
- (void)_showEraseDeviceAlert;	// IMP=0x00000001000f4224
- (void)showLeaveRemoteManagementAlert;	// IMP=0x00000001000f3fb0
- (void)_presentEraseAlertWithTitle:(id)arg1 message:(id)arg2 eraseHandler:(CDUnknownBlockType)arg3;	// IMP=0x00000001000f3d5c
- (void)_initializeViews;	// IMP=0x00000001000f3b5c
- (void)_setupForCloudConfigurationState;	// IMP=0x00000001000f27c4
- (id)init;	// IMP=0x00000001000f2624

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

