//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "BFFPasscodeInputViewDelegate-Protocol.h"

@class DevicePINController, NSString, NSTimer, UILabel;
@protocol BuddyPasscodeEntryDelegate;

@interface BuddyPasscodeEntryController : UIViewController <BFFPasscodeInputViewDelegate>
{
    DevicePINController *_pinController;	// 8 = 0x8
    UILabel *_statusLabel;	// 16 = 0x10
    NSTimer *_statusTimer;	// 24 = 0x18
    _Bool _numeric;	// 32 = 0x20
    unsigned long long _numericLength;	// 40 = 0x28
    id <BuddyPasscodeEntryDelegate> _delegate;	// 48 = 0x30
    NSString *_titleText;	// 56 = 0x38
    NSString *_instructions;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x00000001000125f8
@property(copy, nonatomic) NSString *instructions; // @synthesize instructions=_instructions;
@property(copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(nonatomic) __weak id <BuddyPasscodeEntryDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long numericLength; // @synthesize numericLength=_numericLength;
@property(nonatomic, getter=isNumeric) _Bool numeric; // @synthesize numeric=_numeric;
- (void)configurePasscodeTypeUsingAnimations:(_Bool)arg1;	// IMP=0x0000000100012404
- (void)clear;	// IMP=0x000000010001239c
- (void)passcodeInput:(id)arg1 enteredPasscode:(id)arg2;	// IMP=0x0000000100012268
- (void)passcodeInput:(id)arg1 willChangeContents:(id)arg2;	// IMP=0x00000001000121c0
- (void)updateStatusMessage;	// IMP=0x0000000100011df4
- (void)nextButtonPressed;	// IMP=0x0000000100011d5c
- (void)_finishedWithPasscode:(id)arg1;	// IMP=0x0000000100011cb4
- (void)viewDidLayoutSubviews;	// IMP=0x0000000100011a48
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00000001000119f8
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x0000000100011964
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0000000100011824
- (void)viewDidLoad;	// IMP=0x00000001000117c0
- (void)_setupFirstEntry;	// IMP=0x0000000100011534
- (_Bool)usesSimplePasscodeEntry;	// IMP=0x00000001000114d0
- (id)passcodeView;	// IMP=0x000000010001149c
- (void)dealloc;	// IMP=0x000000010001140c
- (void)loadView;	// IMP=0x000000010001118c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

