//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MCProfileConnection, NSDictionary;

@interface BuddyCloudConfigManager : NSObject
{
    MCProfileConnection *_profileConnection;	// 8 = 0x8
    NSDictionary *_cloudConfigurationDetails;	// 16 = 0x10
}

+ (id)sharedManager;	// IMP=0x00000001000cbbd4
- (void).cxx_destruct;	// IMP=0x00000001000cc074
- (_Bool)isMultiUser;	// IMP=0x00000001000cbfb8
- (_Bool)cloudConfigWantsToSkipControllerClass:(Class)arg1;	// IMP=0x00000001000cbee0
- (void)cloudConfigMayHaveChanged;	// IMP=0x00000001000cbe68
@property(readonly, nonatomic) _Bool hasCloudConfiguration;
@property(copy, nonatomic) NSDictionary *cloudConfigurationDetails;
- (void)_skipTCPanesIfNecessary;	// IMP=0x00000001000cbc40
- (id)profileConnection;	// IMP=0x00000001000cbb80
- (void)_setProfileConnection:(id)arg1;	// IMP=0x00000001000cbb74

@end

