//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ATConnectionDelegate-Protocol.h"
#import "BFFFlowItem-Protocol.h"

@class ATConnection, NSString;
@protocol BFFFlowItemDelegate;

@interface RestoreFromComputerController : UIViewController <BFFFlowItem, ATConnectionDelegate>
{
    id <BFFFlowItemDelegate> _delegate;	// 8 = 0x8
    ATConnection *_airTrafficConnection;	// 16 = 0x10
}

+ (id)cloudConfigSkipKey;	// IMP=0x000000010005e2e4
- (void).cxx_destruct;	// IMP=0x000000010005ea24
- (void)_showConnectedToiTunesUsingAnimations:(_Bool)arg1;	// IMP=0x000000010005e96c
- (void)_showConnectToiTunesUsingAnimations:(_Bool)arg1;	// IMP=0x000000010005e8b4
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;	// IMP=0x000000010005e794
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x000000010005e718
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x000000010005e69c
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x000000010005e5b4
- (void)dealloc;	// IMP=0x000000010005e558
- (void)connectionWasInterrupted:(id)arg1;	// IMP=0x000000010005e530
- (void)connection:(id)arg1 updatedProgress:(id)arg2;	// IMP=0x000000010005e434
- (void)setDelegate:(id)arg1;	// IMP=0x000000010005e420
- (void)loadView;	// IMP=0x000000010005e394
- (id)init;	// IMP=0x000000010005e2ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

