//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class NRDLDKeys, NSData, NSDate, NSString, NSUUID;

@interface NRDLocalDevice : NSObject <NSCopying, NSSecureCoding>
{
    _Bool _isRegistered;	// 8 = 0x8
    _Bool _isEnabled;	// 9 = 0x9
    _Bool _hasConfirmedClassDKeys;	// 10 = 0xa
    _Bool _hasConfirmedClassCKeys;	// 11 = 0xb
    _Bool _hasConfirmedClassAKeys;	// 12 = 0xc
    _Bool _usesSPPLink;	// 13 = 0xd
    _Bool _wasInitiallySetupUsingIDSPairing;	// 14 = 0xe
    _Bool _lastSeenAlwaysOnWiFiSupported;	// 15 = 0xf
    _Bool _isEmptyPairing;	// 16 = 0x10
    _Bool _hasSavedClassCKeysInKeychain;	// 17 = 0x11
    _Bool _hasSavedClassAKeysInKeychain;	// 18 = 0x12
    unsigned short _lastSeenInnerLinkVersionHBO;	// 20 = 0x14
    NSUUID *_nrUUID;	// 24 = 0x18
    NSUUID *_bluetoothUUID;	// 32 = 0x20
    NRDLDKeys *_classDKeys;	// 40 = 0x28
    NRDLDKeys *_classCKeys;	// 48 = 0x30
    NSData *_receivedProxyNotifyPayload;	// 56 = 0x38
    NSData *_outOfBandKey;	// 64 = 0x40
    NSData *_bluetoothMACAddress;	// 72 = 0x48
    NSString *_lastSeenName;	// 80 = 0x50
    NSString *_lastSeenBuildVersion;	// 88 = 0x58
    long long _pairingProtocolVersion;	// 96 = 0x60
    NSDate *_dateCreated;	// 104 = 0x68
    NSDate *_dateRegistered;	// 112 = 0x70
    NSDate *_dateEnabled;	// 120 = 0x78
    NRDLDKeys *_classAKeys;	// 128 = 0x80
    NSData *_localInnerIPv6AddressBytesClassD;	// 136 = 0x88
    NSData *_remoteInnerIPv6AddressBytesClassD;	// 144 = 0x90
    NSData *_localInnerIPv6AddressBytesClassC;	// 152 = 0x98
    NSData *_remoteInnerIPv6AddressBytesClassC;	// 160 = 0xa0
}

+ (_Bool)updateRemoteClassCInnerAddressBytes:(struct in6_addr *)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b8e90
+ (_Bool)updateRemoteClassDInnerAddressBytes:(struct in6_addr *)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b8b20
+ (_Bool)updateLocalClassCInnerAddressBytes:(struct in6_addr *)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b87b0
+ (_Bool)updateLocalClassDInnerAddressBytes:(struct in6_addr *)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b8440
+ (void)writeSockAddrBytes:(struct sockaddr_in6 *)arg1 forEndpoint:(id)arg2;	// IMP=0x00000001000b80ac
+ (id)createTerminusPrefixEndpoint;	// IMP=0x00000001000b800c
+ (id)createNewRemoteClassDAddrData;	// IMP=0x00000001000b7f8c
+ (id)createNewLocalClassDAddrData;	// IMP=0x00000001000b7d98
+ (void)generateNewRandomAddrBytes:(struct in6_addr *)arg1;	// IMP=0x00000001000b7aac
+ (id)createEndpointFromAddrData:(id)arg1 portString:(id)arg2;	// IMP=0x00000001000b7850
+ (void)updateReceivedProxyNotifyPayload:(id)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b760c
+ (void)updateLastSeenAlwaysOnWiFiSupported:(_Bool)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b744c
+ (void)updateLastSeenBuildVersion:(id)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b7208
+ (void)updateLastSeenName:(id)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b6fc4
+ (void)updateLastSeenInnerLinkVersionHBO:(unsigned short)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b6e08
+ (void)ingestRemoteClassAKeysEncryptedWithIDS:(id)arg1 nrUUID:(id)arg2 deviceCompletionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b6ab8
+ (void)ingestRemoteClassCKeysEncryptedWithIDS:(id)arg1 nrUUID:(id)arg2 deviceCompletionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b6768
+ (void)ingestRemoteClassDKeysEncryptedWithIDS:(id)arg1 nrUUID:(id)arg2 deviceCompletionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b62ac
+ (void)ingestRemoteClassAKeys:(id)arg1 nrUUID:(id)arg2 deviceCompletionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b5f80
+ (void)ingestRemoteClassCKeys:(id)arg1 nrUUID:(id)arg2 deviceCompletionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b5c54
+ (void)ingestRemoteClassDKeys:(id)arg1 nrUUID:(id)arg2 deviceCompletionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b5530
+ (void)queryPairingFromIDSKeysForNRUUID:(id)arg1 minDataProtectionClass:(unsigned char)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b53e4
+ (void)queryPairingKeysForNRUUID:(id)arg1 minDataProtectionClass:(unsigned char)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000b4798
+ (_Bool)hasEnabledSPPDevice;	// IMP=0x00000001000b45e0
+ (id)copySPPMACAddressForNRUUID:(id)arg1;	// IMP=0x00000001000b4538
+ (id)copyLocalDeviceForSPPMACAddress:(id)arg1;	// IMP=0x00000001000b42ec
+ (_Bool)isEnabledSPPDeviceForMACAddress:(id)arg1;	// IMP=0x00000001000b40b0
+ (id)copyEnabledSPPBluetoothMACAddresses;	// IMP=0x00000001000b3ec0
+ (id)copyEnabledSPPNRUUIDs;	// IMP=0x00000001000b3cfc
+ (id)copyBestTestingNRUUID;	// IMP=0x00000001000b3b58
+ (_Bool)hasEnabledBluetoothDevice;	// IMP=0x00000001000b39a0
+ (id)copyEnabledBluetoothUUIDs;	// IMP=0x00000001000b37b0
+ (id)copyEnabledAndCompletedPairingNRUUIDs;	// IMP=0x00000001000b3604
+ (id)copyEnabledNRUUIDs;	// IMP=0x00000001000b3458
+ (_Bool)hasEnabledDevice;	// IMP=0x00000001000b32cc
+ (id)copyDeviceListString;	// IMP=0x00000001000b30d0
+ (void)disableDeviceWithNRUUID:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b2de4
+ (void)enableDeviceWithNRUUID:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b2af8
+ (void)unregisterAllDevicesWithCompletionBlock:(CDUnknownBlockType)arg1;	// IMP=0x00000001000b2768
+ (void)unregisterDeviceWithNRUUID:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00000001000b22a0
+ (void)reportRegistrationFailureCode:(long long)arg1 errorDescription:(id)arg2 forNRUUID:(id)arg3;	// IMP=0x00000001000b1e04
+ (void)confirmKeysForClass:(unsigned char)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b17f8
+ (void)registerDeviceWithNRUUID:(id)arg1 pairingProtocolVersion:(long long)arg2 wasInitiallySetupUsingIDSPairing:(_Bool)arg3 outOfBandKey:(id)arg4 pairWithSPPLink:(_Bool)arg5 bluetoothMACAddress:(id)arg6 completionBlock:(CDUnknownBlockType)arg7;	// IMP=0x00000001000b1034
+ (void)removeAnalyticsForNRUUID:(id)arg1;	// IMP=0x00000001000b0fc8
+ (id)getAnalyticsForNRUUID:(id)arg1;	// IMP=0x00000001000b0f64
+ (void)addAnalyticsForNRUUID:(id)arg1 nrUUID:(id)arg2;	// IMP=0x00000001000b0ed4
+ (id)copyNRUUIDForBluetoothUUID:(id)arg1;	// IMP=0x00000001000b0e48
+ (id)copyLocalDeviceForBluetoothUUID:(id)arg1;	// IMP=0x00000001000b0aa4
+ (id)copyLocalDeviceForNRUUID:(id)arg1 shouldCreate:(_Bool)arg2;	// IMP=0x00000001000b08f4
+ (id)copyLocalDeviceForNRUUID:(id)arg1;	// IMP=0x00000001000b0828
+ (id)newLocalDeviceWithRandomNRUUID;	// IMP=0x00000001000b06e4
+ (_Bool)supportsSecureCoding;	// IMP=0x00000001000b06dc
+ (id)copyStatusString;	// IMP=0x00000001000b04ac
+ (void)saveAllDevicesToDiskWithClassA;	// IMP=0x00000001000b045c
+ (void)saveAllDevicesToDisk;	// IMP=0x00000001000afeb4
+ (void)saveClassAKeysWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000afb48
+ (void)loadClassAKeys;	// IMP=0x00000001000af868
+ (void)initializeLocalDeviceDatabaseIfNecessary;	// IMP=0x00000001000af1d4
- (void).cxx_destruct;	// IMP=0x00000001000ae654
@property(retain, nonatomic) NSData *remoteInnerIPv6AddressBytesClassC; // @synthesize remoteInnerIPv6AddressBytesClassC=_remoteInnerIPv6AddressBytesClassC;
@property(retain, nonatomic) NSData *localInnerIPv6AddressBytesClassC; // @synthesize localInnerIPv6AddressBytesClassC=_localInnerIPv6AddressBytesClassC;
@property(retain, nonatomic) NSData *remoteInnerIPv6AddressBytesClassD; // @synthesize remoteInnerIPv6AddressBytesClassD=_remoteInnerIPv6AddressBytesClassD;
@property(retain, nonatomic) NSData *localInnerIPv6AddressBytesClassD; // @synthesize localInnerIPv6AddressBytesClassD=_localInnerIPv6AddressBytesClassD;
@property(nonatomic) _Bool hasSavedClassAKeysInKeychain; // @synthesize hasSavedClassAKeysInKeychain=_hasSavedClassAKeysInKeychain;
@property(nonatomic) _Bool hasSavedClassCKeysInKeychain; // @synthesize hasSavedClassCKeysInKeychain=_hasSavedClassCKeysInKeychain;
@property(retain, nonatomic) NRDLDKeys *classAKeys; // @synthesize classAKeys=_classAKeys;
@property(retain, nonatomic) NSDate *dateEnabled; // @synthesize dateEnabled=_dateEnabled;
@property(retain, nonatomic) NSDate *dateRegistered; // @synthesize dateRegistered=_dateRegistered;
@property(retain, nonatomic) NSDate *dateCreated; // @synthesize dateCreated=_dateCreated;
@property(nonatomic) long long pairingProtocolVersion; // @synthesize pairingProtocolVersion=_pairingProtocolVersion;
@property(nonatomic) _Bool isEmptyPairing; // @synthesize isEmptyPairing=_isEmptyPairing;
@property(nonatomic) _Bool lastSeenAlwaysOnWiFiSupported; // @synthesize lastSeenAlwaysOnWiFiSupported=_lastSeenAlwaysOnWiFiSupported;
@property(retain, nonatomic) NSString *lastSeenBuildVersion; // @synthesize lastSeenBuildVersion=_lastSeenBuildVersion;
@property(retain, nonatomic) NSString *lastSeenName; // @synthesize lastSeenName=_lastSeenName;
@property(nonatomic) unsigned short lastSeenInnerLinkVersionHBO; // @synthesize lastSeenInnerLinkVersionHBO=_lastSeenInnerLinkVersionHBO;
@property(nonatomic) _Bool wasInitiallySetupUsingIDSPairing; // @synthesize wasInitiallySetupUsingIDSPairing=_wasInitiallySetupUsingIDSPairing;
@property(retain, nonatomic) NSData *bluetoothMACAddress; // @synthesize bluetoothMACAddress=_bluetoothMACAddress;
@property(nonatomic) _Bool usesSPPLink; // @synthesize usesSPPLink=_usesSPPLink;
@property(retain, nonatomic) NSData *outOfBandKey; // @synthesize outOfBandKey=_outOfBandKey;
@property(retain, nonatomic) NSData *receivedProxyNotifyPayload; // @synthesize receivedProxyNotifyPayload=_receivedProxyNotifyPayload;
@property(nonatomic) _Bool hasConfirmedClassAKeys; // @synthesize hasConfirmedClassAKeys=_hasConfirmedClassAKeys;
@property(nonatomic) _Bool hasConfirmedClassCKeys; // @synthesize hasConfirmedClassCKeys=_hasConfirmedClassCKeys;
@property(nonatomic) _Bool hasConfirmedClassDKeys; // @synthesize hasConfirmedClassDKeys=_hasConfirmedClassDKeys;
@property(retain, nonatomic) NRDLDKeys *classCKeys; // @synthesize classCKeys=_classCKeys;
@property(retain, nonatomic) NRDLDKeys *classDKeys; // @synthesize classDKeys=_classDKeys;
@property(nonatomic) _Bool isEnabled; // @synthesize isEnabled=_isEnabled;
@property(nonatomic) _Bool isRegistered; // @synthesize isRegistered=_isRegistered;
@property(retain, nonatomic) NSUUID *bluetoothUUID; // @synthesize bluetoothUUID=_bluetoothUUID;
@property(retain, nonatomic) NSUUID *nrUUID; // @synthesize nrUUID=_nrUUID;
- (void)reportEvent:(int)arg1;	// IMP=0x00000001000ae428
- (void)reportEvent:(int)arg1 detailsFormat:(id)arg2;	// IMP=0x00000001000ae394
- (void)reportEvent:(int)arg1 details:(id)arg2;	// IMP=0x00000001000ae324
- (id)copyLocalInnerAddresses;	// IMP=0x00000001000ae1e8
- (id)copyLocalLinkLocalAddressString;	// IMP=0x00000001000ae180
- (void)writeRemoteClassCInnerAddressBytes:(struct in6_addr *)arg1;	// IMP=0x00000001000ae058
- (void)writeRemoteClassDInnerAddressBytes:(struct in6_addr *)arg1;	// IMP=0x00000001000adf30
- (void)writeRemoteClassCInnerAddressSockAddrBytes:(struct sockaddr_in6 *)arg1;	// IMP=0x00000001000addf4
- (void)writeRemoteClassDInnerAddressSockAddrBytes:(struct sockaddr_in6 *)arg1;	// IMP=0x00000001000adcb8
- (void)writeLocalClassCInnerAddressBytes:(struct in6_addr *)arg1;	// IMP=0x00000001000adb90
- (void)writeLocalClassDInnerAddressBytes:(struct in6_addr *)arg1;	// IMP=0x00000001000ada68
- (id)copyLocalInnerEndpointLinkLocal;	// IMP=0x00000001000ad9e8
- (void)writeLocalClassCInnerAddressSockAddrBytes:(struct sockaddr_in6 *)arg1;	// IMP=0x00000001000ad8ac
- (void)writeLocalClassDInnerAddressSockAddrBytes:(struct sockaddr_in6 *)arg1;	// IMP=0x00000001000ad770
- (id)copyRemoteAddressStrings;	// IMP=0x00000001000ad698
- (id)copyRemoteClassCAddressString;	// IMP=0x00000001000ad630
- (id)copyRemoteClassDAddressString;	// IMP=0x00000001000ad5c8
- (id)copyLocalClassCAddressString;	// IMP=0x00000001000ad560
- (id)copyLocalClassDAddressString;	// IMP=0x00000001000ad4f8
- (id)copyRemoteClassCInnerEndpoint;	// IMP=0x00000001000ad4b4
- (id)copyRemoteClassDInnerEndpoint;	// IMP=0x00000001000ad470
- (id)copyLocalClassCInnerEndpoint;	// IMP=0x00000001000ad42c
- (id)copyLocalClassDInnerEndpoint;	// IMP=0x00000001000ad3e8
- (id)copyRemoteClassCInnerEndpointWithPort:(id)arg1;	// IMP=0x00000001000ad1f8
- (id)copyRemoteClassDInnerEndpointWithPort:(id)arg1;	// IMP=0x00000001000ad034
- (id)copyLocalClassCInnerEndpointWithPort:(id)arg1;	// IMP=0x00000001000ace44
- (id)copyLocalClassDInnerEndpointWithPort:(id)arg1;	// IMP=0x00000001000acc80
- (_Bool)hasReceivedRemoteClassCInnerAddress;	// IMP=0x00000001000acc38
- (_Bool)hasReceivedRemoteClassDInnerAddress;	// IMP=0x00000001000acbf0
- (void)encodeWithCoder:(id)arg1;	// IMP=0x00000001000ac60c
- (id)initWithCoder:(id)arg1;	// IMP=0x00000001000abb40
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000ab344
- (id)copyLongDescription;	// IMP=0x00000001000aa2b4
- (id)description;	// IMP=0x00000001000aa094
- (id)initWithNRUUID:(id)arg1;	// IMP=0x00000001000a9ed8
- (void)fillInClassAKeysWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a9d3c
- (void)fillInClassCKeysWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00000001000a9b7c
- (void)fillInKeysForCurrentlyUnlockedWithForceClassA:(_Bool)arg1;	// IMP=0x00000001000a9594
- (_Bool)fillInClassDKeys;	// IMP=0x00000001000a9350
@property(readonly, nonatomic) _Bool hasOutOfBandKey;
- (id)copyKeys:(unsigned char)arg1;	// IMP=0x00000001000a9204
@property(readonly, nonatomic) _Bool isEnabledAndHasCompletedPairing;
@property(readonly, nonatomic) _Bool hasCompletedPairing;

@end

