//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKPlayerOwnedListCacheObject.h"

@interface GKGameRecommendationListCacheObject : GKPlayerOwnedListCacheObject
{
}

+ (Class)entryClass;	// IMP=0x0000000100055a04
+ (id)entityName;	// IMP=0x00000001000559f8
- (id)internalRepresentation;	// IMP=0x0000000100055ce4
- (void)updateWithServerRepresentation:(id)arg1 expirationDate:(id)arg2;	// IMP=0x0000000100055a10

@end

