//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "GKPlayerProfileCacheReader.h"

@interface GKPlayerProfileSelfCacheReader : GKPlayerProfileCacheReader
{
}

- (id)processAvailableResource:(id)arg1 retrievedWithStatement:(struct sqlite3_stmt *)arg2 fromDatabase:(struct sqlite3 *)arg3 statementStore:(id)arg4;	// IMP=0x00000001000803f0
- (id)emailForPlayerEmailStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x00000001000802e8
- (void)bindParametersForEmailsStatement:(struct sqlite3_stmt *)arg1 playerRowID:(int)arg2;	// IMP=0x0000000100080298
- (id)playerEmailsSQLString;	// IMP=0x0000000100080160
- (double)photoPendingTTLForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x0000000100080154
- (double)friendRequestsTTLForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x0000000100080148
- (double)challengesTTLForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x000000010008013c
- (double)TTLForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x0000000100080130
- (int)rowIDForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x0000000100080124
- (int)lastPlayedGameRowIDForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x0000000100080118
- (int)availablePiecesForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x000000010008010c
- (id)playerForProfileStatementResult:(struct sqlite3_stmt *)arg1;	// IMP=0x000000010007faec
- (void)bindParametersForProfileStatement:(struct sqlite3_stmt *)arg1 playerGCID:(id)arg2;	// IMP=0x000000010007faa8
- (id)playerProfileSQLString;	// IMP=0x000000010007f960

@end

