//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface SYDDeviceInfo : NSObject
{
    NSDictionary *_systemDictionary;	// 8 = 0x8
    NSDictionary *_frameworkDictionary;	// 16 = 0x10
}

+ (_Bool)isHomePod;	// IMP=0x0000000100042be0
+ (id)productVersion;	// IMP=0x0000000100042b9c
+ (id)userAgentHeader;	// IMP=0x0000000100042a60
+ (id)clientInfoHeader;	// IMP=0x0000000100042868
+ (id)osVersion;	// IMP=0x0000000100042824
- (void).cxx_destruct;	// IMP=0x0000000100042f74
@property(retain, nonatomic) NSDictionary *frameworkDictionary; // @synthesize frameworkDictionary=_frameworkDictionary;
@property(retain, nonatomic) NSDictionary *systemDictionary; // @synthesize systemDictionary=_systemDictionary;
- (id)frameworkIdentifier;	// IMP=0x0000000100042eec
- (id)frameworkVersion;	// IMP=0x0000000100042e58
- (id)buildVersion;	// IMP=0x0000000100042df8
- (id)osName;	// IMP=0x0000000100042d98
- (id)systemInfoDictionary;	// IMP=0x0000000100042d5c
- (id)frameworkInfoDictionary;	// IMP=0x0000000100042cf8
- (_Bool)isHomePod;	// IMP=0x0000000100042c9c
- (id)productType;	// IMP=0x0000000100042c88
- (id)productVersion;	// IMP=0x0000000100042c74
- (id)wifiMacAddress;	// IMP=0x0000000100042c60
- (id)serialNumber;	// IMP=0x0000000100042c4c
- (id)osVersion;	// IMP=0x0000000100042c38
- (id)gestaltValueForKey:(struct __CFString *)arg1;	// IMP=0x0000000100042c1c
- (id)init;	// IMP=0x00000001000427f0

@end

