//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class SMBDirEntry, SMBDirEnumerator, smbNode;
@protocol OS_dispatch_queue;

@interface dirEnumerator : NSObject
{
    int _enumState;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dirEnumerationSyncQueue;	// 16 = 0x10
    SMBDirEnumerator *_deObj;	// 24 = 0x18
    SMBDirEntry *_dentObjSave;	// 32 = 0x20
    SMBDirEntry *_tmpDent;	// 40 = 0x28
    smbNode *_dnp;	// 48 = 0x30
    unsigned long long _entryIndex;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x0000000100006314
@property int enumState; // @synthesize enumState=_enumState;
@property(readonly) unsigned long long entryIndex; // @synthesize entryIndex=_entryIndex;
@property(readonly) smbNode *dnp; // @synthesize dnp=_dnp;
@property(retain) SMBDirEntry *tmpDent; // @synthesize tmpDent=_tmpDent;
@property(retain) SMBDirEntry *dentObjSave; // @synthesize dentObjSave=_dentObjSave;
@property(retain) SMBDirEnumerator *deObj; // @synthesize deObj=_deObj;
@property(retain) NSObject<OS_dispatch_queue> *dirEnumerationSyncQueue; // @synthesize dirEnumerationSyncQueue=_dirEnumerationSyncQueue;
- (void)processNextEntry:(unsigned int)arg1 inbufPtr:(char *)arg2 prevEntry:(void *)arg3 inbufRemain:(unsigned long long)arg4 bytesFilled:(unsigned int)arg5 IsReadDirAttr:(_Bool)arg6 CompletionHandler:(CDUnknownBlockType)arg7;	// IMP=0x0000000100005f94
- (void)_getEntriesInBuffer:(char *)arg1 BufferLen:(unsigned long long)arg2 CookieIn:(unsigned long long)arg3 VerifyIn:(unsigned long long)arg4 IsReadDirAttr:(_Bool)arg5 CompletionHandler:(CDUnknownBlockType)arg6;	// IMP=0x0000000100005d24
- (void)getEntriesInBuffer:(char *)arg1 BufferLen:(unsigned long long)arg2 CookieIn:(unsigned long long)arg3 VerifyIn:(unsigned long long)arg4 IsReadDirAttr:(_Bool)arg5 CompletionHandler:(CDUnknownBlockType)arg6;	// IMP=0x0000000100005b34
- (int)fillNextEntry:(char *)arg1 BufLen:(unsigned long long)arg2 IsReadDirAttr:(_Bool)arg3 BytesFilled:(unsigned int *)arg4;	// IMP=0x0000000100005564
- (int)fillDirEntry:(char *)arg1 withBufLen:(unsigned long long)arg2 DirEntry:(id)arg3 IsReadDirAttr:(_Bool)arg4 retBytesWritten:(unsigned int *)arg5;	// IMP=0x0000000100004ee4
- (int)resetCurrentIndex:(unsigned long long)arg1;	// IMP=0x0000000100004e04
- (int)skipAnEntry;	// IMP=0x0000000100004b80
- (void)close_dir_enum;	// IMP=0x0000000100004b60
- (int)restart_dir_enum;	// IMP=0x0000000100004aa4
- (int)openEnumeration;	// IMP=0x0000000100004838
- (int)closeEnumeration;	// IMP=0x0000000100004658
- (void)resetAfterReconnect;	// IMP=0x00000001000045fc
- (id)initWithNode:(id)arg1;	// IMP=0x0000000100004538

@end

