//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SMBNode;
@protocol OS_dispatch_queue;

@interface fileRef : NSObject
{
    int _reconnState;	// 8 = 0x8
    int _ownerPid;	// 12 = 0xc
    unsigned int _openMode;	// 16 = 0x10
    unsigned int _refCount;	// 20 = 0x14
    unsigned int _shareMode;	// 24 = 0x18
    unsigned int _desiredAccess;	// 28 = 0x1c
    unsigned int _createDisposition;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_refSyncQueue;	// 40 = 0x28
    SMBNode *_fidCtx;	// 48 = 0x30
    NSString *_streamName;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x000000010003029c
@property(retain) NSString *streamName; // @synthesize streamName=_streamName;
@property unsigned int createDisposition; // @synthesize createDisposition=_createDisposition;
@property unsigned int desiredAccess; // @synthesize desiredAccess=_desiredAccess;
@property unsigned int shareMode; // @synthesize shareMode=_shareMode;
@property(retain) SMBNode *fidCtx; // @synthesize fidCtx=_fidCtx;
@property unsigned int refCount; // @synthesize refCount=_refCount;
@property unsigned int openMode; // @synthesize openMode=_openMode;
@property int ownerPid; // @synthesize ownerPid=_ownerPid;
@property int reconnState; // @synthesize reconnState=_reconnState;
@property(retain) NSObject<OS_dispatch_queue> *refSyncQueue; // @synthesize refSyncQueue=_refSyncQueue;
- (void)dealloc;	// IMP=0x00000001000301bc
- (unsigned int)decRef;	// IMP=0x0000000100030058
- (void)addRef;	// IMP=0x000000010002ffc8
- (_Bool)hasConflict:(unsigned int)arg1;	// IMP=0x000000010002fef8
- (id)initWithPID:(int)arg1 andMode:(unsigned int)arg2;	// IMP=0x000000010002fe68

@end

