//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIViewController.h>

@protocol ServiceBridgedPresentationControllerProxy;

@interface ServicePresentationSafariViewController : UIViewController
{
    id <ServiceBridgedPresentationControllerProxy> _proxyHandler;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010001fe80
@property(nonatomic) __weak id <ServiceBridgedPresentationControllerProxy> proxyHandler; // @synthesize proxyHandler=_proxyHandler;
- (void)_setChildViewController:(id)arg1;	// IMP=0x000000010001fcec
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x000000010001fc18
- (void)loadView;	// IMP=0x000000010001fb80
- (id)initWithSafariViewController:(id)arg1 proxyHandler:(id)arg2;	// IMP=0x000000010001fac4

@end

