//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface MLDDatabaseFileDiagnostic : NSObject
{
    NSString *_databasePath;	// 8 = 0x8
    NSArray *_processesWithOpenFileHandles;	// 16 = 0x10
    NSDictionary *_fileAttributes;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0000000100008b74
@property(readonly, nonatomic) NSDictionary *fileAttributes; // @synthesize fileAttributes=_fileAttributes;
@property(readonly, nonatomic) NSArray *processesWithOpenFileHandles; // @synthesize processesWithOpenFileHandles=_processesWithOpenFileHandles;
@property(readonly, nonatomic) NSString *databasePath; // @synthesize databasePath=_databasePath;
- (id)description;	// IMP=0x000000010000897c
- (id)initWithDatabasePath:(id)arg1;	// IMP=0x0000000100008880

@end

