//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CKKSResultOperation.h"

@class CKKSKeychainView;

__attribute__((visibility("hidden")))
@interface CKKSProcessReceivedKeysStateMachineOperation : CKKSResultOperation
{
    CKKSKeychainView *_ckks;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x000000010015b6fc
@property __weak CKKSKeychainView *ckks; // @synthesize ckks=_ckks;
- (void)main;	// IMP=0x000000010015b5f0
- (id)initWithCKKSKeychainView:(id)arg1;	// IMP=0x000000010015b57c

@end

