//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class LiveFSServiceClient, NSDate, NSString, NSXPCConnection, NSXPCListenerEndpoint;
@protocol NSFileProviderLiveItemCore;

@interface VolumeScan : NSObject
{
    NSString *_uuidString;	// 8 = 0x8
    NSString *_volumeName;	// 16 = 0x10
    const char *_rootPathUTF8String;	// 24 = 0x18
    NSDate *_mountTime;	// 32 = 0x20
    NSDate *_lastMTime;	// 40 = 0x28
    unsigned long long _rootPathUTF8StringLength;	// 48 = 0x30
    NSXPCListenerEndpoint *_volumeListenerEndpoint;	// 56 = 0x38
    NSXPCConnection *_volumeAsyncConnection;	// 64 = 0x40
    LiveFSServiceClient *_serviceClient;	// 72 = 0x48
    id <NSFileProviderLiveItemCore> _volumeSyncConnection;	// 80 = 0x50
    NSString *_rootPath;	// 88 = 0x58
    NSString *_rootFileHandle;	// 96 = 0x60
}

+ (id)volumeNames;	// IMP=0x000000010001dfa8
+ (id)mountServiceClient;	// IMP=0x000000010001df94
- (void).cxx_destruct;	// IMP=0x0000000100020c6c
@property(retain, nonatomic) NSString *rootFileHandle; // @synthesize rootFileHandle=_rootFileHandle;
@property(retain, nonatomic) NSString *rootPath; // @synthesize rootPath=_rootPath;
@property(retain, nonatomic) id <NSFileProviderLiveItemCore> volumeSyncConnection; // @synthesize volumeSyncConnection=_volumeSyncConnection;
@property(retain, nonatomic) LiveFSServiceClient *serviceClient; // @synthesize serviceClient=_serviceClient;
@property(retain, nonatomic) NSXPCConnection *volumeAsyncConnection; // @synthesize volumeAsyncConnection=_volumeAsyncConnection;
@property(retain, nonatomic) NSXPCListenerEndpoint *volumeListenerEndpoint; // @synthesize volumeListenerEndpoint=_volumeListenerEndpoint;
@property(readonly, nonatomic) unsigned long long rootPathUTF8StringLength; // @synthesize rootPathUTF8StringLength=_rootPathUTF8StringLength;
@property(readonly, nonatomic) NSDate *lastMTime; // @synthesize lastMTime=_lastMTime;
@property(readonly, nonatomic) NSDate *mountTime; // @synthesize mountTime=_mountTime;
@property(readonly, nonatomic) const char *rootPathUTF8String; // @synthesize rootPathUTF8String=_rootPathUTF8String;
@property(readonly, nonatomic) NSString *volumeName; // @synthesize volumeName=_volumeName;
@property(retain, nonatomic) NSString *uuidString; // @synthesize uuidString=_uuidString;
- (id)processQueryScopes:(id)arg1 usePersistentFileIDs:(_Bool)arg2;	// IMP=0x0000000100020474
- (id)identifierForItem:(unsigned long long)arg1 name:(id)arg2 parentID:(unsigned long long)arg3;	// IMP=0x00000001000203c0
- (char *)pathFromOID:(unsigned long long)arg1 pathBuffer:(char *)arg2 pathBufferSize:(unsigned long long)arg3 fullPath:(_Bool)arg4 error:(int *)arg5;	// IMP=0x00000001000202c8
- (unsigned int)oidPath:(unsigned long long *)arg1 fromOID:(unsigned long long)arg2 includeLeaf:(_Bool)arg3 error:(int *)arg4;	// IMP=0x0000000100020218
- (unsigned long long)parentFromOID:(unsigned long long)arg1 error:(int *)arg2;	// IMP=0x0000000100020098
- (_Bool)buildCheckOIDs:(unsigned long long *)arg1 oidCount:(unsigned long long)arg2 accessDenied:(char *)arg3 canceled:(_Bool *)arg4;	// IMP=0x000000010001ff54
- (id)bulkResolveOIDs:(unsigned long long *)arg1 oidCount:(unsigned long long)arg2 error:(int *)arg3;	// IMP=0x000000010001fed8
- (id)bulkResolveOIDData:(id)arg1 error:(int *)arg2;	// IMP=0x000000010001fc64
- (void)cancelWithToken:(id)arg1;	// IMP=0x000000010001fa7c
- (id)scanAtLiveFSHandle:(id)arg1 pathFromMountPoint:(id)arg2 date:(id)arg3 itemHandler:(CDUnknownBlockType)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010001f814
- (id)scanAtLiveFSHandle:(id)arg1 pathFromMountPoint:(id)arg2 withCriteria:(id)arg3 itemHandler:(CDUnknownBlockType)arg4 completionHandler:(CDUnknownBlockType)arg5;	// IMP=0x000000010001ef08
- (id)resolveLiveFSHandleForPathFromMountPoint:(const char *)arg1;	// IMP=0x000000010001eb08
- (id)initWithVolumeName:(id)arg1 rootPath:(id)arg2;	// IMP=0x000000010001e078
- (void)dealloc;	// IMP=0x000000010001e030

@end

