//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "FAFamilyCircleOperation.h"

@class NSData, NSString;

@interface FARegisterPushTokenOperation : FAFamilyCircleOperation
{
    NSString *_appleIDorDSID;	// 8 = 0x8
    NSString *_passwordOrAuthToken;	// 16 = 0x10
    NSData *_pushToken;	// 24 = 0x18
    CDUnknownBlockType _registerTokenCompletionHandler;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x000000010000e9fc
@property(copy) CDUnknownBlockType registerTokenCompletionHandler; // @synthesize registerTokenCompletionHandler=_registerTokenCompletionHandler;
@property(readonly) NSData *pushToken; // @synthesize pushToken=_pushToken;
- (void)didFailWithError:(id)arg1;	// IMP=0x000000010000e948
- (void)didReceivePropertyListResponse:(id)arg1;	// IMP=0x000000010000e8c8
- (id)urlRequest;	// IMP=0x000000010000e650
- (id)pushTokenString;	// IMP=0x000000010000e554
- (id)initWithUsername:(id)arg1 password:(id)arg2 pushToken:(id)arg3;	// IMP=0x000000010000e434

@end

