//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol OS_dispatch_queue;

@interface DaemonBiometricKeychain : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueueX509;	// 16 = 0x10
}

+ (void)_handleMessage:(id)arg1 connection:(id)arg2 withReplyBlock:(CDUnknownBlockType)arg3;	// IMP=0x00000001000fa44c
+ (void)x509CertChainDataWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00000001000fa1c0
+ (void)signDataUsingContextWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00000001000f9b5c
+ (void)signDataWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00000001000f952c
+ (void)getPublicKeyDataWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00000001000f92e8
+ (void)deleteKeychainTokensWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00000001000f90c8
+ (void)createX509CertChainDataWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00000001000f8e84
+ (void)createAttestationDataWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x00000001000f8c40
+ (void)observeXPCServer:(id)arg1;	// IMP=0x00000001000f8b40
+ (id)sharedInstance;	// IMP=0x00000001000f383c
- (void).cxx_destruct;	// IMP=0x000000010010688c
- (id)_signData:(id)arg1 context:(id)arg2 error:(id *)arg3;	// IMP=0x0000000100105d88
- (id)_regenerateKeychainTokensForAccountIdentifier:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x000000010010533c
- (id)_queryForPrivateKeyWithLabel:(id)arg1 prompt:(id)arg2 useTokenID:(_Bool)arg3;	// IMP=0x000000010010503c
- (id)_queryForPrivateKeyWithLabel:(id)arg1 prompt:(id)arg2;	// IMP=0x0000000100104fd4
- (id)_publicKeyDataForAccountIdentifier:(id)arg1 purpose:(long long)arg2 regenerateKeys:(_Bool)arg3 error:(id *)arg4;	// IMP=0x0000000100104618
- (id)_presentPaymentSheetForChallenge:(id)arg1 authContext:(id)arg2 biometricContext:(id)arg3 touchIDContext:(id)arg4 touchIDOptions:(id)arg5 accessControlRef:(struct __SecAccessControl *)arg6 passwordToken:(id *)arg7 paymentTokenData:(id *)arg8 fpanID:(id *)arg9 error:(id *)arg10;	// IMP=0x00000001001034f4
- (_Bool)_generateKeychainTokensForAccountIdentifier:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x000000010010265c
- (_Bool)_deleteKeychainTokensForAccountIdentifier:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x0000000100100bd0
- (_Bool)_deleteKeychainTokensForAccountIdentifier:(id)arg1 error:(id *)arg2;	// IMP=0x0000000100100728
- (id)_createX509CertChainDataForAccountIdentifier:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x00000001000fd7ac
- (id)_createAttestationDataForAccountIdentifier:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x00000001000fcc10
- (id)_copyPublicKeyDataForAccountIdentifier:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x00000001000fb374
- (id)_constraintsForPurchase;	// IMP=0x00000001000fac54
- (id)_constraintsForExtendedActions;	// IMP=0x00000001000fa95c
- (_Bool)_isDeviceUnlocked;	// IMP=0x00000001000fa794
- (id)signDataWithKeychain:(id)arg1 accountIdentifier:(id)arg2 purpose:(long long)arg3 localAuthContext:(id)arg4 localAuthOptions:(id)arg5 error:(id *)arg6;	// IMP=0x00000001000f6610
- (struct __SecAccessControl *)copyAccessControlListForPrivateKeyWithBiometricAuthenticationContext:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000f60f8
- (struct __SecAccessControl *)copyAccessControlListForKey:(struct __SecKey *)arg1 error:(id *)arg2;	// IMP=0x00000001000f5dc0
- (id)x509CertChainDataForAccountIdentifier_:(id)arg1 purpose:(long long)arg2 regenerateCerts:(_Bool)arg3 error:(id *)arg4;	// IMP=0x00000001000f5110
- (id)signData_:(id)arg1 context:(id)arg2 error:(id *)arg3;	// IMP=0x00000001000f4bf8
- (id)publicKeyDataForAccountIdentifier_:(id)arg1 purpose:(long long)arg2 regenerateKeys:(_Bool)arg3 error:(id *)arg4;	// IMP=0x00000001000f47b8
- (id)publicKeyDataForAccountIdentifier_:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x00000001000f47a4
- (_Bool)deleteKeychainTokensForAccountIdentifier_:(id)arg1 error:(id *)arg2;	// IMP=0x00000001000f45a0
- (id)createX509CertChainDataForAccountIdentifier_:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x00000001000f4154
- (id)createAttestationDataForAccountIdentifier_:(id)arg1 purpose:(long long)arg2 error:(id *)arg3;	// IMP=0x00000001000f3978
- (id)init;	// IMP=0x00000001000f38f0

@end

