//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

@class SSMemoryEntity;

@interface ExpiredDownloadRecoveryOperation : ISOperation
{
    SSMemoryEntity *_download;	// 96 = 0x60
    CDUnknownBlockType _outputBlock;	// 104 = 0x68
}

+ (_Bool)canAttemptRecoveryWithError:(id)arg1;	// IMP=0x00000001001c15ec
- (void).cxx_destruct;	// IMP=0x00000001001c2118
- (void)run;	// IMP=0x00000001001c17bc
@property(copy) CDUnknownBlockType outputBlock;
- (id)initWithDownloadIdentifier:(long long)arg1 databaseSession:(id)arg2;	// IMP=0x00000001001c13f8

@end

