//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

@class NSString;

@interface MediaDRMOperation : ISOperation
{
    NSString *_mediaFileExtension;	// 96 = 0x60
    NSString *_mediaPath;	// 104 = 0x68
    id _sinfs;	// 112 = 0x70
}

- (void)run;	// IMP=0x0000000100025c18
@property(readonly) id sinfs;
@property(readonly) NSString *mediaPath;
@property(readonly) NSString *mediaFileExtension;
- (void)dealloc;	// IMP=0x0000000100025b14
- (id)initWithMediaPath:(id)arg1 sinfs:(id)arg2;	// IMP=0x0000000100025a84

@end

