//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSString;

@interface PersistentStoreConfiguration : NSObject <NSCopying>
{
    NSString *_databaseFileName;	// 8 = 0x8
    NSArray *_legacyModelVersionIdentifiers;	// 16 = 0x10
    NSString *_modelFileName;	// 24 = 0x18
    int _storeType;	// 32 = 0x20
}

@property(nonatomic) int storeType; // @synthesize storeType=_storeType;
@property(retain, nonatomic) NSString *modelFileName; // @synthesize modelFileName=_modelFileName;
@property(copy, nonatomic) NSArray *legacyModelVersionIdentifiers; // @synthesize legacyModelVersionIdentifiers=_legacyModelVersionIdentifiers;
@property(retain, nonatomic) NSString *databaseFileName; // @synthesize databaseFileName=_databaseFileName;
@property(readonly, nonatomic) NSString *integrityCookieFileName;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00000001000988e8
- (void)dealloc;	// IMP=0x0000000100098890
- (id)initWithStoreType:(int)arg1;	// IMP=0x00000001000986e8

@end

