//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <iTunesStore/ISOperation.h>

@class NSString, SSMutableAuthenticationContext;

@interface PurchaseAuthenticateOperation : ISOperation
{
    CDUnknownBlockType _authenticationBlock;	// 96 = 0x60
    SSMutableAuthenticationContext *_authenticationContext;	// 104 = 0x68
}

- (id)_userAgentForPurchases:(id)arg1;	// IMP=0x00000001001eb310
- (id)_clientIdentifierForPurchases:(id)arg1;	// IMP=0x00000001001eb1b8
- (void)run;	// IMP=0x00000001001eafec
@property(copy) NSString *clientIdentifierHeader;
@property(copy) CDUnknownBlockType authenticationBlock;
- (void)dealloc;	// IMP=0x00000001001eae20
- (id)initWithPurchases:(id)arg1;	// IMP=0x00000001001eac40

@end

