//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary, NSString;
@protocol OS_dispatch_queue;

@interface PurchaseManifest : NSObject
{
    NSMutableDictionary *_dictionary;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 16 = 0x10
    NSString *_path;	// 24 = 0x18
}

+ (id)_sharedManifestWithManifestType:(long long)arg1;	// IMP=0x000000010000e7e8
+ (void)_handleMessage:(id)arg1 connection:(id)arg2 usingBlock:(CDUnknownBlockType)arg3;	// IMP=0x000000010000e60c
+ (void)removeItemWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x000000010000e384
+ (void)rebuildWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x000000010000e2a8
+ (void)observeXPCServer:(id)arg1;	// IMP=0x000000010000e228
+ (void)getPathsWithMessage:(id)arg1 connection:(id)arg2;	// IMP=0x000000010000dea8
+ (id)sharedManifestForDownloadKind:(id)arg1;	// IMP=0x000000010000bf60
+ (void)jetsam;	// IMP=0x000000010000befc
- (_Bool)_writeToFile;	// IMP=0x000000010000eb78
- (id)_dictionary;	// IMP=0x000000010000e820
- (id)removeItemsWithAssetPaths:(id)arg1 error:(id *)arg2;	// IMP=0x000000010000cf0c
- (void)rebuildManifest;	// IMP=0x000000010000c718
@property(readonly) NSArray *purchaseManifestItems;
@property(readonly) NSString *path;
- (void)jetsam;	// IMP=0x000000010000c494
- (void)addCompletedItem:(id)arg1;	// IMP=0x000000010000c174
- (void)dealloc;	// IMP=0x000000010000bea4
- (id)initWithPurchaseDirectory:(id)arg1;	// IMP=0x000000010000bda8
- (id)init;	// IMP=0x000000010000bd98

@end

