//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "CLLocationManagerDelegate-Protocol.h"

@class MISSING_TYPE;

@interface _TtC8coreidvd17DIPLocationHelper : NSObject <CLLocationManagerDelegate>
{
    MISSING_TYPE *locationManager;	// 8 = 0x8
    MISSING_TYPE *location;	// 16 = 0x10
    MISSING_TYPE *serviceQueue;	// 24 = 0x18
    MISSING_TYPE *authorizationStatus;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00000001000d481c
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;	// IMP=0x00000001000d527c
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;	// IMP=0x00000001000d5158
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;	// IMP=0x00000001000d50bc
- (void)dealloc;	// IMP=0x00000001000d47f8
- (id)init;	// IMP=0x00000001000d3f58

@end

