//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "BaseRequestHandler.h"

@class CloudArtistHeroImageImporter;

@interface ArtistImageRequestHandler : BaseRequestHandler
{
    CloudArtistHeroImageImporter *_importer;	// 8 = 0x8
}

+ (id)handler;	// IMP=0x00000001000d9a38
+ (id)accountlessHandler;	// IMP=0x00000001000d9994
+ (_Bool)supportsAccountlessHandling;	// IMP=0x00000001000d989c
+ (id)handlers;	// IMP=0x00000001000d9830
- (void).cxx_destruct;	// IMP=0x00000001000d9db0
@property(readonly, nonatomic) CloudArtistHeroImageImporter *importer; // @synthesize importer=_importer;
- (void)deprioritizeAlbumArtistHeroImageForPersistentID:(long long)arg1;	// IMP=0x00000001000d9d88
- (void)deprioritizeArtistHeroImageForPersistentID:(long long)arg1;	// IMP=0x00000001000d9d70
- (void)importAlbumArtistHeroImageForPersistentID:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d9d58
- (void)importArtistHeroImageForPersistentID:(long long)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x00000001000d9d40
- (void)cancelAllOperationsAndWaitForOperationsToFinish:(_Bool)arg1;	// IMP=0x00000001000d9d28
- (void)cancelAllOperations;	// IMP=0x00000001000d9d18
- (void)updateArtistHeroImagesForArtistsAddedSinceLastUpdate;	// IMP=0x00000001000d9c38
- (void)updateArtistHeroImages;	// IMP=0x00000001000d9c20
- (id)initWithConfiguration:(id)arg1;	// IMP=0x00000001000d9a94

@end

