//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "CloudLibraryOperation.h"

@class NSArray, NSString;

@interface SagaCreateGeniusPlaylistOperation : CloudLibraryOperation
{
    long long _playlistPersistentID;	// 8 = 0x8
    NSString *_playlistName;	// 16 = 0x10
    NSArray *_seedItemIDs;	// 24 = 0x18
    NSArray *_itemIDs;	// 32 = 0x20
    unsigned long long _playlistSagaID;	// 40 = 0x28
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0000000100020528
- (void).cxx_destruct;	// IMP=0x0000000100020b70
@property(readonly, nonatomic) unsigned long long playlistSagaID; // @synthesize playlistSagaID=_playlistSagaID;
- (void)main;	// IMP=0x0000000100020788
- (_Bool)isPersistent;	// IMP=0x0000000100020780
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0000000100020690
- (id)initWithCoder:(id)arg1;	// IMP=0x0000000100020530
- (id)initWithConfiguration:(id)arg1 geniusPlaylistPersistentID:(long long)arg2 playlistName:(id)arg3 seedItemIDs:(id)arg4 itemIDs:(id)arg5;	// IMP=0x00000001000203e8
- (id)initWithGeniusPlaylistPersistentID:(long long)arg1 playlistName:(id)arg2 seedItemIDs:(id)arg3 itemIDs:(id)arg4;	// IMP=0x000000010002032c

@end

