//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class iAP2Connection;
@protocol OS_dispatch_queue;

@interface iAP2MsgVoiceOver : NSObject
{
    NSObject<OS_dispatch_queue> *_voiceOverQ;	// 8 = 0x8
    unsigned int _informationMask;	// 16 = 0x10
    unsigned int _propertyMask;	// 20 = 0x14
    _Bool _lastSentEnabled;	// 24 = 0x18
    unsigned char _lastSentVolume;	// 25 = 0x19
    unsigned char _lastSentRate;	// 26 = 0x1a
    iAP2Connection *_connection;	// 32 = 0x20
}

@property(nonatomic) unsigned char lastSentRate; // @synthesize lastSentRate=_lastSentRate;
@property(nonatomic) unsigned char lastSentVolume; // @synthesize lastSentVolume=_lastSentVolume;
@property(nonatomic) _Bool lastSentEnabled; // @synthesize lastSentEnabled=_lastSentEnabled;
@property(readonly, nonatomic) iAP2Connection *connection; // @synthesize connection=_connection;
- (void)shuttingDown;	// IMP=0x0000000100042f64
- (id)description;	// IMP=0x0000000100042f20
- (void)dealloc;	// IMP=0x0000000100042ecc
- (id)initWithConnection:(id)arg1;	// IMP=0x0000000100042e5c
@property(nonatomic) unsigned int propertyMask;
@property(nonatomic) unsigned int informationMask;

@end

