//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import "DAIDSMessageReceiver-Protocol.h"
#import "DAIDSMessageSender-Protocol.h"

@class NSString, NSXPCConnection;
@protocol DAIDSMessageReceiver, OS_dispatch_queue;

@interface DAIDSMessengerProxy : NSObject <DAIDSMessageReceiver, DAIDSMessageSender>
{
    id <DAIDSMessageReceiver> _receiver;	// 8 = 0x8
    NSXPCConnection *_connection;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_messageReceiverQueue;	// 24 = 0x18
}

+ (id)allowedDataClasses;	// IMP=0x0000000100007828
- (void).cxx_destruct;	// IMP=0x00000001000079ec
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *messageReceiverQueue; // @synthesize messageReceiverQueue=_messageReceiverQueue;
@property(retain, nonatomic) NSXPCConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) __weak id <DAIDSMessageReceiver> receiver; // @synthesize receiver=_receiver;
- (id)_createXPCConnection;	// IMP=0x00000001000073cc
- (void)receiveMessage:(id)arg1 data:(id)arg2 fromDestination:(id)arg3 expectsResponse:(_Bool)arg4 response:(CDUnknownBlockType)arg5;	// IMP=0x0000000100007190
- (void)sendMessage:(id)arg1 data:(id)arg2 toDestination:(id)arg3 forceLocalDelivery:(_Bool)arg4 expectsResponse:(_Bool)arg5 response:(CDUnknownBlockType)arg6;	// IMP=0x0000000100007004
- (void)availableDestinationsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0000000100006eec
- (id)init;	// IMP=0x0000000100006e5c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

