//
//     Generated by classdumpios 1.0.1 (64 bit) (iOS port by DreamDevLost)(Debug version compiled Sep 26 2020 13:48:20).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <UIKit/UIView.h>

@interface HSSetupCodeGlyphView : UIView
{
    unsigned long long _style;	// 8 = 0x8
}

@property(nonatomic) unsigned long long style; // @synthesize style=_style;
- (void)_prepareConstraintsForView:(id)arg1;	// IMP=0x0000000100028820
- (id)_clearView;	// IMP=0x000000010002879c
- (id)_activityIndicatorView;	// IMP=0x0000000100028714
- (id)_failureImageView;	// IMP=0x00000001000286a0
- (id)_successImageView;	// IMP=0x000000010002862c
- (id)_logoImageView;	// IMP=0x0000000100028570
- (id)_viewForStyle:(unsigned long long)arg1;	// IMP=0x00000001000284b0
- (void)pulse;	// IMP=0x0000000100028188
- (void)transitionToStyle:(unsigned long long)arg1 pulse:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0000000100027ca0
- (id)init;	// IMP=0x0000000100027c1c

@end

